var component_list = [
    'Active Oppose.png',
    'Active Support.png',
    'Aid.png',
    'ARVN Base.png',
    'ARVN Pawn.png',
    'ARVN Police.png',
    'ARVN Ranger (Active).png',
    'ARVN Ranger.png',
    'ARVN Troops.png',
    'Blank Square.png',
    'COIN+Patron.png',
    'Deception Back.png',
    'Deception Hidden Agenda (x4).png',
    'Deception Hidden Asset (x4).png',
    'Deception Hidden Threat (x4).png',
    'Deception Mask.png',
    'Econ.png',
    'Medevac-No Air Lift.png',
    'Medevac.png',
    'NVA Base.png',
    'NVA Guerrilla (Active).png',
    'NVA Guerrilla.png',
    'NVA Pawn.png',
    'NVA Troops.png',
    'NVA Tunnel.png',
    'NVA+Bases.png',
    'Oppose+Bases.png',
    'Passive Oppose.png',
    'Passive Support.png',
    'Patron.png',
    'PopBoxControl.png',
    'PopEcon.png',
    'Sabotage.png',
    'Support+Avail.png',
    'Terror.png',
    'The Trail.png',
    'US Policy.png',
    'USA Base.png',
    'USA Irregular (Active).png',
    'USA Irregular.png',
    'USA Pawn.png',
    'USA Troops.png',
    'VC Base.png',
    'VC Guerrilla (Active).png',
    'VC Guerrilla.png',
    'VC Pawn.png',
    'VC Tunnel.png',];