var cards_per_pixel_x = 1;
var cards_per_pixel_y = 1.5;

var card_abs_pos_top_start  = 400;
var card_abs_pos_left_start = 20;

var card_width = 200;
var card_height = 250;

var decks = [
    {
        'name': 'Event cards',
        'back': 'FITL Card Back.png',
        'fronts': [
            'FITL Card 01.png',
            'FITL Card 02.png',
            'FITL Card 03.png',
            'FITL Card 04.png',
            'FITL Card 05.png',
            'FITL Card 06.png',
            'FITL Card 07.png',
            'FITL Card 08.png',
            'FITL Card 09.png',
            'FITL Card 10.png',
            'FITL Card 11.png',
            'FITL Card 12.png',
            'FITL Card 13.png',
            'FITL Card 14.png',
            'FITL Card 15.png',
            'FITL Card 16.png',
            'FITL Card 17.png',
            'FITL Card 18.png',
            'FITL Card 19.png',
            'FITL Card 20.png',
            'FITL Card 21.png',
            'FITL Card 22.png',
            'FITL Card 23.png',
            'FITL Card 24.png',
            'FITL Card 25.png',
            'FITL Card 26.png',
            'FITL Card 27.png',
            'FITL Card 28.png',
            'FITL Card 29.png',
            'FITL Card 30.png',
            'FITL Card 31.png',
            'FITL Card 32.png',
            'FITL Card 33.png',
            'FITL Card 34.png',
            'FITL Card 35.png',
            'FITL Card 36.png',
            'FITL Card 37.png',
            'FITL Card 38.png',
            'FITL Card 39.png',
            'FITL Card 40.png',
            'FITL Card 41.png',
            'FITL Card 42.png',
            'FITL Card 43.png',
            'FITL Card 44.png',
            'FITL Card 45.png',
            'FITL Card 46.png',
            'FITL Card 47.png',
            'FITL Card 48.png',
            'FITL Card 49.png',
            'FITL Card 50.png',
            'FITL Card 51.png',
            'FITL Card 52.png',
            'FITL Card 53.png',
            'FITL Card 54.png',
            'FITL Card 55.png',
            'FITL Card 56.png',
            'FITL Card 57.png',
            'FITL Card 58.png',
            'FITL Card 59.png',
            'FITL Card 60.png',
            'FITL Card 61.png',
            'FITL Card 62.png',
            'FITL Card 63.png',
            'FITL Card 64.png',
            'FITL Card 65.png',
            'FITL Card 66.png',
            'FITL Card 67.png',
            'FITL Card 68.png',
            'FITL Card 69.png',
            'FITL Card 70.png',
            'FITL Card 71.png',
            'FITL Card 72.png',
            'FITL Card 73.png',
            'FITL Card 74.png',
            'FITL Card 75.png',
            'FITL Card 76.png',
            'FITL Card 77.png',
            'FITL Card 78.png',
            'FITL Card 79.png',
            'FITL Card 80.png',
            'FITL Card 81.png',
            'FITL Card 82.png',
            'FITL Card 83.png',
            'FITL Card 84.png',
            'FITL Card 85.png',
            'FITL Card 86.png',
            'FITL Card 87.png',
            'FITL Card 88.png',
            'FITL Card 89.png',
            'FITL Card 90.png',
            'FITL Card 91.png',
            'FITL Card 92.png',
            'FITL Card 93.png',
            'FITL Card 94.png',
            'FITL Card 95.png',
            'FITL Card 96.png',
            'FITL Card 97.png',
            'FITL Card 98.png',
            'FITL Card 99.png',
            'FITL Card 100.png',
            'FITL Card 101.png',
            'FITL Card 102.png',
            'FITL Card 103.png',
            'FITL Card 104.png',
            'FITL Card 105.png',
            'FITL Card 106.png',
            'FITL Card 107.png',
            'FITL Card 108.png',
            'FITL Card 109.png',
            'FITL Card 110.png',
            'FITL Card 111.png',
            'FITL Card 112.png',
            'FITL Card 113.png',
            'FITL Card 114.png',
            'FITL Card 115.png',
            'FITL Card 116.png',
            'FITL Card 117.png',
            'FITL Card 118.png',
            'FITL Card 119.png',
            'FITL Card 120.png',
            'FITL Card 121.png',
            'FITL Card 122.png',
            'FITL Card 123.png',
            'FITL Card 124.png',
        ]
    },
    {
        'name': 'Coup cards',
        'back': 'FITL Card Back.png',
        'fronts': [
            'FITL Card 125.png',
            'FITL Card 126.png',
            'FITL Card 127.png',
            'FITL Card 128.png',
            'FITL Card 129.png',
            'FITL Card 130.png'
        ]
    }
];
