var component_list = [
    [
        "British",
        ["br-1-1-arty-bttn", {"b": "BR-1-1-Arty-Bttn-r.png", "f": "BR-1-1-Arty-Bttn-f.png"}],
        ["br-1-12gp-gldr-inf-bttn", {"b": "BR-1-12GP-Gldr-Inf-Bttn-r.png", "f": "BR-1-12GP-Gldr-Inf-Bttn-f.png"}],
        ["br-1-1a-1b-a-gldr-inf-bttn", {"b": "BR-1-1A-1B-A-Gldr-Inf-Bttn-r.png", "f": "BR-1-1A-1B-A-Gldr-Inf-Bttn-f.png"}],
        ["br-1-1a-1b-b-gldr-inf-bttn", {"b": "BR-1-1A-1B-B-Gldr-Inf-Bttn-r.png", "f": "BR-1-1A-1B-B-Gldr-Inf-Bttn-f.png"}],
        ["br-1-1a-1ss-a-gldr-inf-bttn", {"b": "BR-1-1A-1SS-A-Gldr-Inf-Bttn-r.png", "f": "BR-1-1A-1SS-A-Gldr-Inf-Bttn-f.png"}],
        ["br-1-1a-1ss-b-gldr-inf-bttn", {"b": "BR-1-1A-1SS-B-Gldr-Inf-Bttn-r.png", "f": "BR-1-1A-1SS-B-Gldr-Inf-Bttn-f.png"}],
        ["br-1-1a-7kosb-a-gldr-inf-bttn", {"b": "BR-1-1A-7KOSB-A-Gldr-Inf-Bttn-r.png", "f": "BR-1-1A-7KOSB-A-Gldr-Inf-Bttn-f.png"}],
        ["br-1-1a-7kosb-b-gldr-inf-bttn", {"b": "BR-1-1A-7KOSB-B-Gldr-Inf-Bttn-r.png", "f": "BR-1-1A-7KOSB-B-Gldr-Inf-Bttn-f.png"}],
        ["br-1-1p-1-para-inf-bttn", {"b": "BR-1-1P-1-Para-Inf-Bttn-r.png", "f": "BR-1-1P-1-Para-Inf-Bttn-f.png"}],
        ["br-1-1p-2-para-inf-bttn", {"b": "BR-1-1P-2-Para-Inf-Bttn-r.png", "f": "BR-1-1P-2-Para-Inf-Bttn-f.png"}],
        ["br-1-1p-3-para-inf-bttn", {"b": "BR-1-1P-3-Para-Inf-Bttn-r.png", "f": "BR-1-1P-3-Para-Inf-Bttn-f.png"}],
        ["br-1-4p-10-para-inf-bttn", {"b": "BR-1-4P-10-Para-Inf-Bttn-r.png", "f": "BR-1-4P-10-Para-Inf-Bttn-f.png"}],
        ["br-1-4p-11-para-inf-bttn", {"b": "BR-1-4P-11-Para-Inf-Bttn-r.png", "f": "BR-1-4P-11-Para-Inf-Bttn-f.png"}],
        ["br-1-4p-156-para-inf-bttn", {"b": "BR-1-4P-156-Para-Inf-Bttn-r.png", "f": "BR-1-4P-156-Para-Inf-Bttn-f.png"}],
        ["br-1-a-para-inf-bd", {"f": "BR-1-A-Para-Inf-BD-f.png"}],
        ["br-1-ab-repl", {"f": "BR-1-AB-REPL-f.png"}],
        ["br-1-b-para-inf-bd", {"f": "BR-1-B-Para-Inf-BD-f.png"}],
        ["br-1-supply-head", {"b": "BR-1-Supply-Head-r.png", "f": "BR-1-Supply-Head-f.png"}],
        ["br-11-1519krh-armd-bttn", {"b": "BR-11-1519KRH-Armd-Bttn-r.png", "f": "BR-11-1519KRH-Armd-Bttn-f.png"}],
        ["br-11-159-1h-mot-inf-bttn", {"b": "BR-11-159-1H-Mot-Inf-Bttn-r.png", "f": "BR-11-159-1H-Mot-Inf-Bttn-f.png"}],
        ["br-11-159-3m-mot-inf-bttn", {"b": "BR-11-159-3M-Mot-Inf-Bttn-r.png", "f": "BR-11-159-3M-Mot-Inf-Bttn-f.png"}],
        ["br-11-159-4ksli-mot-inf-bttn", {"b": "BR-11-159-4KSLI-Mot-Inf-Bttn-r.png", "f": "BR-11-159-4KSLI-Mot-Inf-Bttn-f.png"}],
        ["br-11-29-23h-armd-bttn", {"b": "BR-11-29-23H-Armd-Bttn-r.png", "f": "BR-11-29-23H-Armd-Bttn-f.png"}],
        ["br-11-29-2ffy-armd-bttn", {"b": "BR-11-29-2FFY-Armd-Bttn-r.png", "f": "BR-11-29-2FFY-Armd-Bttn-f.png"}],
        ["br-11-29-3rtr-armd-bttn", {"b": "BR-11-29-3RTR-Armd-Bttn-r.png", "f": "BR-11-29-3RTR-Armd-Bttn-f.png"}],
        ["br-11-29-8rb-mech-bttn", {"b": "BR-11-29-8RB-Mech-Bttn-r.png", "f": "BR-11-29-8RB-Mech-Bttn-f.png"}],
        ["br-11armdiv-arty-bde", {"b": "BR-11ArmDiv-Arty-Bde-r.png", "f": "BR-11ArmDiv-Arty-Bde-f.png"}],
        ["br-15-44-6kosb-mot-inf-bttn", {"b": "BR-15-44-6KOSB-Mot-Inf-Bttn-r.png", "f": "BR-15-44-6KOSB-Mot-Inf-Bttn-f.png"}],
        ["br-15-44-6rsf-mot-inf-bttn", {"b": "BR-15-44-6RSF-Mot-Inf-Bttn-r.png", "f": "BR-15-44-6RSF-Mot-Inf-Bttn-f.png"}],
        ["br-15-46-2gh-mot-inf-bttn", {"b": "BR-15-46-2GH-Mot-Inf-Bttn-r.png", "f": "BR-15-46-2GH-Mot-Inf-Bttn-f.png"}],
        ["br-15-46-7sh-mot-inf-bttn", {"b": "BR-15-46-7SH-Mot-Inf-Bttn-r.png", "f": "BR-15-46-7SH-Mot-Inf-Bttn-f.png"}],
        ["br-15-46-9c-mot-inf-bttn", {"b": "BR-15-46-9C-Mot-Inf-Bttn-r.png", "f": "BR-15-46-9C-Mot-Inf-Bttn-f.png"}],
        ["br-1stab-supplymarker", {"b": "BR-1stAB-SupplyMarker-r.png", "f": "BR-1stAB-SupplyMarker-f.png"}],
        ["br-2hc-recon-bttn", {"b": "BR-2HC-Recon-Bttn-r.png", "f": "BR-2HC-Recon-Bttn-f.png"}],
        ["br-3-9-1kosb-inf-bttn", {"b": "BR-3-9-1KOSB-Inf-Bttn-r.png", "f": "BR-3-9-1KOSB-Inf-Bttn-f.png"}],
        ["br-3-9-2l-inf-bttn", {"b": "BR-3-9-2L-Inf-Bttn-r.png", "f": "BR-3-9-2L-Inf-Bttn-f.png"}],
        ["br-3-9-2rur-inf-bttn", {"b": "BR-3-9-2RUR-Inf-Bttn-r.png", "f": "BR-3-9-2RUR-Inf-Bttn-f.png"}],
        ["br-30corps-bridging-unit", {"f": "BR-30Corps-Bridging-Unit-f.png"}],
        ["br-30corps-eng-bttn", {"b": "BR-30Corps-Eng-Bttn-r.png", "f": "BR-30Corps-Eng-Bttn-f.png"}],
        ["br-3div-257", {"b": "BR-3Div-257-r.png", "f": "BR-3Div-257-f.png"}],
        ["br-43-129-4sli-mot-inf-bttn", {"b": "BR-43-129-4SLI-Mot-Inf-Bttn-r.png", "f": "BR-43-129-4SLI-Mot-Inf-Bttn-f.png"}],
        ["br-43-129-4w-mot-inf-bttn", {"b": "BR-43-129-4W-Mot-Inf-Bttn-r.png", "f": "BR-43-129-4W-Mot-Inf-Bttn-f.png"}],
        ["br-43-129-5w-mot-inf-bttn", {"b": "BR-43-129-5W-Mot-Inf-Bttn-r.png", "f": "BR-43-129-5W-Mot-Inf-Bttn-f.png"}],
        ["br-43-130-4d-mot-inf-bttn", {"b": "BR-43-130-4D-Mot-Inf-Bttn-r.png", "f": "BR-43-130-4D-Mot-Inf-Bttn-f.png"}],
        ["br-43-130-5d-mot-inf-bttn", {"b": "BR-43-130-5D-Mot-Inf-Bttn-r.png", "f": "BR-43-130-5D-Mot-Inf-Bttn-f.png"}],
        ["br-43-130-7h-mot-inf-bttn", {"b": "BR-43-130-7H-Mot-Inf-Bttn-r.png", "f": "BR-43-130-7H-Mot-Inf-Bttn-f.png"}],
        ["br-43-214-1w-mot-inf-bttn", {"b": "BR-43-214-1W-Mot-Inf-Bttn-r.png", "f": "BR-43-214-1W-Mot-Inf-Bttn-f.png"}],
        ["br-43-214-5dcli-mot-inf-bttn", {"b": "BR-43-214-5DCLI-Mot-Inf-Bttn-r.png", "f": "BR-43-214-5DCLI-Mot-Inf-Bttn-f.png"}],
        ["br-43-214-7sli-mot-inf-bttn", {"b": "BR-43-214-7SLI-Mot-Inf-Bttn-r.png", "f": "BR-43-214-7SLI-Mot-Inf-Bttn-f.png"}],
        ["br-43-43-recon-bttn", {"b": "BR-43-43-Recon-Bttn-r.png", "f": "BR-43-43-Recon-Bttn-f.png"}],
        ["br-43div-arty-bde", {"b": "BR-43Div-Arty-Bde-r.png", "f": "BR-43Div-Arty-Bde-f.png"}],
        ["br-43div-eng-bttn", {"b": "BR-43Div-Eng-Bttn-r.png", "f": "BR-43Div-Eng-Bttn-f.png"}],
        ["br-44rtr-armd-bttn", {"b": "BR-44RTR-Armd-Bttn-r.png", "f": "BR-44RTR-Armd-Bttn-f.png"}],
        ["br-50-151-6dli-inf-bttn", {"b": "BR-50-151-6DLI-Inf-Bttn-r.png", "f": "BR-50-151-6DLI-Inf-Bttn-f.png"}],
        ["br-50-151-8dli-inf-bttn", {"b": "BR-50-151-8DLI-Inf-Bttn-r.png", "f": "BR-50-151-8DLI-Inf-Bttn-f.png"}],
        ["br-50-151-9dli-inf-bttn", {"b": "BR-50-151-9DLI-Inf-Bttn-r.png", "f": "BR-50-151-9DLI-Inf-Bttn-f.png"}],
        ["br-50-231-1d-inf-bttn", {"b": "BR-50-231-1D-Inf-Bttn-r.png", "f": "BR-50-231-1D-Inf-Bttn-f.png"}],
        ["br-50-231-1h-inf-bttn", {"b": "BR-50-231-1H-Inf-Bttn-r.png", "f": "BR-50-231-1H-Inf-Bttn-f.png"}],
        ["br-50-231-2d-inf-bttn", {"b": "BR-50-231-2D-Inf-Bttn-r.png", "f": "BR-50-231-2D-Inf-Bttn-f.png"}],
        ["br-50-69-5ey-inf-bttn", {"b": "BR-50-69-5EY-Inf-Bttn-r.png", "f": "BR-50-69-5EY-Inf-Bttn-f.png"}],
        ["br-50-69-6gh-inf-bttn", {"b": "BR-50-69-6GH-Inf-Bttn-r.png", "f": "BR-50-69-6GH-Inf-Bttn-f.png"}],
        ["br-50-69-7gh-inf-bttn", {"b": "BR-50-69-7GH-Inf-Bttn-r.png", "f": "BR-50-69-7GH-Inf-Bttn-f.png"}],
        ["br-50div-arty-bde", {"b": "BR-50Div-Arty-Bde-r.png", "f": "BR-50Div-Arty-Bde-f.png"}],
        ["br-5agra-arty-bde", {"b": "BR-5AGRA-Arty-Bde-r.png", "f": "BR-5AGRA-Arty-Bde-f.png"}],
        ["br-8-12krrc-mot-inf-bttn", {"b": "BR-8-12KRRC-Mot-Inf-Bttn-r.png", "f": "BR-8-12KRRC-Mot-Inf-Bttn-f.png"}],
        ["br-8-1318rh-armd-bttn", {"b": "BR-8-1318RH-Armd-Bttn-r.png", "f": "BR-8-1318RH-Armd-Bttn-f.png"}],
        ["br-8-47rdg-armd-bttn", {"b": "BR-8-47RDG-Armd-Bttn-r.png", "f": "BR-8-47RDG-Armd-Bttn-f.png"}],
        ["br-8-sry-armd-bttn", {"b": "BR-8-SRY-Armd-Bttn-r.png", "f": "BR-8-SRY-Armd-Bttn-f.png"}],
        ["br-8corps-bridging-unit", {"f": "BR-8Corps-Bridging-Unit-f.png"}],
        ["br-a-armd-bd", {"f": "BR-A-Armd-BD-f.png"}],
        ["br-a-inf-bd", {"b": "BR-A-Inf-BD-r.png", "f": "BR-A-Inf-BD-f.png"}],
        ["br-airsupport-marker-1", {"b": "BR-AirSupport-Marker-1-r.png", "f": "BR-AirSupport-Marker-1-f.png"}],
        ["br-airsupport-marker-2", {"b": "BR-AirSupport-Marker-2-r.png", "f": "BR-AirSupport-Marker-2-f.png"}],
        ["br-b-armd-bd", {"f": "BR-B-Armd-BD-f.png"}],
        ["br-b-inf-bd", {"b": "BR-B-Inf-BD-r.png", "f": "BR-B-Inf-BD-f.png"}],
        ["br-c-armd-bd", {"f": "BR-C-Armd-BD-f.png"}],
        ["br-c-inf-bd", {"b": "BR-C-Inf-BD-r.png", "f": "BR-C-Inf-BD-f.png"}],
        ["br-gds-2wg-armd-bttn", {"b": "BR-Gds-2WG-Armd-Bttn-r.png", "f": "BR-Gds-2WG-Armd-Bttn-f.png"}],
        ["br-gds-32-1wg-mot-inf-bttn", {"b": "BR-Gds-32-1WG-Mot-Inf-Bttn-r.png", "f": "BR-Gds-32-1WG-Mot-Inf-Bttn-f.png"}],
        ["br-gds-32-3ig-mot-inf-bttn", {"b": "BR-Gds-32-3IG-Mot-Inf-Bttn-r.png", "f": "BR-Gds-32-3IG-Mot-Inf-Bttn-f.png"}],
        ["br-gds-32-5cg-mot-inf-bttn", {"b": "BR-Gds-32-5CG-Mot-Inf-Bttn-r.png", "f": "BR-Gds-32-5CG-Mot-Inf-Bttn-f.png"}],
        ["br-gds-5-1cg-armd-bttn", {"b": "BR-Gds-5-1CG-Armd-Bttn-r.png", "f": "BR-Gds-5-1CG-Armd-Bttn-f.png"}],
        ["br-gds-5-1gg-mech-bttn", {"b": "BR-Gds-5-1GG-Mech-Bttn-r.png", "f": "BR-Gds-5-1GG-Mech-Bttn-f.png"}],
        ["br-gds-5-2gg-armd-bttn", {"b": "BR-Gds-5-2GG-Armd-Bttn-r.png", "f": "BR-Gds-5-2GG-Armd-Bttn-f.png"}],
        ["br-gds-5-2ig-armd-bttn", {"b": "BR-Gds-5-2IG-Armd-Bttn-r.png", "f": "BR-Gds-5-2IG-Armd-Bttn-f.png"}],
        ["br-gdsdiv-arty-bde", {"b": "BR-GdsDiv-Arty-Bde-r.png", "f": "BR-GdsDiv-Arty-Bde-f.png"}],
        ["br-moved-marker-1", {"f": "BR-Moved-Marker-1-f.png"}],
        ["br-moved-marker-2", {"f": "BR-Moved-Marker-2-f.png"}],
        ["br-moved-marker-3", {"f": "BR-Moved-Marker-3-f.png"}],
        ["br-rem-1-para-inf-a", {"f": "BR-REM-1-Para-Inf-A-f.png"}],
        ["br-rem-1-para-inf-b", {"f": "BR-REM-1-Para-Inf-B-f.png"}],
        ["br-rem-1-para-inf-c", {"f": "BR-REM-1-Para-Inf-C-f.png"}],
        ["br-rem-1-para-inf-d", {"f": "BR-REM-1-Para-Inf-D-f.png"}],
        ["br-rem-armd-a", {"f": "BR-REM-Armd-A-f.png"}],
        ["br-rem-armd-b", {"f": "BR-REM-Armd-B-f.png"}],
        ["br-rem-armd-c", {"f": "BR-REM-Armd-C-f.png"}],
        ["br-rem-armd-d", {"f": "BR-REM-Armd-D-f.png"}],
        ["br-rem-armd-e", {"f": "BR-REM-Armd-E-f.png"}],
        ["br-rem-mot-inf-a", {"b": "BR-REM-Mot-Inf-A-r.png", "f": "BR-REM-Mot-Inf-A-f.png"}],
        ["br-rem-mot-inf-b", {"b": "BR-REM-Mot-Inf-B-r.png", "f": "BR-REM-Mot-Inf-B-f.png"}],
        ["br-rem-mot-inf-c", {"b": "BR-REM-Mot-Inf-C-r.png", "f": "BR-REM-Mot-Inf-C-f.png"}],
        ["br-rem-mot-inf-d", {"b": "BR-REM-Mot-Inf-D-r.png", "f": "BR-REM-Mot-Inf-D-f.png"}],
        ["ca-2023rce-eng-bttn", {"b": "CA-2023RCE-Eng-Bttn-r.png", "f": "CA-2023RCE-Eng-Bttn-f.png"}],
    ],
    [
        "Germans (SS)",
        ["ge-10ss-10-2-pz-coy", {"f": "GE-10ss-10-2-Pz-Coy-f.png"}],
        ["ge-10ss-10-arty-regt", {"b": "GE-10ss-10-Arty-Regt-r.png", "f": "GE-10ss-10-Arty-Regt-f.png"}],
        ["ge-10ss-22-i-mot-inf-bttn", {"b": "GE-10ss-22-I-Mot-Inf-Bttn-r.png", "f": "GE-10ss-22-I-Mot-Inf-Bttn-f.png"}],
        ["ge-10ss-22-ii-mot-inf-bttn", {"b": "GE-10ss-22-II-Mot-Inf-Bttn-r.png", "f": "GE-10ss-22-II-Mot-Inf-Bttn-f.png"}],
        ["ge-10ss-brinkmn-kg", {"b": "GE-10ss-Brinkmn-KG-r.png", "f": "GE-10ss-Brinkmn-KG-f.png"}],
        ["ge-10ss-euling-mot-inf-bttn", {"f": "GE-10ss-Euling-Mot-Inf-Bttn-f.png"}],
        ["ge-10ss-hartung-inf-bttn", {"f": "GE-10ss-Hartung-Inf-Bttn-f.png"}],
        ["ge-10ss-pzjg-pzjg-coy", {"f": "GE-10ss-PzJg-PzJg-Coy-f.png"}],
        ["ge-10ss-reinhold-kg", {"f": "GE-10ss-Reinhold-KG-f.png"}],
        ["ge-10ss-richter-kg", {"b": "GE-10ss-Richter-KG-r.png", "f": "GE-10ss-Richter-KG-f.png"}],
        ["ge-10ss-roestel-pzjg-bttn", {"f": "GE-10ss-Roestel-PzJg-Bttn-f.png"}],
        ["ge-9ss-19-inf-regt", {"f": "GE-9ss-19-Inf-Regt-f.png"}],
        ["ge-9ss-20-inf-regt", {"f": "GE-9ss-20-Inf-Regt-f.png"}],
        ["ge-9ss-9-2-pz-coy", {"f": "GE-9ss-9-2-Pz-Coy-f.png"}],
        ["ge-9ss-9recon-mot-inf-bttn", {"f": "GE-9ss-9Recon-Mot-Inf-Bttn-f.png"}],
        ["ge-9ss-allwoerden-kg", {"b": "GE-9ss-Allwoerden-KG-r.png", "f": "GE-9ss-Allwoerden-KG-f.png"}],
        ["ge-9ss-graebner-recon-coy", {"f": "GE-9ss-Graebner-Recon-Coy-f.png"}],
        ["ge-9ss-harder-kg", {"b": "GE-9ss-Harder-KG-r.png", "f": "GE-9ss-Harder-KG-f.png"}],
        ["ge-9ss-segler-kg", {"b": "GE-9ss-Segler-KG-r.png", "f": "GE-9ss-Segler-KG-f.png"}],
        ["ge-9ss-spindler-kg", {"b": "GE-9ss-Spindler-KG-r.png", "f": "GE-9ss-Spindler-KG-f.png"}],
        ["ge-eberwein-inf-bttn", {"b": "GE-Eberwein-Inf-Bttn-r.png", "f": "GE-Eberwein-Inf-Bttn-f.png"}],
        ["ge-helle-inf-bttn", {"b": "GE-Helle-Inf-Bttn-r.png", "f": "GE-Helle-Inf-Bttn-f.png"}],
        ["ge-krafft-inf-bttn", {"b": "GE-Krafft-Inf-Bttn-r.png", "f": "GE-Krafft-Inf-Bttn-f.png"}],
        ["ge-krause-arty-regt", {"b": "GE-Krause-Arty-Regt-r.png", "f": "GE-Krause-Arty-Regt-f.png"}],
        ["ge-lndstmndl-iii-inf-bttn", {"b": "GE-LndstmNdl-III-Inf-Bttn-r.png", "f": "GE-LndstmNdl-III-Inf-Bttn-f.png"}],
        ["ge-mattusch-inf-bttn", {"b": "GE-Mattusch-Inf-Bttn-r.png", "f": "GE-Mattusch-Inf-Bttn-f.png"}],
        ["ge-oelkers-inf-bttn", {"b": "GE-Oelkers-Inf-Bttn-r.png", "f": "GE-Oelkers-Inf-Bttn-f.png"}],
        ["ge-schulz-inf-bttn", {"b": "GE-Schulz-Inf-Bttn-r.png", "f": "GE-Schulz-Inf-Bttn-f.png"}],
        ["ge-schwappacher-ers-bttn", {"b": "GE-Schwappacher-Ers-Bttn-r.png", "f": "GE-Schwappacher-Ers-Bttn-f.png"}],
    ],
    [
        "Germans (Luftwaffe)",
        ["ge-1-fortress-bttn", {"b": "GE-1-Fortress-Bttn-r.png", "f": "GE-1-Fortress-Bttn-f.png"}],
        ["ge-2-fortress-bttn", {"b": "GE-2-Fortress-Bttn-r.png", "f": "GE-2-Fortress-Bttn-f.png"}],
        ["ge-3-fortress-bttn", {"b": "GE-3-Fortress-Bttn-r.png", "f": "GE-3-Fortress-Bttn-f.png"}],
        ["ge-12stug-pz-bde", {"f": "GE-12StuG-Pz-Bde-f.png"}],
        ["ge-19flak-bttn", {"f": "GE-19Flak-Bttn-f.png"}],
        ["ge-428fla-flak-bttn", {"f": "GE-428Fla-Flak-Bttn-f.png"}],
        ["ge-2-finzel-fj-bttn", {"b": "GE-2-Finzel-FJ-Bttn-r.png", "f": "GE-2-Finzel-FJ-Bttn-f.png"}],
        ["ge-21-i-fj-bttn", {"b": "GE-21-I-FJ-Bttn-r.png", "f": "GE-21-I-FJ-Bttn-f.png"}],
        ["ge-3-becker-fj-kg", {"b": "GE-3-Becker-FJ-KG-r.png", "f": "GE-3-Becker-FJ-KG-f.png"}],
        ["ge-5-herman-fj-kg", {"b": "GE-5-Herman-FJ-KG-r.png", "f": "GE-5-Herman-FJ-KG-f.png"}],
        ["ge-bloch-fj-bttn", {"b": "GE-Bloch-FJ-Bttn-r.png", "f": "GE-Bloch-FJ-Bttn-f.png"}],
        ["ge-budde-fj-kg", {"b": "GE-Budde-FJ-KG-r.png", "f": "GE-Budde-FJ-KG-f.png"}],
        ["ge-erdmann-1-fj-bttn", {"b": "GE-Erdmann-1-FJ-Bttn-r.png", "f": "GE-Erdmann-1-FJ-Bttn-f.png"}],
        ["ge-erdmann-2-fj-bttn", {"b": "GE-Erdmann-2-FJ-Bttn-r.png", "f": "GE-Erdmann-2-FJ-Bttn-f.png"}],
        ["ge-erdmann-3-fj-bttn", {"b": "GE-Erdmann-3-FJ-Bttn-r.png", "f": "GE-Erdmann-3-FJ-Bttn-f.png"}],
        ["ge-erdmann-4-fj-bttn", {"b": "GE-Erdmann-4-FJ-Bttn-r.png", "f": "GE-Erdmann-4-FJ-Bttn-f.png"}],
        ["ge-erdmann-5-fj-bttn", {"b": "GE-Erdmann-5-FJ-Bttn-r.png", "f": "GE-Erdmann-5-FJ-Bttn-f.png"}],
        ["ge-erdmann-6-fj-bttn", {"b": "GE-Erdmann-6-FJ-Bttn-r.png", "f": "GE-Erdmann-6-FJ-Bttn-f.png"}],
        ["ge-ewald-a-fj-bttn", {"b": "GE-Ewald-A-FJ-Bttn-r.png", "f": "GE-Ewald-A-FJ-Bttn-f.png"}],
        ["ge-hoffmann-14-fj-bttn", {"f": "GE-Hoffmann-14-FJ-Bttn-f.png"}],
        ["ge-jungwirth-fj-bttn", {"b": "GE-Jungwirth-FJ-Bttn-r.png", "f": "GE-Jungwirth-FJ-Bttn-f.png"}],
        ["ge-kerutt-fj-bttn", {"b": "GE-Kerutt-FJ-Bttn-r.png", "f": "GE-Kerutt-FJ-Bttn-f.png"}],
        ["ge-rem-fj-a", {"f": "GE-REM-FJ-A-f.png"}],
        ["ge-rem-fj-b", {"f": "GE-REM-FJ-B-f.png"}],
        ["ge-rem-fj-c", {"f": "GE-REM-FJ-C-f.png"}],
        ["ge-stephan-fj-bttn", {"b": "GE-Stephan-FJ-Bttn-r.png", "f": "GE-Stephan-FJ-Bttn-f.png"}],
        ["ge-vdh-i-fj-bttn", {"b": "GE-vdH-I-FJ-Bttn-r.png", "f": "GE-vdH-I-FJ-Bttn-f.png"}],
        ["ge-vdh-iii-fj-bttn", {"b": "GE-vdH-III-FJ-Bttn-r.png", "f": "GE-vdH-III-FJ-Bttn-f.png"}],
        ["ge-vdh-iv-fj-bttn", {"b": "GE-vdH-IV-FJ-Bttn-r.png", "f": "GE-vdH-IV-FJ-Bttn-f.png"}],
        ["ge-6penal-inf-bttn", {"b": "GE-6Penal-Inf-Bttn-r.png", "f": "GE-6Penal-Inf-Bttn-f.png"}],
        ["ge-gothsche-a-inf-bttn", {"b": "GE-Gothsche-A-Inf-Bttn-r.png", "f": "GE-Gothsche-A-Inf-Bttn-f.png"}],
        ["ge-hgtraining-inf-bttn", {"f": "GE-HGTraining-Inf-Bttn-f.png"}],
        ["ge-hg-wos-inf-bttn", {"b": "GE-HG-Wos-Inf-Bttn-r.png", "f": "GE-HG-Wos-Inf-Bttn-f.png"}],
        ["ge-kauer-inf-bttn", {"b": "GE-Kauer-Inf-Bttn-r.png", "f": "GE-Kauer-Inf-Bttn-f.png"}],
        ["ge-ladewig-bttn", {"f": "GE-Ladewig-Bttn-f.png"}],
        ["ge-neuman-bttn", {"f": "GE-Neuman-Bttn-f.png"}],
    ],
    [
        "Germans (Wehrmacht)",
        ["ge-107-2107-12-pz-bttn", {"b": "GE-107-2107-12-Pz-Bttn-r.png", "f": "GE-107-2107-12-Pz-Bttn-f.png"}],
        ["ge-107-2107-34-pz-bttn", {"b": "GE-107-2107-34-Pz-Bttn-r.png", "f": "GE-107-2107-34-Pz-Bttn-f.png"}],
        ["ge-107-2107-a-pzgr-bttn", {"b": "GE-107-2107-A-PzGr-Bttn-r.png", "f": "GE-107-2107-A-PzGr-Bttn-f.png"}],
        ["ge-107-2107-b-pzgr-bttn", {"b": "GE-107-2107-B-PzGr-Bttn-r.png", "f": "GE-107-2107-B-PzGr-Bttn-f.png"}],
        ["ge-1409-fortress-bttn", {"b": "GE-1409-Fortress-Bttn-r.png", "f": "GE-1409-Fortress-Bttn-f.png"}],
        ["ge-180-100-inf-bttn", {"b": "GE-180-100-Inf-Bttn-r.png", "f": "GE-180-100-Inf-Bttn-f.png"}],
        ["ge-180-22-16-inf-bttn", {"b": "GE-180-22-16-Inf-Bttn-r.png", "f": "GE-180-22-16-Inf-Bttn-f.png"}],
        ["ge-180-22-489-inf-bttn", {"b": "GE-180-22-489-Inf-Bttn-r.png", "f": "GE-180-22-489-Inf-Bttn-f.png"}],
        ["ge-180-22-arty-regt", {"b": "GE-180-22-Arty-Regt-r.png", "f": "GE-180-22-Arty-Regt-f.png"}],
        ["ge-180-269-47-inf-bttn", {"b": "GE-180-269-47-Inf-Bttn-r.png", "f": "GE-180-269-47-Inf-Bttn-f.png"}],
        ["ge-180-269-65-inf-bttn", {"b": "GE-180-269-65-Inf-Bttn-r.png", "f": "GE-180-269-65-Inf-Bttn-f.png"}],
        ["ge-180-30-eng-bttn", {"f": "GE-180-30-Eng-Bttn-f.png"}],
        ["ge-184artillery-inf-regt", {"f": "GE-184Artillery-Inf-Regt-f.png"}],
        ["ge-191arko-arty", {"b": "GE-191Arko-Arty-r.png", "f": "GE-191Arko-Arty-f.png"}],
        ["ge-26-i-sec-bttn", {"b": "GE-26-I-Sec-Bttn-r.png", "f": "GE-26-I-Sec-Bttn-f.png"}],
        ["ge-26-ii-sec-bttn", {"b": "GE-26-II-Sec-Bttn-r.png", "f": "GE-26-II-Sec-Bttn-f.png"}],
        ["ge-280stug-pz-bde", {"f": "GE-280StuG-Pz-Bde-f.png"}],
        ["ge-30fortress-mg-bttn", {"b": "GE-30Fortress-MG-Bttn-r.png", "f": "GE-30Fortress-MG-Bttn-f.png"}],
        ["ge-347field-ers-bttn", {"b": "GE-347Field-Ers-Bttn-r.png", "f": "GE-347Field-Ers-Bttn-f.png"}],
        ["ge-37fortress-mg-bttn", {"b": "GE-37Fortress-MG-Bttn-r.png", "f": "GE-37Fortress-MG-Bttn-f.png"}],
        ["ge-3police-i-inf-bttn", {"b": "GE-3Police-I-Inf-Bttn-r.png", "f": "GE-3Police-I-Inf-Bttn-f.png"}],
        ["ge-406-arty-regt", {"b": "GE-406-Arty-Regt-r.png", "f": "GE-406-Arty-Regt-f.png"}],
        ["ge-41fortress-mg-bttn", {"b": "GE-41Fortress-MG-Bttn-r.png", "f": "GE-41Fortress-MG-Bttn-f.png"}],
        ["ge-559pzjg-pz-bttn", {"f": "GE-559PzJg-Pz-Bttn-f.png"}],
        ["ge-59-1034-i-inf-bttn", {"b": "GE-59-1034-I-Inf-Bttn-r.png", "f": "GE-59-1034-I-Inf-Bttn-f.png"}],
        ["ge-59-1034-ii-inf-bttn", {"b": "GE-59-1034-II-Inf-Bttn-r.png", "f": "GE-59-1034-II-Inf-Bttn-f.png"}],
        ["ge-59-1035-i-inf-bttn", {"b": "GE-59-1035-I-Inf-Bttn-r.png", "f": "GE-59-1035-I-Inf-Bttn-f.png"}],
        ["ge-59-1035-ii-inf-bttn", {"b": "GE-59-1035-II-Inf-Bttn-r.png", "f": "GE-59-1035-II-Inf-Bttn-f.png"}],
        ["ge-59-1036-i-inf-bttn", {"b": "GE-59-1036-I-Inf-Bttn-r.png", "f": "GE-59-1036-I-Inf-Bttn-f.png"}],
        ["ge-59-159-arty-bttn", {"b": "GE-59-159-Arty-Bttn-r.png", "f": "GE-59-159-Arty-Bttn-f.png"}],
        ["ge-59-159-eng-bttn", {"f": "GE-59-159-Eng-Bttn-f.png"}],
        ["ge-59-159-field-ers-bttn", {"b": "GE-59-159-Field-Ers-Bttn-r.png", "f": "GE-59-159-Field-Ers-Bttn-f.png"}],
        ["ge-6training-1-a-sec-bttn", {"f": "GE-6Training-1-A-Sec-Bttn-f.png"}],
        ["ge-719-723-i-inf-bttn", {"b": "GE-719-723-I-Inf-Bttn-r.png", "f": "GE-719-723-I-Inf-Bttn-f.png"}],
        ["ge-719-zedlitz-kg", {"b": "GE-719-Zedlitz-KG-r.png", "f": "GE-719-Zedlitz-KG-f.png"}],
        ["ge-719-zuber-kg", {"b": "GE-719-Zuber-KG-r.png", "f": "GE-719-Zuber-KG-f.png"}],
        ["ge-85-dryer-inf-bttn", {"b": "GE-85-Dryer-Inf-Bttn-r.png", "f": "GE-85-Dryer-Inf-Bttn-f.png"}],
        ["ge-85-ohler-inf-bttn", {"b": "GE-85-Ohler-Inf-Bttn-r.png", "f": "GE-85-Ohler-Inf-Bttn-f.png"}],
        ["ge-9lehr-eng-bttn", {"f": "GE-9Lehr-Eng-Bttn-f.png"}],
        ["ge-a-inf-bd", {"b": "GE-A-Inf-BD-r.png", "f": "GE-A-Inf-BD-f.png"}],
        ["ge-b-inf-bd", {"b": "GE-B-Inf-BD-r.png", "f": "GE-B-Inf-BD-f.png"}],
        ["ge-bruhns-kg", {"b": "GE-Bruhns-KG-r.png", "f": "GE-Bruhns-KG-f.png"}],
        ["ge-c-inf-bd", {"b": "GE-C-Inf-BD-r.png", "f": "GE-C-Inf-BD-f.png"}],
        ["ge-chill-kg", {"b": "GE-Chill-KG-r.png", "f": "GE-Chill-KG-f.png"}],
        ["ge-ear-ers-bttn", {"b": "GE-Ear-Ers-Bttn-r.png", "f": "GE-Ear-Ers-Bttn-f.png"}],
        ["ge-fuerstenberg-mot-inf-bttn", {"b": "GE-Fuerstenberg-Mot-Inf-Bttn-r.png", "f": "GE-Fuerstenberg-Mot-Inf-Bttn-f.png"}],
        ["ge-goebel-kg", {"b": "GE-Goebel-KG-r.png", "f": "GE-Goebel-KG-f.png"}],
        ["ge-greshick-kg", {"b": "GE-Greshick-KG-r.png", "f": "GE-Greshick-KG-f.png"}],
        ["ge-henke-kg", {"b": "GE-Henke-KG-r.png", "f": "GE-Henke-KG-f.png"}],
        ["ge-isphording-inf-bttn", {"b": "GE-Isphording-Inf-Bttn-r.png", "f": "GE-Isphording-Inf-Bttn-f.png"}],
        ["ge-jenkel-inf-bttn", {"b": "GE-Jenkel-Inf-Bttn-r.png", "f": "GE-Jenkel-Inf-Bttn-f.png"}],
        ["ge-junghans-sec-bttn", {"b": "GE-Junghans-Sec-Bttn-r.png", "f": "GE-Junghans-Sec-Bttn-f.png"}],
        ["ge-kempton-inf-bttn", {"b": "GE-Kempton-Inf-Bttn-r.png", "f": "GE-Kempton-Inf-Bttn-f.png"}],
        ["ge-knaust-kg", {"b": "GE-Knaust-KG-r.png", "f": "GE-Knaust-KG-f.png"}],
        ["ge-lewin-inf-bttn", {"b": "GE-Lewin-Inf-Bttn-r.png", "f": "GE-Lewin-Inf-Bttn-f.png"}],
        ["ge-molzer-eng-bttn", {"b": "GE-Molzer-Eng-Bttn-r.png", "f": "GE-Molzer-Eng-Bttn-f.png"}],
        ["ge-moved-marker-1", {"f": "GE-Moved-Marker-1-f.png"}],
        ["ge-moved-marker-2", {"f": "GE-Moved-Marker-2-f.png"}],
        ["ge-police-sec-bttn", {"f": "GE-Police-Sec-Bttn-f.png"}],
        ["ge-rem-inf-a", {"f": "GE-REM-Inf-A-f.png"}],
        ["ge-rem-inf-b", {"f": "GE-REM-Inf-B-f.png"}],
        ["ge-rem-inf-c", {"f": "GE-REM-Inf-C-f.png"}],
        ["ge-rrsecurity-sec-bttn", {"f": "GE-RRSecurity-Sec-Bttn-f.png"}],
        ["ge-runge-inf-bttn", {"f": "GE-Runge-Inf-Bttn-f.png"}],
        ["ge-schoerken-ers-bttn", {"b": "GE-Schoerken-Ers-Bttn-r.png", "f": "GE-Schoerken-Ers-Bttn-f.png"}],
        ["ge-setup", {"f": "GE-Setup.png"}],
        ["ge-stargaard-inf-bttn", {"b": "GE-Stargaard-Inf-Bttn-r.png", "f": "GE-Stargaard-Inf-Bttn-f.png"}],
    ],
    [
        "Germans (Kriegsmarine)",
        ["ge-10training-sec-bttn", {"b": "GE-10Training-Sec-Bttn-r.png", "f": "GE-10Training-Sec-Bttn-f.png"}],
        ["ge-14training-6-sec-bttn", {"b": "GE-14Training-6-Sec-Bttn-r.png", "f": "GE-14Training-6-Sec-Bttn-f.png"}],
        ["ge-koehnen-kg", {"b": "GE-Koehnen-KG-r.png", "f": "GE-Koehnen-KG-f.png"}],
    ],
    [
        "Germans (?)",
        ["ge-107-eng-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-107-Eng-Coy-f.png"}],
        ["ge-18flak-1-flak-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-18Flak-1-Flak-Coy-f.png"}],
        ["ge-18flak-koeppel-flak-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-18Flak-Koeppel-Flak-Coy-f.png"}],
        ["ge-1pchtearmy-mot-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-1PchteArmy-Mot-Inf-Coy-f.png"}],
        ["ge-224-pz-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-224-Pz-Coy-f.png"}],
        ["ge-506hv-3-pz-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-506Hv-3-Pz-Coy-f.png"}],
        ["ge-559stug-pz-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-559StuG-Pz-Coy-f.png"}],
        ["ge-572flak-4-flak-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-572Flak-4-Flak-Coy-f.png"}],
        ["ge-6training-1-b-sec-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-6Training-1-B-Sec-Coy-f.png"}],
        ["ge-alarm-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Alarm-Inf-Coy-f.png"}],
        ["ge-ewald-b-fj-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Ewald-B-FJ-Coy-f.png"}],
        ["ge-garrison-1-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Garrison-1-Inf-Coy-f.png"}],
        ["ge-garrison-2-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Garrison-2-Inf-Coy-f.png"}],
        ["ge-garrison-3-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Garrison-3-Inf-Coy-f.png"}],
        ["ge-garrison-4-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Garrison-4-Inf-Coy-f.png"}],
        ["ge-garrison-5-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Garrison-5-Inf-Coy-f.png"}],
        ["ge-garrison-6-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Garrison-6-Inf-Coy-f.png"}],
        ["ge-gothsche-b-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Gothsche-B-Inf-Coy-f.png"}],
        ["ge-hummel-pz-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Hummel-Pz-Coy-f.png"}],
        ["ge-lwpersonnel-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-LWPersonnel-Inf-Coy-f.png"}],
        ["ge-lxxxviiicorps-mot-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-LXXXVIIICorps-Mot-Inf-Coy-f.png"}],
        ["ge-mielke-pz-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-Mielke-Pz-Coy-f.png"}],
        ["ge-tielgarrison-inf-coy", {"b": "GE-Garrison-1-Inf-Coy-r.png", "f": "GE-TielGarrison-Inf-Coy-f.png"}]
    ],
    [
        "Dutch / Polish",
        ["nl-princessirene-mot-inf-bde", {"b": "NL-PrincessIrene-Mot-Inf-Bde-r.png", "f": "NL-PrincessIrene-Mot-Inf-Bde-f.png"}],
        ["nl-princessirene-recon-coy", {"f": "NL-PrincessIrene-Recon-Coy-f.png"}],
        ["po-1pol-1-para-inf-bttn", {"b": "PO-1Pol-1-Para-Inf-Bttn-r.png", "f": "PO-1Pol-1-Para-Inf-Bttn-f.png"}],
        ["po-1pol-2-para-inf-bttn", {"b": "PO-1Pol-2-Para-Inf-Bttn-r.png", "f": "PO-1Pol-2-Para-Inf-Bttn-f.png"}],
        ["po-1pol-3-para-inf-bttn", {"b": "PO-1Pol-3-Para-Inf-Bttn-r.png", "f": "PO-1Pol-3-Para-Inf-Bttn-f.png"}],
        ["po-1pol-a-para-inf-bd", {"f": "PO-1Pol-A-Para-Inf-BD-f.png"}],
        ["po-ab-repl-", {"f": "PO-AB-REPL--f.png"}],
        ["po-rem-para-inf-a", {"f": "PO-REM-Para-Inf-A-f.png"}],
        ["po-rem-para-inf-b", {"f": "PO-REM-Para-Inf-B-f.png"}],
    ],
    [
        "USA",
        ["us-101-327-1-a-gldr-inf-bttn", {"b": "US-101-327-1-A-Gldr-Inf-Bttn-r.png", "f": "US-101-327-1-A-Gldr-Inf-Bttn-f.png"}],
        ["us-101-327-1-b-gldr-inf-bttn", {"b": "US-101-327-1-B-Gldr-Inf-Bttn-r.png", "f": "US-101-327-1-B-Gldr-Inf-Bttn-f.png"}],
        ["us-101-327-2-a-gldr-inf-bttn", {"b": "US-101-327-2-A-Gldr-Inf-Bttn-r.png", "f": "US-101-327-2-A-Gldr-Inf-Bttn-f.png"}],
        ["us-101-327-2-b-gldr-inf-bttn", {"b": "US-101-327-2-B-Gldr-Inf-Bttn-r.png", "f": "US-101-327-2-B-Gldr-Inf-Bttn-f.png"}],
        ["us-101-401-1-a-gldr-inf-bttn", {"b": "US-101-401-1-A-Gldr-Inf-Bttn-r.png", "f": "US-101-401-1-A-Gldr-Inf-Bttn-f.png"}],
        ["us-101-401-1-b-gldr-inf-bttn", {"b": "US-101-401-1-B-Gldr-Inf-Bttn-r.png", "f": "US-101-401-1-B-Gldr-Inf-Bttn-f.png"}],
        ["us-101-501-1-para-inf-bttn", {"b": "US-101-501-1-Para-Inf-Bttn-r.png", "f": "US-101-501-1-Para-Inf-Bttn-f.png"}],
        ["us-101-501-2-para-inf-bttn", {"b": "US-101-501-2-Para-Inf-Bttn-r.png", "f": "US-101-501-2-Para-Inf-Bttn-f.png"}],
        ["us-101-501-3-para-inf-bttn", {"b": "US-101-501-3-Para-Inf-Bttn-r.png", "f": "US-101-501-3-Para-Inf-Bttn-f.png"}],
        ["us-101-502-1-para-inf-bttn", {"b": "US-101-502-1-Para-Inf-Bttn-r.png", "f": "US-101-502-1-Para-Inf-Bttn-f.png"}],
        ["us-101-502-2-para-inf-bttn", {"b": "US-101-502-2-Para-Inf-Bttn-r.png", "f": "US-101-502-2-Para-Inf-Bttn-f.png"}],
        ["us-101-502-3-para-inf-bttn", {"b": "US-101-502-3-Para-Inf-Bttn-r.png", "f": "US-101-502-3-Para-Inf-Bttn-f.png"}],
        ["us-101-506-1-para-inf-bttn", {"b": "US-101-506-1-Para-Inf-Bttn-r.png", "f": "US-101-506-1-Para-Inf-Bttn-f.png"}],
        ["us-101-506-2-para-inf-bttn", {"b": "US-101-506-2-Para-Inf-Bttn-r.png", "f": "US-101-506-2-Para-Inf-Bttn-f.png"}],
        ["us-101-506-3-para-inf-bttn", {"b": "US-101-506-3-Para-Inf-Bttn-r.png", "f": "US-101-506-3-Para-Inf-Bttn-f.png"}],
        ["us-101-a-para-inf-bd", {"f": "US-101-A-Para-Inf-BD-f.png"}],
        ["us-101-ab-repl", {"f": "US-101-AB-REPL-f.png"}],
        ["us-101-b-para-inf-bd", {"f": "US-101-B-Para-Inf-BD-f.png"}],
        ["us-101-supply-head", {"b": "US-101-Supply-Head-r.png", "f": "US-101-Supply-Head-f.png"}],
        ["us-101div-arty-regt", {"b": "US-101Div-Arty-Regt-r.png", "f": "US-101Div-Arty-Regt-f.png"}],
        ["us-82-325-1-a-gldr-inf-bttn", {"b": "US-82-325-1-A-Gldr-Inf-Bttn-r.png", "f": "US-82-325-1-A-Gldr-Inf-Bttn-f.png"}],
        ["us-82-325-1-b-gldr-inf-bttn", {"b": "US-82-325-1-B-Gldr-Inf-Bttn-r.png", "f": "US-82-325-1-B-Gldr-Inf-Bttn-f.png"}],
        ["us-82-325-2-a-gldr-inf-bttn", {"b": "US-82-325-2-A-Gldr-Inf-Bttn-r.png", "f": "US-82-325-2-A-Gldr-Inf-Bttn-f.png"}],
        ["us-82-325-2-b-gldr-inf-bttn", {"b": "US-82-325-2-B-Gldr-Inf-Bttn-r.png", "f": "US-82-325-2-B-Gldr-Inf-Bttn-f.png"}],
        ["us-82-401-2-a-gldr-inf-bttn", {"b": "US-82-401-2-A-Gldr-Inf-Bttn-r.png", "f": "US-82-401-2-A-Gldr-Inf-Bttn-f.png"}],
        ["us-82-401-2-b-gldr-inf-bttn", {"b": "US-82-401-2-B-Gldr-Inf-Bttn-r.png", "f": "US-82-401-2-B-Gldr-Inf-Bttn-f.png"}],
        ["us-82-504-1-para-inf-bttn", {"b": "US-82-504-1-Para-Inf-Bttn-r.png", "f": "US-82-504-1-Para-Inf-Bttn-f.png"}],
        ["us-82-504-2-para-inf-bttn", {"b": "US-82-504-2-Para-Inf-Bttn-r.png", "f": "US-82-504-2-Para-Inf-Bttn-f.png"}],
        ["us-82-504-3-para-inf-bttn", {"b": "US-82-504-3-Para-Inf-Bttn-r.png", "f": "US-82-504-3-Para-Inf-Bttn-f.png"}],
        ["us-82-505-1-para-inf-bttn", {"b": "US-82-505-1-Para-Inf-Bttn-r.png", "f": "US-82-505-1-Para-Inf-Bttn-f.png"}],
        ["us-82-505-2-para-inf-bttn", {"b": "US-82-505-2-Para-Inf-Bttn-r.png", "f": "US-82-505-2-Para-Inf-Bttn-f.png"}],
        ["us-82-505-3-para-inf-bttn", {"b": "US-82-505-3-Para-Inf-Bttn-r.png", "f": "US-82-505-3-Para-Inf-Bttn-f.png"}],
        ["us-82-508-1-para-inf-bttn", {"b": "US-82-508-1-Para-Inf-Bttn-r.png", "f": "US-82-508-1-Para-Inf-Bttn-f.png"}],
        ["us-82-508-2-para-inf-bttn", {"b": "US-82-508-2-Para-Inf-Bttn-r.png", "f": "US-82-508-2-Para-Inf-Bttn-f.png"}],
        ["us-82-508-3-para-inf-bttn", {"b": "US-82-508-3-Para-Inf-Bttn-r.png", "f": "US-82-508-3-Para-Inf-Bttn-f.png"}],
        ["us-82-a-para-inf-bd", {"f": "US-82-A-Para-Inf-BD-f.png"}],
        ["us-82-ab-repl", {"f": "US-82-AB-REPL-f.png"}],
        ["us-82-b-para-inf-bd", {"f": "US-82-B-Para-Inf-BD-f.png"}],
        ["us-82-supply-head", {"b": "US-82-Supply-Head-r.png", "f": "US-82-Supply-Head-f.png"}],
        ["us-82div-arty-regt", {"b": "US-82Div-Arty-Regt-r.png", "f": "US-82Div-Arty-Regt-f.png"}],
        ["us-82ndab-supplymarker", {"f": "US-82ndAB-SupplyMarker-f.png"}],
        ["us-rem-101-para-inf-a", {"f": "US-REM-101-Para-Inf-A-f.png"}],
        ["us-rem-101-para-inf-b", {"f": "US-REM-101-Para-Inf-B-f.png"}],
        ["us-rem-101-para-inf-c", {"f": "US-REM-101-Para-Inf-C-f.png"}],
        ["us-rem-82-para-inf-a", {"f": "US-REM-82-Para-Inf-A-f.png"}],
        ["us-rem-82-para-inf-b", {"f": "US-REM-82-Para-Inf-B-f.png"}],
        ["us-rem-82-para-inf-c", {"f": "US-REM-82-Para-Inf-C-f.png"}],
        ["us-setup-marker1", {"f": "US-Setup-Marker1.png"}],
        ["us-setup-marker2", {"f": "US-Setup-Marker2.png"}],
        ["us-setup-marker3", {"f": "US-Setup-Marker3.png"}]
    ],
    [
        "Markers",
        ["ge-phase-marker", {"b": "GE-Phase-Marker-r.png", "f": "GE-Phase-Marker-f.png"}],
        ["ge-weather-am-marker", {"f": "GE-Weather-AM-Marker-f.png"}],
        ["ge-weather-pm-marker", {"f": "GE-Weather-PM-Marker-f.png"}],
        ["ge-gameturn-marker", {"b": "GE-GameTurn-Marker-r.png", "f": "GE-GameTurn-Marker-f.png"}],
        ["x-autods-marker-1", {"b": "X-AutoDS-Marker-1-r.png", "f": "X-AutoDS-Marker-1-f.png"}],
        ["x-bridgeblown-marker-1", {"b": "X-BridgeBlown-Marker-1-r.png", "f": "X-BridgeBlown-Marker-1-f.png"}],
        ["x-bridgeintact-marker-1", {"b": "X-BridgeIntact-Marker-1-r.png", "f": "X-BridgeIntact-Marker-1-f.png"}],
        ["x-dismounted-marker-1", {"b": "X-Dismounted-Marker-1-r.png", "f": "X-Dismounted-Marker-1-f.png"}],
        ["x-disrupted-marker-1", {"b": "X-Disrupted-Marker-1-r.png", "f": "X-Disrupted-Marker-1-f.png"}],
        ["x-engaged-marker-1", {"b": "X-Engaged-Marker-1-r.png", "f": "X-Engaged-Marker-1-f.png"}],
        ["x-outofsupply-marker-1", {"b": "X-OutOfSupply-Marker-1-r.png", "f": "X-OutOfSupply-Marker-1-f.png"}],
        ["x-repl-marker-1", {"f": "X-Repl-Marker-1-f.png"}],
        ["x-scattered-marker-1", {"b": "X-Scattered-Marker-1-r.png", "f": "X-Scattered-Marker-1-f.png"}],
        ["x-traffic-marker-1", {"b": "X-Traffic-Marker-1-r.png", "f": "X-Traffic-Marker-1-f.png"}],
        ["x-traffic-marker-2", {"b": "X-Traffic-Marker-2-r.png", "f": "X-Traffic-Marker-2-f.png"}],
        ["x-traffic-marker-3", {"b": "X-Traffic-Marker-3-r.png", "f": "X-Traffic-Marker-3-f.png"}],
        ["x-traffic-marker-4", {"b": "X-Traffic-Marker-4-r.png", "f": "X-Traffic-Marker-4-f.png"}],
        ["x-traffic-marker-5", {"b": "X-Traffic-Marker-5-r.png", "f": "X-Traffic-Marker-5-f.png"}],
        ["x-traffic-marker-6", {"b": "X-Traffic-Marker-6-r.png", "f": "X-Traffic-Marker-6-f.png"}],
    ]
];