var component_list = [
    'aamgdis.gif',
    'aamgmalf.gif',
    'acq-1-Al.gif',
    'acq-1-Am.gif',
    'acq-1-Br.gif',
    'acq-1-Fr.gif',
    'acq-1-Ja.gif',
    'acq-1-Ru.gif',
    'acq-2-Al.gif',
    'acq-2-Am.gif',
    'acq-2-Br.gif',
    'acq-2-Fr.gif',
    'acq-2-Ja.gif',
    'acq-2-Ru.gif',
    'acq1.gif',
    'acq2.gif',
    'acqB1.gif',
    'acqB2.gif',
    'am-105mm-1.gif',
    'am-105mmB.gif',
    'am-57mm-1.gif',
    'am-76mm-1.gif',
    'am-ATB.gif',
    'am-ATG-57mm-1.gif',
    'am-ATG-57mm-Broken.gif',
    'am-Blank lg.gif',
    'am-blank-sm.gif',
    'am-Conceal-lg.gif',
    'am-conceal.gif',
    'am-gia-v-CE-Stun.gif',
    'am-gia-v-CE.gif',
    'am-gia-v-jeep-wreck.gif',
    'am-HOW-105mm-1.gif',
    'am-HOW-105mmB.gif',
    'am-M10 W-1.gif',
    'am-M16 W-1.gif',
    'am-M3-A W-1.gif',
    'am-M3-B W-1.gif',
    'am-M4A4 W-1.gif',
    'am-M4M52 W-1.gif',
    'am-MMC 246.gif',
    'am-MMC 666.gif',
    'am-MMC 847.gif',
    'am-MMC B6.gif',
    'am-MMC B7.gif',
    'am-mmc-cod-C-246-SL-Berserk.gif',
    'am-mmc-cod-S-666-SL-Berserk.gif',
    'am-mmc-cod-S-847-SL-Berserk.gif',
    'am-Priest W-1.gif',
    'am-SMC 10-2-Bzk-w.gif',
    'am-SMC 10-2-Bzk.gif',
    'am-SMC 10-2w.gif',
    'am-SMC 10-3-Bzk-w.gif',
    'am-SMC 10-3-Bzk.gif',
    'am-SMC 10-3w.gif',
    'am-SMC 6+1-Bzk-w.gif',
    'am-SMC 6+1-Bzk.gif',
    'am-SMC 6+1.gif',
    'am-SMC 6+1w.gif',
    'am-SMC 6-0-Bzk-w.gif',
    'am-SMC 6-0w.gif',
    'am-SMC 7-0-Bzk-w.gif',
    'am-SMC 7-0-Bzk.gif',
    'am-SMC 7-0.gif',
    'am-SMC 7-0w.gif',
    'am-SMC 8-0-Bzk-w.gif',
    'am-SMC 8-0-Bzk.gif',
    'am-SMC 8-0.gif',
    'am-SMC 8-0w.gif',
    'am-SMC 8-1-Bzk-w.gif',
    'am-SMC 8-1-Bzk.gif',
    'am-SMC 8-1.gif',
    'am-SMC 8-1w.gif',
    'am-SMC 9-1-Bzk-w.gif',
    'am-SMC 9-1-Bzk.gif',
    'am-SMC 9-1.gif',
    'am-SMC 9-1w.gif',
    'am-SMC 9-2-Bzk-w.gif',
    'am-SMC 9-2-Bzk.gif',
    'am-SMC 9-2w.gif',
    'am-SMC B10-w.gif',
    'am-SMC B10.gif',
    'am-SMC B5-w.gif',
    'am-SMC B6-w.gif',
    'am-SMC B6.gif',
    'am-SMC B7-w.gif',
    'am-SMC B7.gif',
    'am-SMC B8-w.gif',
    'am-SMC B8.gif',
    'am-SMC B9-w.gif',
    'am-SMC B9.gif',
    'am-SW-Bazooka.gif',
    'am-SW-BazookaF.gif',
    'am-SW-DC.gif',
    'am-SW-DCF.gif',
    'am-SW-FT.gif',
    'am-SW-FTF.gif',
    'am-SW-MG-H.gif',
    'am-SW-MG-HB.gif',
    'am-SW-MG-M.gif',
    'am-SW-MG-MB.gif',
    'am-SW-Mortar.gif',
    'am-SW-MortarB.gif',
    'am-SW-Radio.gif',
    'am-SW-RadioB.gif',
    'am-Truck W-1.gif',
    'am-v-Jeep-1.gif',
    'am-v-M10-1.gif',
    'am-v-M10-Wreck.gif',
    'am-v-M16-1.gif',
    'am-v-M3 MG-1.gif',
    'am-v-M3-1.gif',
    'am-v-M3-MG-Wreck.gif',
    'am-v-M3-Wreck.gif',
    'am-v-M4A4-1.gif',
    'am-v-M4A4-Wreck.gif',
    'am-v-M4M52-1.gif',
    'am-v-M4M52-Wreck.gif',
    'am-v-Priest-1.gif',
    'am-v-Priest-Wreck.gif',
    'am-v-Truck-1.gif',
    'am-v-Truck-Wreck.gif',
    'amer.gif',
    'an-cod-CE-Text.gif',
    'an-cod-CE.gif',
    'an-cod-conceal-sm.gif',
    'an-cod-mmc-458.gif',
    'an-cod-mmc-broken6.gif',
    'apd.gif',
    'Ar.gif',
    'at1.gif',
    'at2.gif',
    'at3.gif',
    'at4.gif',
    'at5.gif',
    'ax-conceal.gif',
    'ax-neu-conceal-lg.gif',
    'ax-neu-conceal-sm.gif',
    'ber.gif',
    'bmgdis.gif',
    'bmgmalf.gif',
    'bog.gif',
    'br-cod-CE-Stun.gif',
    'br-cod-CE.gif',
    'brit.gif',
    'cmgdis.gif',
    'cmgmalf.gif',
    'Ffe1.gif',
    'Ffe1_b.gif',
    'finn.gif',
    'Ford.gif',
    'Fort1.gif',
    'fr-cod-CE-Text.gif',
    'fr-cod-CE.gif',
    'fr-cod-v-CE.gif',
    'fren.gif',
    'ge-57mm-1.gif',
    'ge-75mm-1.gif',
    'ge-ATB.gif',
    'ge-ATG-50mm-1.gif',
    'ge-ATG-75mm-1.gif',
    'ge-ATG-Broken.gif',
    'ge-blank-lg-ss.gif',
    'ge-Blank-lg.gif',
    'ge-blank-sm-ss.gif',
    'ge-blank-sm.gif',
    'ge-COI-105 Art-1.gif',
    'ge-COI-105 Mtr-1.gif',
    'ge-COI-105-128 Art Brk-1.gif',
    'ge-COI-105L Art-1.gif',
    'ge-COI-120 Mtr-1.gif',
    'ge-COI-128L Art-1.gif',
    'ge-COI-150 Art-1.gif',
    'ge-COI-150 Inf Brk-1.gif',
    'ge-COI-150 Inf-1.gif',
    'ge-COI-150 Rct-1.gif',
    'ge-COI-150-170 Art Brk-1.gif',
    'ge-COI-150L Art-1.gif',
    'ge-COI-170L Art-1.gif',
    'ge-COI-20L AA A-1.gif',
    'ge-COI-20L AA B-1.gif',
    'ge-COI-20L AA Brk-1.gif',
    'ge-COI-20L AA C Brk-1.gif',
    'ge-COI-20L AA C-1.gif',
    'ge-COI-210 Rct-1.gif',
    'ge-COI-28-50 Brk-1.gif',
    'ge-COI-280 Rct A-1.gif',
    'ge-COI-280 Rct B-1.gif',
    'ge-COI-28LL AT-1.gif',
    'ge-COI-37L AA B Brk-1.gif',
    'ge-COI-37L AA B-1.gif',
    'ge-COI-37L AA Brk-1.gif',
    'ge-COI-37L AA-1.gif',
    'ge-COI-37L AT-1.gif',
    'ge-COI-47 AT-1.gif',
    'ge-COI-50L AT-1.gif',
    'ge-COI-75 Art Brk-1.gif',
    'ge-COI-75 Art-1.gif',
    'ge-COI-75 AT Brk-1.gif',
    'ge-COI-75 AT-1.gif',
    'ge-COI-75 Inf A-1.gif',
    'ge-COI-75 Inf B-1.gif',
    'ge-COI-75 Inf Brk-1.gif',
    'ge-COI-75-76 Brk-1.gif',
    'ge-COI-75L AT-1.gif',
    'ge-COI-76L AT-1.gif',
    'ge-COI-81 Mtr Brk1.gif',
    'ge-COI-81 Mtr Brk2.gif',
    'ge-COI-81 Mtr Brk3.gif',
    'ge-COI-81 Mtr Brk4.gif',
    'ge-COI-81 Mtr Brk5.gif',
    'ge-COI-81 Mtr Brk6.gif',
    'ge-COI-81 Mtr-1.gif',
    'ge-COI-88 Limber Brk-1.gif',
    'ge-COI-88 Limber-1.gif',
    'ge-COI-88L AA-1.gif',
    'ge-COI-88LL AA Brk-1.gif',
    'ge-COI-88LL AA-1.gif',
    'ge-COI-88LL AT-1.gif',
    'ge-COI-88LL Brk-1.gif',
    'ge-COI-Brummbar A-1.gif',
    'ge-COI-Brummbar B-1.gif',
    'ge-COI-Brummbar W-1.gif',
    'ge-COI-Elefant A-1.gif',
    'ge-COI-Elefant B-1.gif',
    'ge-COI-Elefant W-1.gif',
    'ge-COI-Elefant W-5a.gif',
    'ge-COI-FPz 38(t) W-1.gif',
    'ge-COI-FPz 38(t)-1.gif',
    'ge-COI-FPz IV.20 W-1.gif',
    'ge-COI-FPz IV.20-1.gif',
    'ge-COI-Hvy Truck W-1.gif',
    'ge-COI-Hvy Truck-1.gif',
    'ge-COI-JgdPz38 FT W-1.gif',
    'ge-COI-JgdPz38 FT-1.gif',
    'ge-COI-JgdPz38 W-1.gif',
    'ge-COI-JgdPz38(t)-1.gif',
    'ge-COI-JgdPz38-1.gif',
    'ge-COI-JgdPz38t FT-1.gif',
    'ge-COI-JgdPz38t-1.gif',
    'ge-COI-JgdPzIVG-1.gif',
    'ge-COI-JgdPzIVG-L W-1.gif',
    'ge-COI-JgdPzIVG-w1.gif',
    'ge-COI-JgdPzIVL70-1.gif',
    'ge-COI-JgdPzIVL70-w1.gif',
    'ge-COI-JgdPzV W-1.gif',
    'ge-COI-JgdPzV-1.gif',
    'ge-COI-JgdPzVI W-1.gif',
    'ge-COI-JgdPzVI-1.gif',
    'ge-COI-Kubelwagen A-1.gif',
    'ge-COI-Kubelwagen B-1.gif',
    'ge-COI-Lkw Truck A-1.gif',
    'ge-COI-Lkw Truck B-1.gif',
    'ge-COI-Lkw Truck W-1.gif',
    'ge-COI-Lt Truck-1.gif',
    'ge-COI-Lt Truck-w1.gif',
    'ge-COI-Mortar Brk.gif',
    'ge-COI-Nashorn-1.gif',
    'ge-COI-Nashorn-w1.gif',
    'ge-COI-Ostwind-1.gif',
    'ge-COI-Ostwind-6a.gif',
    'ge-COI-Ostwind-w1.gif',
    'ge-COI-PSW 222-1.gif',
    'ge-COI-PSW 222-w1.gif',
    'ge-COI-PSW 231 W-1.gif',
    'ge-COI-PSW 231-1.gif',
    'ge-COI-PSW 233-1.gif',
    'ge-COI-PSW 233-w1.gif',
    'ge-COI-PSW 234.1 W-1.gif',
    'ge-COI-PSW 234.1-1.gif',
    'ge-COI-PSW 234.2 W-1.gif',
    'ge-COI-PSW 234.2-1.gif',
    'ge-COI-PSW 234.3 W-1.gif',
    'ge-COI-PSW 234.3-1.gif',
    'ge-COI-PSW 234.4 W-1.gif',
    'ge-COI-PSW 234.4-1.gif',
    'ge-COI-PzA II A-1.gif',
    'ge-COI-PzA II B-1.gif',
    'ge-COI-PzA II W-1.gif',
    'ge-COI-PzA III-IV-1.gif',
    'ge-COI-PzA III-IV-w1.gif',
    'ge-COI-PzA III-IV-w1a.gif',
    'ge-COI-PzA III-IV-w2a.gif',
    'ge-COI-PzA III-IV-w3a.gif',
    'ge-COI-PzA III-IV-w4a.gif',
    'ge-COI-PzA III-IV-w5a.gif',
    'ge-COI-PzA III-IV-w6a.gif',
    'ge-COI-PzALrS-1.gif',
    'ge-COI-PzALrS-w1.gif',
    'ge-COI-PzJag I W-1.gif',
    'ge-COI-PzJag I-1.gif',
    'ge-COI-PzJag IID-1.gif',
    'ge-COI-PzJag IID-w1.gif',
    'ge-COI-PzJag IIM-1.gif',
    'ge-COI-PzJag IIM-w1.gif',
    'ge-COI-PzKw IIID A-1.gif',
    'ge-COI-PzKw IIID B-1.gif',
    'ge-COI-PzKw IIID-E W-1.gif',
    'ge-COI-PzKw IIIE-1.gif',
    'ge-COI-PzKw IIIJ A-1.gif',
    'ge-COI-PzKw IIIJ B-1.gif',
    'ge-COI-PzKw IIIJ-L W-1.gif',
    'ge-COI-PzKw IIIL-1.gif',
    'ge-COI-PzKw IIIM A-1.gif',
    'ge-COI-PzKw IIIM B-1.gif',
    'ge-COI-PzKw IIIM W-1.gif',
    'ge-COI-PzW42-1.gif',
    'ge-COI-PzW42-w1.gif',
    'ge-COI-Rct Brk-1.gif',
    'ge-COI-SdKfz 7t W-1.gif',
    'ge-COI-SdKfz 7t-1.gif',
    'ge-COI-SdKfz11-1.gif',
    'ge-COI-SdKfz11-w1.gif',
    'ge-COI-SdKfz7-1.gif',
    'ge-COI-SdKfz7-w1.gif',
    'ge-COI-sIG 38H-1.gif',
    'ge-COI-sIG 38H-w1.gif',
    'ge-COI-sIG IB-1.gif',
    'ge-COI-sIG IB-w1.gif',
    'ge-COI-sIG II-1.gif',
    'ge-COI-sIG II-w1.gif',
    'ge-COI-SPW250.1 W-1.gif',
    'ge-COI-SPW250.1-1.gif',
    'ge-COI-SPW250.10-1.gif',
    'ge-COI-SPW250.3 W-1.gif',
    'ge-COI-SPW250.3-1.gif',
    'ge-COI-SPW250.7 W-1.gif',
    'ge-COI-SPW250.7-1.gif',
    'ge-COI-SPW250.8 W-1.gif',
    'ge-COI-SPW250.8-1.gif',
    'ge-COI-SPW251.1 W-1.gif',
    'ge-COI-SPW251.1-1.gif',
    'ge-COI-SPW251.10 W-1.gif',
    'ge-COI-SPW251.10-1.gif',
    'ge-COI-SPW251.16 W-1.gif',
    'ge-COI-SPW251.16-1.gif',
    'ge-COI-SPW251.1W W-1.gif',
    'ge-COI-SPW251.1W-1.gif',
    'ge-COI-SPW251.2 W-1.gif',
    'ge-COI-SPW251.2-1.gif',
    'ge-COI-SPW251.22 W-1.gif',
    'ge-COI-SPW251.22-1.gif',
    'ge-COI-SPW251.2a W-1.gif',
    'ge-COI-SPW251.2a-1.gif',
    'ge-COI-SPW251.9 W-1.gif',
    'ge-COI-SPW251.9-1.gif',
    'ge-COI-STG IIIB W-1.gif',
    'ge-COI-STG IIIB-1.gif',
    'ge-COI-STG IIIF A-1.gif',
    'ge-COI-STG IIIF B-1.gif',
    'ge-COI-STG IIIF W-1.gif',
    'ge-COI-STG IIIG A-1.gif',
    'ge-COI-STG IIIG B-1.gif',
    'ge-COI-STG IIIG W-1.gif',
    'ge-COI-STG IIIG-75 W-1.gif',
    'ge-COI-STG IIIG-75-1.gif',
    'ge-COI-Stuka-1.gif',
    'ge-COI-sw-Mtr50.gif',
    'ge-COI-sw-Mtr50B.gif',
    'ge-conceal-lg-ss.gif',
    'ge-conceal-lg.gif',
    'ge-conceal-sm-ss.gif',
    'ge-conceal.gif',
    'ge-concealment-large.gif',
    'ge-GIA-FPz IV.20-1.gif',
    'ge-MMC 247.gif',
    'ge-MMC 467.gif',
    'ge-MMC 838.gif',
    'ge-mmc B5.gif',
    'ge-MMC B7.gif',
    'ge-MMC B8.gif',
    'ge-MMC DYO-b.gif',
    'ge-mmc-436.gif',
    'ge-mmc-468.gif',
    'ge-mmc-548.gif',
    'ge-mmc-b9-ss.gif',
    'ge-mmc-C-248ss-Bzk.gif',
    'ge-mmc-C-248ss.gif',
    'ge-mmc-cod-C-247-Berserk.gif',
    'ge-mmc-cod-C-248-Berserk.gif',
    'ge-mmc-cod-C-248-ss-Berserk.gif',
    'ge-mmc-cod-C-248.gif',
    'ge-mmc-cod-S-(1)08-FJ-Bzk.gif',
    'ge-mmc-cod-S-(1)08-FJ.gif',
    'ge-mmc-cod-S-(1)08-FJxx-Bzk.gif',
    'ge-mmc-cod-S-228-FJ-Bzk.gif',
    'ge-mmc-cod-S-228-FJ.gif',
    'ge-mmc-cod-S-436-Berserk.gif',
    'ge-mmc-cod-S-447-Berserk.gif',
    'ge-mmc-cod-S-447.gif',
    'ge-mmc-cod-S-467-Berserk.gif',
    'ge-mmc-cod-S-468-Berserk.gif',
    'ge-mmc-cod-S-548-Berserk.gif',
    'ge-mmc-cod-S-548-Berserk1.gif',
    'ge-mmc-cod-S-548-FJ-Bzk.gif',
    'ge-mmc-cod-S-548-FJ.gif',
    'ge-mmc-cod-S-548a.gif',
    'ge-mmc-cod-S-658ss.gif',
    'ge-mmc-cod-S-838-Berserk.gif',
    'ge-mmc-cod-S-DYO-Bzk.gif',
    'ge-mmc-cod-S-DYO.gif',
    'ge-mmc-cod-S-DYOss-b9.gif',
    'ge-mmc-cod-S-DYOss-Bzk.gif',
    'ge-mmc-cod-S-DYOss.gif',
    'ge-mmc-S-658ss-Bzk.gif',
    'ge-mmc-SS-248.gif',
    'ge-mmc-SS-248B.gif',
    'ge-mmc-SS-658.gif',
    'ge-mmc-SS-658B.gif',
    'ge-mmc-SS-9B.gif',
    'ge-SdKfz 251-A W-1.gif',
    'ge-SdKfz 251-B W-1.gif',
    'ge-SL-Brummbar W-1.gif',
    'ge-SL-MkIVF1 W-1.gif',
    'ge-SL-MkIVF2 W-1.gif',
    'ge-SL-STGIIIx W-1.gif',
    'ge-SL-Truck W-1.gif',
    'ge-SMC 10-2a-Bzk-w.gif',
    'ge-SMC 10-2a-Bzk.gif',
    'ge-SMC 10-2a.gif',
    'ge-SMC 10-2aw.gif',
    'ge-SMC 10-2b-Bzk-w.gif',
    'ge-SMC 10-2b-Bzk.gif',
    'ge-SMC 10-2b-w.gif',
    'ge-SMC 10-2b.gif',
    'ge-SMC 10-3a-Bzk-w.gif',
    'ge-SMC 10-3a-Bzk.gif',
    'ge-SMC 10-3a.gif',
    'ge-SMC 10-3aw.gif',
    'ge-SMC 10-3b-Bzk-w.gif',
    'ge-SMC 10-3b-Bzk.gif',
    'ge-SMC 10-3b-w.gif',
    'ge-SMC 10-3b.gif',
    'ge-SMC 5+1a-w.gif',
    'ge-SMC 5+1b-w.gif',
    'ge-SMC 6+1.gif',
    'ge-SMC 6+1a-Bzk-w.gif',
    'ge-SMC 6+1a-Bzk.gif',
    'ge-SMC 6+1a-w.gif',
    'ge-SMC 6+1a.gif',
    'ge-SMC 6+1b-Bzk-w.gif',
    'ge-SMC 6+1b-Bzk.gif',
    'ge-SMC 6+1b-w.gif',
    'ge-SMC 6+1b.gif',
    'ge-SMC 6-0-Bzk-w.gif',
    'ge-SMC 6-0w.gif',
    'ge-SMC 7-0-Bzk-w.gif',
    'ge-SMC 7-0-Bzk.gif',
    'ge-SMC 7-0.gif',
    'ge-SMC 7-0w.gif',
    'ge-SMC 8-0-Bzk-w.gif',
    'ge-SMC 8-0-Bzk.gif',
    'ge-SMC 8-0.gif',
    'ge-SMC 8-0w.gif',
    'ge-SMC 8-1-Bzk-w.gif',
    'ge-SMC 8-1-Bzk.gif',
    'ge-SMC 8-1.gif',
    'ge-SMC 8-1b-Bzk-w.gif',
    'ge-SMC 8-1b-w.gif',
    'ge-SMC 8-1w.gif',
    'ge-SMC 9-1-Bzk-w.gif',
    'ge-SMC 9-1-Bzk.gif',
    'ge-SMC 9-1.gif',
    'ge-SMC 9-1b-Bzk-w.gif',
    'ge-SMC 9-1b-w.gif',
    'ge-SMC 9-1w.gif',
    'ge-SMC 9-2a-Bzk-w.gif',
    'ge-SMC 9-2a-Bzk.gif',
    'ge-SMC 9-2a.gif',
    'ge-SMC 9-2aw.gif',
    'ge-SMC 9-2b-Bzk-w.gif',
    'ge-SMC 9-2b-Bzk.gif',
    'ge-SMC 9-2b-w.gif',
    'ge-SMC 9-2b.gif',
    'ge-SMC B10.gif',
    'ge-SMC B10w.gif',
    'ge-SMC B5w.gif',
    'ge-SMC B6.gif',
    'ge-SMC B6w.gif',
    'ge-SMC B7.gif',
    'ge-SMC B7w.gif',
    'ge-SMC B8.gif',
    'ge-SMC B8w.gif',
    'ge-SMC B9.gif',
    'ge-SMC B9w.gif',
    'ge-SMC Blank-Bzk.gif',
    'ge-smc-CE 10-1-Bzk-w.gif',
    'ge-smc-CE 10-1-Bzk.gif',
    'ge-smc-CE 10-2-Bzk-w.gif',
    'ge-smc-CE 10-2-Bzk.gif',
    'ge-smc-CE 10-3-Bzk-w.gif',
    'ge-smc-CE 10-3-Bzk.gif',
    'ge-smc-CE 8-1-Bzk-w.gif',
    'ge-smc-CE 8-1-Bzk.gif',
    'ge-smc-CE 8-1.gif',
    'ge-smc-CE 9-1-Bzk-w.gif',
    'ge-smc-CE 9-1-Bzk.gif',
    'ge-smc-CE 9-1.gif',
    'ge-smc-CE 9-2-Bzk-w.gif',
    'ge-smc-CE 9-2-Bzk.gif',
    'ge-smc-CE Text.gif',
    'ge-smc-Sniper-1-Bzk-w.gif',
    'ge-smc-Sniper-1-Bzk.gif',
    'ge-smc-Sniper-1.gif',
    'ge-smc-SS-10-2a-Bzk-w.gif',
    'ge-smc-SS-10-2a-Bzk.gif',
    'ge-smc-SS-10-2a-w.gif',
    'ge-smc-SS-10-2a.gif',
    'ge-smc-SS-10-2b-Bzk-w.gif',
    'ge-smc-SS-10-2b-Bzk.gif',
    'ge-smc-SS-10-2b-w.gif',
    'ge-smc-SS-10-2b.gif',
    'ge-smc-SS-10-3a-Bzk-w.gif',
    'ge-smc-SS-10-3a-Bzk.gif',
    'ge-smc-SS-10-3a-w.gif',
    'ge-smc-SS-10-3a.gif',
    'ge-smc-SS-10-3b-Bzk-w.gif',
    'ge-smc-SS-10-3b-Bzk.gif',
    'ge-smc-SS-10-3b-w.gif',
    'ge-smc-SS-10-3b.gif',
    'ge-smc-SS-10B.gif',
    'ge-smc-SS-11B.gif',
    'ge-smc-SS-5+1-Bzk-w.gif',
    'ge-smc-SS-5+1-w.gif',
    'ge-smc-SS-5+1a-Bzk-w.gif',
    'ge-smc-SS-5+1a-w.gif',
    'ge-smc-SS-6+1-Bzk-w.gif',
    'ge-smc-SS-6+1-w.gif',
    'ge-smc-SS-6+1.gif',
    'ge-smc-SS-6+1a-Bzk-w.gif',
    'ge-smc-SS-6+1a-Bzk.gif',
    'ge-smc-SS-6+1a-w.gif',
    'ge-smc-SS-6+1a.gif',
    'ge-smc-SS-6+1b-Bzk.gif',
    'ge-smc-SS-6+1B.gif',
    'ge-smc-SS-6-0-Bzk-w.gif',
    'ge-smc-SS-6-0-w.gif',
    'ge-smc-SS-7-0-Bzk-w.gif',
    'ge-smc-SS-7-0-Bzk.gif',
    'ge-smc-SS-7-0-w.gif',
    'ge-smc-SS-7-0.gif',
    'ge-smc-SS-7-0B.gif',
    'ge-smc-SS-7B.gif',
    'ge-smc-SS-8-0-Bzk-w.gif',
    'ge-smc-SS-8-0-Bzk.gif',
    'ge-smc-SS-8-0-w.gif',
    'ge-smc-SS-8-0.gif',
    'ge-smc-SS-8-0b-w.gif',
    'ge-smc-SS-8-0B.gif',
    'ge-smc-SS-8-1-Bzk-w.gif',
    'ge-smc-SS-8-1-Bzk.gif',
    'ge-smc-SS-8-1-w.gif',
    'ge-smc-SS-8-1.gif',
    'ge-smc-SS-8-1a-Bzk-w.gif',
    'ge-smc-SS-8-1a-w.gif',
    'ge-smc-SS-8-1b-w.gif',
    'ge-smc-SS-8-1B.gif',
    'ge-smc-SS-8B.gif',
    'ge-smc-SS-9-1.gif',
    'ge-smc-SS-9-1a-Bzk-w.gif',
    'ge-smc-SS-9-1a-w.gif',
    'ge-smc-SS-9-1b-Bzk-w.gif',
    'ge-smc-SS-9-1b-Bzk.gif',
    'ge-smc-SS-9-1b-w.gif',
    'ge-smc-SS-9-1b.gif',
    'ge-smc-SS-9-2a-Bzk-w.gif',
    'ge-smc-SS-9-2a-Bzk.gif',
    'ge-smc-SS-9-2a-w.gif',
    'ge-smc-SS-9-2a.gif',
    'ge-smc-SS-9-2b-Bzk-w.gif',
    'ge-smc-SS-9-2b-Bzk.gif',
    'ge-smc-SS-9-2b-w.gif',
    'ge-smc-SS-9-2b.gif',
    'ge-smc-SS-9B.gif',
    'ge-smc-SS-B10-w.gif',
    'ge-smc-SS-B10.gif',
    'ge-smc-SS-B11-w.gif',
    'ge-smc-SS-B11.gif',
    'ge-smc-SS-B6-w.gif',
    'ge-smc-SS-B7-w.gif',
    'ge-smc-SS-B7.gif',
    'ge-smc-SS-B8-w.gif',
    'ge-smc-SS-B8.gif',
    'ge-smc-SS-B9-w.gif',
    'ge-smc-SS-B9.gif',
    'ge-smc-SS-CE+2-Bzk-w.gif',
    'ge-smc-SS-CE+2-Bzk.gif',
    'ge-smc-SS-CE+2.gif',
    'ge-smc-SS-Sniper-1-Bzk-w.gif',
    'ge-smc-SS-Sniper-1-Bzk.gif',
    'ge-smc-SS-Sniper-1.gif',
    'ge-smc-SS-Sniper-1w.gif',
    'ge-smc-SS-Sniper-2-Bzk-w.gif',
    'ge-smc-SS-Sniper-2-Bzk.gif',
    'ge-smc-SS-Sniper-2w.gif',
    'ge-smc-SS-Sniper-3-Bzk-w.gif',
    'ge-smc-SS-Sniper-3-Bzk.gif',
    'ge-smc-SS-Sniper-3w.gif',
    'ge-smc-SS-Sniper-4-Bzk-w.gif',
    'ge-smc-SS-Sniper-4-Bzk.gif',
    'ge-smc-SS-Sniper-4w.gif',
    'ge-smc-ss-SniperB.gif',
    'ge-ss-blank-sm.gif',
    'ge-SS-CE 10-1B.gif',
    'ge-SS-CE 10-2B-w.gif',
    'ge-SS-CE 10-2B.gif',
    'ge-SS-CE 10-3B-w.gif',
    'ge-SS-CE 10-3B.gif',
    'ge-SS-CE 8-1.gif',
    'ge-SS-CE 8-1B-w.gif',
    'ge-SS-CE 8-1B.gif',
    'ge-SS-CE 9-1.gif',
    'ge-SS-CE 9-1B-w.gif',
    'ge-SS-CE 9-1B.gif',
    'ge-SS-CE 9-2B-w.gif',
    'ge-SS-CE 9-2B.gif',
    'ge-SS-CE-Text.gif',
    'ge-SS-CE.gif',
    'ge-SS-CEB.gif',
    'ge-SW DC.gif',
    'ge-SW DCF.gif',
    'ge-SW FT.gif',
    'ge-SW FTF.gif',
    'ge-SW Radio.gif',
    'ge-SW RadioB.gif',
    'ge-sw-ATM.gif',
    'ge-sw-ATMB.gif',
    'ge-sw-ATR.gif',
    'ge-sw-ATRB.gif',
    'ge-sw-Baz.gif',
    'ge-sw-BazF.gif',
    'ge-SW-MG-H.gif',
    'ge-SW-MG-HB.gif',
    'ge-SW-MG-L.gif',
    'ge-SW-MG-LB.gif',
    'ge-SW-MG-M.gif',
    'ge-SW-MG-MB.gif',
    'ge-SW-Mortar.gif',
    'ge-SW-MortarB.gif',
    'ge-sw-PZF 42b.gif',
    'ge-sw-PZF 42bF.gif',
    'ge-sw-PZF 43a F.gif',
    'ge-sw-PZF 43a.gif',
    'ge-sw-PZF 43b F.gif',
    'ge-sw-PZF 43b.gif',
    'ge-sw-PZF 44a F.gif',
    'ge-sw-PZF 44a.gif',
    'ge-SW-PzFaust.gif',
    'ge-SW-PzFaustF.gif',
    'ge-v-Brummbar-1.gif',
    'ge-v-Brummbar-Wreck.gif',
    'ge-v-COD-PzKw 35(t)-1.gif',
    'ge-v-COD-PzKw 35-8 W-1.gif',
    'ge-v-COD-PzKw 38(t) S-1.gif',
    'ge-v-COD-PzKw 38(t)-1.gif',
    'ge-v-COD-PzKw 38t-1.gif',
    'ge-v-COD-PzKw IB-1.gif',
    'ge-v-COD-PzKw IB-w1.gif',
    'ge-v-COD-PzKw IIIM FT W-1.gif',
    'ge-v-COD-PzKw IIIM FT W-4a.gif',
    'ge-v-COD-PzKw IIIM-FT-1.gif',
    'ge-v-COD-PzKw IVC-1.gif',
    'ge-v-COD-PzKw IVC-F1-w1.gif',
    'ge-v-COD-PzKw IVD-1.gif',
    'ge-v-COD-PzKw IVE-1.gif',
    'ge-v-COD-PzKw IVF1-1.gif',
    'ge-v-COD-PzKw IVF2 A-1.gif',
    'ge-v-COD-PzKw IVF2B-1.gif',
    'ge-v-COD-PzKw-IV-H-1.gif',
    'ge-v-COD-PzKw-IV-H-w1.gif',
    'ge-v-COD-PzKwII-Lynx-1.gif',
    'ge-v-COD-PzKwII-Lynx-w1.gif',
    'ge-v-COD-PzKwII-Lynx-w3a.gif',
    'ge-v-COD-PzKwIIa-Lynx-1.gif',
    'ge-v-COD-PzKwIIa-Lynx-2a.gif',
    'ge-v-COD-PzKwIID-1.gif',
    'ge-v-COD-PzKwIID-Flamm-1.gif',
    'ge-v-COD-PzKwIID-w1.gif',
    'ge-v-COD-PzKwIIF-1.gif',
    'ge-v-COD-PzKwIIF-w1.gif',
    'ge-v-COD-PzKwVD-1.gif',
    'ge-v-COD-PzKwVD-w1.gif',
    'ge-v-COD-PzKwVG-1.gif',
    'ge-v-COD-PzKwVG-NbW-w1.gif',
    'ge-v-COD-PzKwVGa-1.gif',
    'ge-v-COD-PzKwVI-B-1.gif',
    'ge-v-COD-PzKwVI-B-w1.gif',
    'ge-v-COD-PzKwVI-E-1.gif',
    'ge-v-COD-PzKwVI-E-NbW-w1.gif',
    'ge-v-COD-PzKwVI-E-w1.gif',
    'ge-v-COD-SPW250-9-1.gif',
    'ge-v-COD-SPW250-9-10 W-1.gif',
    'ge-v-MkIVF1-1.gif',
    'ge-v-MkIVF1-Wreck.gif',
    'ge-v-MkIVF2-1.gif',
    'ge-v-MkIVF2-Wreck.gif',
    'ge-v-SdKfz 251 MG-Wreck.gif',
    'ge-v-SdKfz 251-1 MG.gif',
    'ge-v-SdKfz 251-1.gif',
    'ge-v-SdKfz 251-2 MG.gif',
    'ge-v-SdKfz 251-3 MG.gif',
    'ge-v-SdKfz 251-4 MG.gif',
    'ge-v-SdKfz 251-5 MG.gif',
    'ge-v-SdKfz 251-6 MG.gif',
    'ge-v-SdKfz 251-Wreck.gif',
    'ge-v-STG III 105-1.gif',
    'ge-v-STG III-1.gif',
    'ge-v-STGIII 105-Wreck.gif',
    'ge-v-STGIII-Wreck.gif',
    'ge-v-Truck-1.gif',
    'ge-v-Truck-Wreck.gif',
    'germ.gif',
    'if.gif',
    'immob.gif',
    'info-1ToHit Withdraw.gif',
    'info-1ToHit.gif',
    'info-Abandoned.gif',
    'info-AdvF.gif',
    'info-AircraftF.gif',
    'info-AM Artillery Request.gif',
    'info-AM FFE.gif',
    'info-AM SR.gif',
    'info-berserk.gif',
    'info-Blank Lg.gif',
    'info-Blank Sm.gif',
    'info-BOG.gif',
    'info-Bridge2-1.gif',
    'info-Bridge3-1.gif',
    'info-BridgeB-1.gif',
    'info-Building Fire.gif',
    'info-Building FireF.gif',
    'info-Building Rubble.gif',
    'info-Bunker 135-C.gif',
    'info-Bunker 135-L.gif',
    'info-Bunker 135-R.gif',
    'info-Bunker 157-C.gif',
    'info-Bunker 157-L.gif',
    'info-Bunker 157-R.gif',
    'info-Bunker 235-C.gif',
    'info-Bunker 235-L.gif',
    'info-Bunker 235-R.gif',
    'info-Bunker 257-C.gif',
    'info-Bunker 257-L.gif',
    'info-Bunker 257-R.gif',
    'info-Bunker 335-C.gif',
    'info-Bunker 335-L.gif',
    'info-Bunker 335-R.gif',
    'info-Bunker 357-C.gif',
    'info-Bunker 357-L.gif',
    'info-Bunker 357-R.gif',
    'info-CC.gif',
    'info-CE.gif',
    'info-conceal-v-am.gif',
    'info-conceal-v-ge.gif',
    'info-conceal-v-ru.gif',
    'Info-control-Amer.gif',
    'Info-control-Brit1.gif',
    'Info-control-finn.gif',
    'Info-control-Fren1.gif',
    'Info-control-Germ.gif',
    'Info-control-Holl-12.gif',
    'Info-control-Italians.gif',
    'info-control-Norway.gif',
    'info-control-pl-1.gif',
    'Info-control-Pol.gif',
    'Info-control-Russ1.gif',
    'Info-control-Russ2.gif',
    'Info-control-VChex1.gif',
    'info-Crest.gif',
    'info-CX Info.gif',
    'info-CX.gif',
    'info-DefF.gif',
    'info-DM.gif',
    'info-Entrench.gif',
    'info-EntrenchF.gif',
    'info-EscPrisoner.gif',
    'info-Fanatic.gif',
    'info-FFE.gif',
    'info-Fire.gif',
    'info-FireF.gif',
    'info-Ford-1.gif',
    'info-GE Artillery Request.gif',
    'info-GE FFE.gif',
    'info-GE SR.gif',
    'info-Gun Disabled.gif',
    'info-Gun Malfunction.gif',
    'Info-half_turn1.gif',
    'Info-half_turn2.gif',
    'Info-half_turn3.gif',
    'info-HazMvmt.gif',
    'info-HazMvmt2.gif',
    'info-Horse-Saddled.gif',
    'info-Horse.gif',
    'info-immob.gif',
    'info-immobF.gif',
    'info-Immobilized.gif',
    'info-ImmobilizeX.gif',
    'info-Level-Roof.gif',
    'info-Melee.gif',
    'info-MG Disabled.gif',
    'info-MG Malfunction.gif',
    'info-mine00.gif',
    'info-mine01.gif',
    'info-mine02.gif',
    'info-mine04.gif',
    'info-mine06.gif',
    'info-mine08.gif',
    'info-mine12.gif',
    'info-mine16.gif',
    'info-mine20.gif',
    'info-mine24.gif',
    'info-mine30.gif',
    'info-mine36.gif',
    'info-MolCocktail.gif',
    'info-MolCocktailF.gif',
    'info-North-1.gif',
    'info-North-1a.gif',
    'info-North-2b.gif',
    'info-North-3b.gif',
    'info-North-4d.gif',
    'info-Parachute.gif',
    'info-ParachuteF.gif',
    'info-PrepF.gif',
    'Info-Rein-American.gif',
    'Info-Rein-Axis-Minor.gif',
    'Info-Rein-British.gif',
    'Info-Rein-Finnish.gif',
    'Info-Rein-French.gif',
    'Info-Rein-German.gif',
    'Info-Rein-Holland.gif',
    'Info-Rein-Pole.gif',
    'Info-Rein-Russian.gif',
    'info-RU Artillery Request.gif',
    'info-RU FFE.gif',
    'info-RU SR.gif',
    'info-Sewer.gif',
    'info-Smoke-AL.gif',
    'info-Smoke-AM.gif',
    'info-Smoke-GE.gif',
    'info-Smoke-JA.gif',
    'info-Smoke-RU.gif',
    'info-Smoke.gif',
    'info-SS DM.gif',
    'info-Starshell.gif',
    'info-TB-Left.gif',
    'info-TB-Right.gif',
    'info-TI.gif',
    'info-Track-blue.gif',
    'info-Track-brown.gif',
    'info-Track-green.gif',
    'info-Track-red.gif',
    'info-Track-yellow.gif',
    'info-Track.gif',
    'Info-Trench-B.gif',
    'Info-Trench.gif',
    'Info-Turn-Counter-0.gif',
    'Info-Turn-Counter-1.gif',
    'Info-Turn-Counter-10.gif',
    'Info-Turn-Counter-11.gif',
    'Info-Turn-Counter-12.gif',
    'Info-Turn-Counter-13.gif',
    'Info-Turn-Counter-14.gif',
    'Info-Turn-Counter-15.gif',
    'Info-Turn-Counter-16.gif',
    'Info-Turn-Counter-17.gif',
    'Info-Turn-Counter-18.gif',
    'Info-Turn-Counter-19.gif',
    'Info-Turn-Counter-7.gif',
    'Info-Turn-Counter-8.gif',
    'Info-Turn-Counter-9.gif',
    'info-Turn-Marker-Chart-Blank-Turn.gif',
    'Info-Turn-Marker-die1.gif',
    'Info-Turn-Marker-die10.gif',
    'Info-Turn-Marker-die2.gif',
    'Info-Turn-Marker-die3.gif',
    'Info-Turn-Marker-die4.gif',
    'Info-Turn-Marker-die5.gif',
    'Info-Turn-Marker-die6.gif',
    'Info-Turn-Marker-die7.gif',
    'Info-Turn-Marker-die8.gif',
    'Info-Turn-Marker-die9.gif',
    'Info-Turn-Marker-Phase-1-Rph.gif',
    'Info-Turn-Marker-Phase-2-PFph.gif',
    'Info-Turn-Marker-Phase-3-Mph.gif',
    'Info-Turn-Marker-Phase-4-DFph.gif',
    'Info-Turn-Marker-Phase-5-AFph.gif',
    'Info-Turn-Marker-Phase-6-RTph.gif',
    'Info-Turn-Marker-Phase-7-Aph.gif',
    'Info-Turn-Marker-Phase-8-CCph.gif',
    'Info-Wagon-1.gif',
    'info-wire-hexagon.gif',
    'info-wire-hexagon1.gif',
    'info-wire-hexagon2.gif',
    'info-wire-hexagon3.gif',
    'info-wire-hexagon4.gif',
    'info-wire-hexagon5.gif',
    'info-wire.gif',
    'It-cod-v-armor-leader-b.gif',
    'It-cod-v-CE.gif',
    'It-TargetAcq-1.gif',
    'ja-gia-CE.gif',
    'ja-smc-CE-Stun.gif',
    'LabelMe.gif',
    'Lev1.gif',
    'Lev2.gif',
    'Lev3.gif',
    'limbered.gif',
    'lowammo.gif',
    'madis.gif',
    'mamalf.gif',
    'mayrout.gif',
    'neu-Blank.gif',
    'neu-cod-g-Art105-1.gif',
    'neu-cod-g-Art105-128-brk1.gif',
    'neu-cod-g-Art105L-1.gif',
    'neu-cod-g-Art128L-1.gif',
    'neu-cod-g-Art150-1.gif',
    'neu-cod-g-Art150-Brk1.gif',
    'neu-cod-g-Art150-Brk2.gif',
    'neu-cod-g-Art150-Brk3.gif',
    'neu-cod-g-Art150-Brk4.gif',
    'neu-cod-g-Art150-Brk5.gif',
    'neu-cod-g-Art150-Brk6.gif',
    'neu-coi-Blank-DYO-sm.gif',
    'neu-coi-Blank-lg.gif',
    'neu-coi-conceal-lg.gif',
    'neu-coi-conceal-sm.gif',
    'neu-coi-mmc-227.gif',
    'neu-coi-smc-b4w.gif',
    'neu-coi-smc-b5.gif',
    'neu-coi-smc-b5w.gif',
    'neu-coi-smc-b6.gif',
    'neu-coi-smc-b6w.gif',
    'neu-coi-smc-b7.gif',
    'neu-coi-smc-b7w.gif',
    'neu-coi-smc-Sniper-1-Bzk-w.gif',
    'neu-coi-smc-Sniper-1-Bzk.gif',
    'neu-coi-smc-Sniper-1-w.gif',
    'neu-coi-smc-Sniper-2-Bzk-w.gif',
    'neu-coi-smc-Sniper-2-Bzk.gif',
    'neu-coi-smc-Sniper-2-w.gif',
    'neu-Conceal.gif',
    'neu-gia-mmc-137H.gif',
    'neu-gia-mmc-227C.gif',
    'neu-gia-mmc-347S.gif',
    'neu-mmc-227.gif',
    'neu-mmc-347.gif',
    'neu-mmc-6B.gif',
    'neu-mmc-cod-C-227-Berserk.gif',
    'neu-mmc-cod-S-347-Berserk.gif',
    'neu-mmc-coi-DYO-b.gif',
    'neu-mmc-coi-S-DYO-Bzk.gif',
    'neu-mmc-coi-S-DYO.gif',
    'neu-mmc-gia-C-227-Berserk.gif',
    'neu-mmc-gia-S-347(10)-Berserk.gif',
    'neu-smc-5B.gif',
    'neu-smc-6B.gif',
    'neu-smc-7B.gif',
    'neu-smc-coi-5+1-Bzk-w.gif',
    'neu-smc-coi-5+1w.gif',
    'neu-smc-coi-6+1-Bzk-w.gif',
    'neu-smc-coi-6+1-Bzk.gif',
    'neu-smc-coi-6+1.gif',
    'neu-smc-coi-6-0-Bzk-w.gif',
    'neu-smc-coi-6-0-w.gif',
    'neu-smc-coi-7-0-Bzk-w.gif',
    'neu-smc-coi-7-0-Bzk.gif',
    'neu-smc-coi-7-0.gif',
    'neu-smc-coi-7-0w.gif',
    'neu-smc-coi-8-0-Bzk.gif',
    'neu-smc-coi-8-0.gif',
    'neu-smc-coi-8-1-Bzk.gif',
    'neu-smc-coi-8-1.gif',
    'neu-smc-Sniper-1.gif',
    'neu-sw-LMG.gif',
    'neu-sw-LMGB.gif',
    'neu-sw-MMG.gif',
    'neu-sw-MMGB.gif',
    'NoAP.gif',
    'NoAPCR.gif',
    'NoAPDS.gif',
    'NoCannister.gif',
    'nofire.gif',
    'NoHE.gif',
    'NoHEAT.gif',
    'NoSmoke.gif',
    'Pole.gif',
    'qmarkme.gif',
    'Rdblk1.gif',
    'Rdblk2.gif',
    'Rdblk3.gif',
    'Rdblk4.gif',
    'Rdblk5.gif',
    'Rdblk6.gif',
    'recall.gif',
    'ru-57mm-1.gif',
    'ru-76mm-1.gif',
    'ru-ATB.gif',
    'ru-ATG-57mm-1.gif',
    'ru-ATG-76mm-1.gif',
    'ru-ATG-Broken.gif',
    'ru-Blank-lg.gif',
    'ru-blank.gif',
    'ru-CE 10-2B.gif',
    'ru-CE 10-3B.gif',
    'ru-CE 8-1B.gif',
    'ru-CE 9-1B.gif',
    'ru-CE 9-2B.gif',
    'ru-CE-8-1.gif',
    'ru-CE-9-1.gif',
    'ru-CE-B.gif',
    'ru-CE-Stun.gif',
    'ru-CE.gif',
    'ru-CEB.gif',
    'ru-COI-100L AT-1.gif',
    'ru-COI-100L Brk-1.gif',
    'ru-COI-107 Art W-1.gif',
    'ru-COI-107 Art-1.gif',
    'ru-COI-107 Mtr-1.gif',
    'ru-COI-120 Mtr-1.gif',
    'ru-COI-122 Art-1.gif',
    'ru-COI-122L Art-1.gif',
    'ru-COI-122x Art Brk-1.gif',
    'ru-COI-152 Art A-1.gif',
    'ru-COI-152 Art B-1.gif',
    'ru-COI-152 Art Brk-1.gif',
    'ru-COI-160 Mtr-1.gif',
    'ru-COI-25LL AA A-1.gif',
    'ru-COI-25LL AA B-1.gif',
    'ru-COI-25LL AA Brk-1.gif',
    'ru-COI-37 Inf Brk-1.gif',
    'ru-COI-37 Inf-1.gif',
    'ru-COI-37-57 Brk-1.gif',
    'ru-COI-37L AT-1.gif',
    'ru-COI-37LL AA Brk-1.gif',
    'ru-COI-37LL AA-1.gif',
    'ru-COI-45L AT-1.gif',
    'ru-COI-45LL AT-1.gif',
    'ru-COI-57LL AT-1.gif',
    'ru-COI-76 Art A-1.gif',
    'ru-COI-76 Art B-1.gif',
    'ru-COI-76 Inf A-1.gif',
    'ru-COI-76 Inf B-1.gif',
    'ru-COI-76 Inf Brk-1.gif',
    'ru-COI-76-85 AA Brk-1.gif',
    'ru-COI-76-85 Art Brk-1.gif',
    'ru-COI-76L AA-1.gif',
    'ru-COI-76L Art-1.gif',
    'ru-COI-82 Mtr-1.gif',
    'ru-COI-85L AA-1.gif',
    'ru-COI-85L Art-1.gif',
    'ru-COI-BA32 A-1.gif',
    'ru-COI-BA32 B-1.gif',
    'ru-COI-BA32 W-1.gif',
    'ru-COI-BA64 W-1.gif',
    'ru-COI-BA64-1.gif',
    'ru-COI-BT5 W-1.gif',
    'ru-COI-BT5-1.gif',
    'ru-COI-BT5A W-1.gif',
    'ru-COI-BT5A-1.gif',
    'ru-COI-BT7-2 A-1.gif',
    'ru-COI-BT7-2 B-1.gif',
    'ru-COI-BT7-2 B-1a.gif',
    'ru-COI-BT7-2 C-1.gif',
    'ru-COI-BT7-2 D-1.gif',
    'ru-COI-BT7A-1.gif',
    'ru-COI-BT7M W-1.gif',
    'ru-COI-BT7M-1.gif',
    'ru-COI-BT7x W-1.gif',
    'ru-COI-GAZ 67B-1.gif',
    'ru-COI-JAG Hvy Truck W-1.gif',
    'ru-COI-JAG Hvy Truck-1.gif',
    'ru-COI-JSI A-1.gif',
    'ru-COI-JSI B-1.gif',
    'ru-COI-JSII W-1.gif',
    'ru-COI-JSII-1.gif',
    'ru-COI-JSIII-1.gif',
    'ru-COI-JSU122 w-1.gif',
    'ru-COI-JSU122-1.gif',
    'ru-COI-JSU152 W-1.gif',
    'ru-COI-JSU152-1.gif',
    'ru-COI-JSx W-1.gif',
    'ru-COI-KV8 A-1.gif',
    'ru-COI-KV8 B-1.gif',
    'ru-COI-KV8 W-1.gif',
    'ru-COI-KV85 W-1.gif',
    'ru-COI-KV85-1.gif',
    'ru-COI-KVI-1.gif',
    'ru-COI-KVIA A-1.gif',
    'ru-COI-KVIA B-1.gif',
    'ru-COI-KVIC A-1.gif',
    'ru-COI-KVIC B-1.gif',
    'ru-COI-KVIIA W-1.gif',
    'ru-COI-KVIIA-1.gif',
    'ru-COI-KVIx W-1.gif',
    'ru-COI-M5 57LL-1.gif',
    'ru-COI-M5 A-1.gif',
    'ru-COI-M5 B-1.gif',
    'ru-COI-M5 C-1.gif',
    'ru-COI-M5 W-1.gif',
    'ru-COI-M5-57LL W-1.gif',
    'ru-COI-Mortar Brk.gif',
    'ru-COI-Rct Brk-1.gif',
    'ru-COI-Rct-1.gif',
    'ru-COI-SU100 W-1.gif',
    'ru-COI-SU100-1.gif',
    'ru-COI-SU100Y W-1.gif',
    'ru-COI-SU100Y-1.gif',
    'ru-COI-SU122 A-1.gif',
    'ru-COI-SU122 B-1.gif',
    'ru-COI-SU122 B-6a.gif',
    'ru-COI-SU122 W-1.gif',
    'ru-COI-SU14Br2 W-1.gif',
    'ru-COI-SU14Br2-1.gif',
    'ru-COI-SU152 W-1.gif',
    'ru-COI-SU152-1.gif',
    'ru-COI-SU37A w-1.gif',
    'ru-COI-SU37A-1.gif',
    'ru-COI-SU37B w-1.gif',
    'ru-COI-SU37B-1.gif',
    'ru-COI-SU45 W-1.gif',
    'ru-COI-SU45-1.gif',
    'ru-COI-SU57 W-1.gif',
    'ru-COI-SU57-1.gif',
    'ru-COI-SU76 A-1.gif',
    'ru-COI-SU76 B-1.gif',
    'ru-COI-SU76 C-1.gif',
    'ru-COI-SU76M A-1.gif',
    'ru-COI-SU76M B-1.gif',
    'ru-COI-SU76M C-1.gif',
    'ru-COI-SU76M D-1.gif',
    'ru-COI-SU76x W-1.gif',
    'ru-COI-SU85 W-1.gif',
    'ru-COI-SU85-1.gif',
    'ru-COI-SW 50Mtr.gif',
    'ru-COI-SW 50MtrB.gif',
    'ru-COI-SW-hmg.gif',
    'ru-COI-SW-hmgB.gif',
    'ru-COI-T26OT W-1.gif',
    'ru-COI-T26OT-1.gif',
    'ru-COI-T26S W-1.gif',
    'ru-COI-T26S-1.gif',
    'ru-COI-T28B A-1.gif',
    'ru-COI-T28B B-1.gif',
    'ru-COI-T28B W-1.gif',
    'ru-COI-T28C W-1.gif',
    'ru-COI-T28C-1.gif',
    'ru-COI-T34-76A-1.gif',
    'ru-COI-T34-76A-w-1.gif',
    'ru-COI-T34-76B w-1.gif',
    'ru-COI-T34-76B-1.gif',
    'ru-COI-T34-76C w-1.gif',
    'ru-COI-T34-76C-1.gif',
    'ru-COI-T34.85 W-1.gif',
    'ru-COI-T34.85-1.gif',
    'ru-COI-T34ATO W-1.gif',
    'ru-COI-T34ATO-1.gif',
    'ru-COI-T35 W-1.gif',
    'ru-COI-T35-1.gif',
    'ru-COI-T37A W-1.gif',
    'ru-COI-T37A-1.gif',
    'ru-COI-T40 W-1.gif',
    'ru-COI-T40-1.gif',
    'ru-COI-T40A-1.gif',
    'ru-COI-T43 W-1.gif',
    'ru-COI-T43-1.gif',
    'ru-COI-T50 W-1.gif',
    'ru-COI-T50-1.gif',
    'ru-COI-T60-1.gif',
    'ru-COI-T60-70 W-1.gif',
    'ru-COI-T60A-1.gif',
    'ru-COI-T70-1.gif',
    'ru-COI-ZIS Lt Truck W-1.gif',
    'ru-COI-ZIS Lt Truck-1.gif',
    'ru-COI-ZISa W-1.gif',
    'ru-COI-ZISa-1.gif',
    'ru-COI-ZISb-1.gif',
    'ru-COI-ZISb-c W-1.gif',
    'ru-COI-ZISc-1.gif',
    'ru-COI-ZISd W-1.gif',
    'ru-COI-ZISd-1.gif',
    'ru-COI-ZISe W-1.gif',
    'ru-COI-ZISe-1.gif',
    'ru-COI-ZISf-1.gif',
    'ru-COI-ZISf-h W-1.gif',
    'ru-COI-ZISg-1.gif',
    'ru-COI-ZISh-1.gif',
    'ru-conceal-lg.gif',
    'ru-conceal.gif',
    'ru-concealment-large.gif',
    'ru-IL2.gif',
    'ru-IL2M-1.gif',
    'ru-IL2M3-1.gif',
    'ru-MMC 237.gif',
    'ru-MMC 237B.gif',
    'ru-MMC 336.gif',
    'ru-MMC 336B.gif',
    'ru-MMC 436.gif',
    'ru-MMC 436B.gif',
    'ru-MMC 447.gif',
    'ru-MMC 447B.gif',
    'ru-MMC 448.gif',
    'ru-MMC 448B.gif',
    'ru-MMC 537.gif',
    'ru-MMC 537B.gif',
    'ru-MMC 5B.gif',
    'ru-MMC 628.gif',
    'ru-MMC 628B.gif',
    'ru-MMC 7B.gif',
    'ru-MMC 8B.gif',
    'ru-MMC DYO-B.gif',
    'ru-MMC DYO-B1.gif',
    'ru-MMC DYO-Bzk.gif',
    'ru-MMC DYO.gif',
    'ru-mmc-458.gif',
    'ru-mmc-458B.gif',
    'ru-SL-122 W-1.gif',
    'ru-SL-152 W-1.gif',
    'ru-SL-T34 W-1.gif',
    'ru-SMC 10-0-w.gif',
    'ru-SMC 10-0.gif',
    'ru-SMC 10-2 Bzk.gif',
    'ru-SMC 10-3 Bzk.gif',
    'ru-SMC 10B-w.gif',
    'ru-SMC 10B.gif',
    'ru-SMC 5B-w.gif',
    'ru-SMC 6+1-Bzk-w.gif',
    'ru-SMC 6+1-Bzk.gif',
    'ru-SMC 6+1-w.gif',
    'ru-SMC 6+1.gif',
    'ru-SMC 6+1B.gif',
    'ru-SMC 6-0 Bzk-w.gif',
    'ru-SMC 6-0-w.gif',
    'ru-SMC 6B-w.gif',
    'ru-SMC 6B.gif',
    'ru-SMC 7-0 Bzk-w.gif',
    'ru-SMC 7-0 Bzk.gif',
    'ru-SMC 7-0-w.gif',
    'ru-SMC 7-0.gif',
    'ru-SMC 7B-w.gif',
    'ru-SMC 7B.gif',
    'ru-SMC 8-0 Bzk-w.gif',
    'ru-SMC 8-0 Bzk.gif',
    'ru-SMC 8-0-w.gif',
    'ru-SMC 8-0.gif',
    'ru-SMC 8-1 Bzk-w.gif',
    'ru-SMC 8-1 Bzk.gif',
    'ru-SMC 8-1-w.gif',
    'ru-SMC 8-1.gif',
    'ru-SMC 8B-w.gif',
    'ru-SMC 8B.gif',
    'ru-SMC 9-0-w.gif',
    'ru-SMC 9-0.gif',
    'ru-SMC 9-1 Bzk-w.gif',
    'ru-SMC 9-1 Bzk.gif',
    'ru-SMC 9-1-w.gif',
    'ru-SMC 9-1.gif',
    'ru-SMC 9-2 Bzk-w.gif',
    'ru-SMC 9-2 Bzk.gif',
    'ru-SMC 9-2-w.gif',
    'ru-SMC 9B-w.gif',
    'ru-SMC 9B.gif',
    'ru-SMC Par 6-0-Bzk-w.gif',
    'ru-SMC Par 6-0-w.gif',
    'ru-SMC Par 7-0-Bzk-w.gif',
    'ru-SMC Par 7-0-Bzk.gif',
    'ru-SMC Par 7-0-w.gif',
    'ru-SMC Par 7-0.gif',
    'ru-SMC Par 7-0B.gif',
    'ru-SMC Par 8-0-Bzk-w.gif',
    'ru-SMC Par 8-0-Bzk.gif',
    'ru-SMC Par 8-0-w.gif',
    'ru-SMC Par 8-0.gif',
    'ru-SMC Par 8-0B.gif',
    'ru-SMC Par 8-1-Bzk.gif',
    'ru-SMC Par 8-1.gif',
    'ru-SMC Par 8-1B.gif',
    'ru-SMC Par 9-1-Bzk.gif',
    'ru-SMC Par 9-1.gif',
    'ru-SMC Par 9-1B.gif',
    'ru-SMC-10-2 Bzk.gif',
    'ru-SMC-10-3 Bzk.gif',
    'ru-SMC-7-0 Bzk.gif',
    'ru-SMC-8-0 Bzk.gif',
    'ru-SMC-8-1 Bzk.gif',
    'ru-SMC-9-1 Bzk.gif',
    'ru-SMC-9-2 Bzk.gif',
    'ru-smc-cod-10-0-w.gif',
    'ru-smc-cod-10-0.gif',
    'ru-smc-cod-10-0b-w.gif',
    'ru-smc-cod-10-0b.gif',
    'ru-smc-cod-9-0-w.gif',
    'ru-smc-cod-9-0.gif',
    'ru-smc-cod-9-0b-w.gif',
    'ru-smc-cod-9-0b.gif',
    'ru-smc-cod-DYO-Comm.gif',
    'ru-smc-Sniper-1-Bzk.gif',
    'ru-SMC-Sniper-1.gif',
    'ru-smc-Sniper-2-Bzk.gif',
    'ru-smc-Sniper-3-Bzk.gif',
    'ru-smc-Sniper-4-Bzk.gif',
    'ru-smc-SniperB.gif',
    'ru-SW FT.gif',
    'ru-SW FTF.gif',
    'ru-SW Radio.gif',
    'ru-SW RadioB.gif',
    'ru-SW-ATM.gif',
    'ru-SW-ATMF.gif',
    'ru-SW-ATR.gif',
    'ru-SW-ATRB.gif',
    'ru-SW-DC.gif',
    'ru-SW-DCF.gif',
    'ru-SW-MG-H.gif',
    'ru-SW-MG-HB.gif',
    'ru-SW-MG-L.gif',
    'ru-SW-MG-LB.gif',
    'ru-SW-MG-M.gif',
    'ru-SW-MG-MB.gif',
    'ru-SW-Mortar.gif',
    'ru-SW-MortarB.gif',
    'ru-v-M3 MG-1.gif',
    'ru-v-M3-1.gif',
    'ru-v-M3-MG-Wreck.gif',
    'ru-v-M3-Wreck.gif',
    'ru-v-SU122-1.gif',
    'ru-v-SU122-Wreck.gif',
    'ru-v-SU152-1.gif',
    'ru-v-SU152-Wreck.gif',
    'ru-v-T34-1.gif',
    'ru-v-T34-Wreck.gif',
    'ru-v-Truck-1.gif',
    'ru-v-Truck-Wreck.gif',
    'russ.gif',
    'sadis.gif',
    'samalf.gif',
    'SMC 6+1.gif',
    'smc-CE-2-B.gif',
    'Sr.gif',
    'Sr_b.gif',
    'St_rub.gif',
    'stun.gif',
    'VChex.gif',
    'Wd_rub.gif',];