var component_list = [
    [
        "All",
        ["1md", {"b": "1MD.ex.gif", "f": "1MD.gif"}],
        ["1me", {"b": "1ME.ex.gif", "f": "1ME.gif"}],
        ["1ri", {"b": "1RI.ex.gif", "f": "1RI.gif"}],
        ["2va", {"b": "2VA.ex.gif", "f": "2VA.gif"}],
        ["3in", {"b": "3IN.ex.gif", "f": "3IN.gif"}],
        ["4ny", {"b": "4NY.ex.gif", "f": "4NY.gif"}],
        ["60ny", {"b": "60NY.ex.gif", "f": "60NY.gif"}],
        ["6ny", {"b": "6NY.ex.gif", "f": "6NY.gif"}],
        ["9vt", {"b": "9VT.ex.gif", "f": "9VT.gif"}],
        ["activemv", {"f": "Activemv.gif"}],
        ["ammo1", {"f": "Ammo1.gif"}],
        ["ammo2", {"f": "Ammo2.gif"}],
        ["ammo3", {"f": "Ammo3.gif"}],
        ["ammo4", {"f": "Ammo4.gif"}],
        ["ammoout", {"f": "AmmoOut.gif"}],
        ["anderson", {"b": "Anderson.ex.gif", "f": "Anderson.gif"}],
        ["aphill", {"b": "APHill.ex.gif", "f": "APHill.gif"}],
        ["art0", {"f": "Art0.gif"}],
        ["art1", {"f": "Art1.gif"}],
        ["art2", {"f": "Art2.gif"}],
        ["art3", {"f": "Art3.gif"}],
        ["art4", {"f": "Art4.gif"}],
        ["art5", {"f": "Art5.gif"}],
        ["art6", {"f": "Art6.gif"}],
        ["art7", {"f": "Art7.gif"}],
        ["art8", {"f": "Art8.gif"}],
        ["art9", {"f": "Art9.gif"}],
        ["augur", {"b": "Augur.ex.gif", "f": "Augur.gif"}],
        ["banks", {"f": "Banks.gif"}],
        ["bayard", {"b": "Bayard.ex.gif", "f": "Bayard.gif"}],
        ["beardsley", {"b": "Beardsley.ex.gif", "f": "Beardsley.gif"}],
        ["breastwork", {"f": "Breastwork.gif"}],
        ["breastworkbuild.x1", {"f": "BreastworkBuild.x1.gif"}],
        ["bridge.rem", {"f": "bridge.rem.gif"}],
        ["buford", {"b": "Buford.ex.gif", "f": "Buford.gif"}],
        ["c.disorg1", {"f": "C.disorg1.gif"}],
        ["c.disorg10", {"f": "C.disorg10.gif"}],
        ["c.disorg11", {"f": "C.disorg11.gif"}],
        ["c.disorg12", {"f": "C.disorg12.gif"}],
        ["c.disorg13", {"f": "C.disorg13.gif"}],
        ["c.disorg14", {"f": "C.disorg14.gif"}],
        ["c.disorg15", {"f": "C.disorg15.gif"}],
        ["c.disorg16", {"f": "C.disorg16.gif"}],
        ["c.disorg17", {"f": "C.disorg17.gif"}],
        ["c.disorg18", {"f": "C.disorg18.gif"}],
        ["c.disorg2", {"f": "C.disorg2.gif"}],
        ["c.disorg3", {"f": "C.disorg3.gif"}],
        ["c.disorg4", {"f": "C.disorg4.gif"}],
        ["c.disorg5", {"f": "C.disorg5.gif"}],
        ["c.disorg6", {"f": "C.disorg6.gif"}],
        ["c.disorg7", {"f": "C.disorg7.gif"}],
        ["c.disorg8", {"f": "C.disorg8.gif"}],
        ["c.disorg9", {"f": "C.disorg9.gif"}],
        ["c.org1", {"f": "C.org1.gif"}],
        ["c.org10", {"f": "C.org10.gif"}],
        ["c.org11", {"f": "C.org11.gif"}],
        ["c.org12", {"f": "C.org12.gif"}],
        ["c.org13", {"f": "C.org13.gif"}],
        ["c.org14", {"f": "C.org14.gif"}],
        ["c.org15gif", {"f": "C.org15gif.gif"}],
        ["c.org16", {"f": "C.org16.gif"}],
        ["c.org17", {"f": "C.org17.gif"}],
        ["c.org18", {"f": "C.org18.gif"}],
        ["c.org2", {"f": "C.org2.gif"}],
        ["c.org3", {"f": "C.org3.gif"}],
        ["c.org4", {"f": "C.org4.gif"}],
        ["c.org5", {"f": "C.org5.gif"}],
        ["c.org6", {"f": "C.org6.gif"}],
        ["c.org7", {"f": "C.org7.gif"}],
        ["c.org8", {"f": "C.org8.gif"}],
        ["c.org9", {"f": "C.org9.gif"}],
        ["casey", {"b": "Casey.ex.gif", "f": "Casey.gif"}],
        ["cforce", {"f": "CForce.gif"}],
        ["cforce2", {"f": "CForce2.gif"}],
        ["cntr-controlobjcsa", {"f": "Cntr-ControlObjCSA.gif"}],
        ["cntr-controlobjusa", {"f": "Cntr-ControlObjUSA.gif"}],
        ["cntr-objcsa", {"f": "Cntr-ObjCSA.gif"}],
        ["cntr-objusa", {"f": "Cntr-ObjUSA.gif"}],
        ["confed.bridge", {"f": "Confed.bridge.gif"}],
        ["confed.bridgemajor", {"f": "Confed.bridgeMajor.gif"}],
        ["confed.bridgeminor", {"f": "Confed.bridgeMinor.gif"}],
        ["confed.dem1", {"f": "Confed.dem1.gif"}],
        ["confed.dem2", {"f": "Confed.dem2.gif"}],
        ["confed.force2", {"f": "Confed.force2.gif"}],
        ["confed.obj", {"f": "Confed.obj.gif"}],
        ["corpsmv", {"f": "Corpsmv.gif"}],
        ["couch", {"b": "Couch.ex.gif", "f": "Couch.gif"}],
        ["crawford", {"b": "Crawford.ex.gif", "f": "Crawford.gif"}],
        ["csaforce3", {"f": "CSAforce3.gif"}],
        ["csaforce4", {"f": "CSAforce4.gif"}],
        ["csaforce5", {"f": "CSAforce5.gif"}],
        ["csaforce6", {"f": "CSAforce6.gif"}],
        ["csaforce7", {"f": "CSAforce7.gif"}],
        ["csaforce8", {"f": "CSAforce8.gif"}],
        ["csub1", {"b": "CSub1.ex.gif", "f": "CSub1.gif"}],
        ["csub2", {"b": "CSub2.ex.gif", "f": "CSub2.gif"}],
        ["csub3", {"b": "CSub3.ex.gif", "f": "CSub3.gif"}],
        ["csub4", {"b": "CSub4.ex.gif", "f": "CSub4.gif"}],
        ["csub5", {"b": "CSub5.ex.gif", "f": "CSub5.gif"}],
        ["csub6", {"b": "CSub6.ex.gif", "f": "CSub6.gif"}],
        ["csub7", {"b": "CSub7.ex.gif", "f": "CSub7.gif"}],
        ["csub8", {"b": "CSub8.ex.gif", "f": "CSub8.gif"}],
        ["damage", {"f": "Damage.gif"}],
        ["destroy", {"f": "Destroy.gif"}],
        ["destroyed fort", {"f": "Destroyed Fort.gif"}],
        ["dhhill", {"b": "DHHill.ex.gif", "f": "DHHill.gif"}],
        ["drjones", {"b": "DRJones.ex.gif", "f": "DRJones.gif"}],
        ["evans", {"b": "Evans.ex.gif", "f": "Evans.gif"}],
        ["ewella", {"b": "EwellA.ex.gif", "f": "EwellA.gif"}],
        ["ewellb", {"b": "EwellB.ex.gif", "f": "EwellB.gif"}],
        ["fairchild", {"b": "Fairchild.ex.gif", "f": "Fairchild.gif"}],
        ["fatigue1", {"f": "Fatigue1.gif"}],
        ["fatigue2", {"f": "Fatigue2.gif"}],
        ["fatigue3", {"f": "Fatigue3.gif"}],
        ["fatigue4", {"f": "Fatigue4.gif"}],
        ["ferrero", {"b": "Ferrero.ex.gif", "f": "Ferrero.gif"}],
        ["flankref.csa", {"f": "FlankRef.CSA.gif"}],
        ["flankref.usa", {"f": "FlankRef.USA.gif"}],
        ["flee", {"b": "FLee.ex.gif", "f": "FLee.gif"}],
        ["fort", {"f": "Fort.gif"}],
        ["fortbuild.x2", {"f": "FortBuild.x2.gif"}],
        ["franklin", {"f": "Franklin.gif"}],
        ["greene", {"b": "Greene.ex.gif", "f": "Greene.gif"}],
        ["gregg", {"b": "Gregg.ex.gif", "f": "Gregg.gif"}],
        ["griffin", {"b": "Griffin.ex.gif", "f": "Griffin.gif"}],
        ["hampton", {"b": "Hampton.ex.gif", "f": "Hampton.gif"}],
        ["harland", {"b": "Harland.ex.gif", "f": "Harland.gif"}],
        ["heintzmn", {"f": "Heintzmn.gif"}],
        ["hood", {"b": "Hood.ex.gif", "f": "Hood.gif"}],
        ["hooker", {"b": "Hooker.ex.gif", "f": "Hooker.gif"}],
        ["jackson", {"f": "Jackson.gif"}],
        ["jackson.sub", {"f": "Jackson.sub.gif"}],
        ["kearny", {"b": "Kearny.ex.gif", "f": "Kearny.gif"}],
        ["kemper", {"b": "Kemper.ex.gif", "f": "Kemper.gif"}],
        ["kimball", {"b": "Kimball.ex.gif", "f": "Kimball.gif"}],
        ["king", {"b": "King.ex.gif", "f": "King.gif"}],
        ["lawton", {"b": "Lawton.ex.gif", "f": "Lawton.gif"}],
        ["ldractive", {"f": "LdrActive.gif"}],
        ["ldractive_csa", {"f": "LdrActive_CSA.gif"}],
        ["ldrmv", {"f": "LdrMv.gif"}],
        ["lee", {"f": "Lee.gif"}],
        ["longstreet", {"f": "Longstreet.gif"}],
        ["longstreet.sub", {"f": "Longstreet.sub.gif"}],
        ["major_river_unfordablerev", {"f": "major_river_unfordableRev.gif"}],
        ["mcclelln", {"f": "McClelln.gif"}],
        ["mcdowll", {"f": "McDowll.gif"}],
        ["mclaws", {"b": "McLaws.ex.gif", "f": "McLaws.gif"}],
        ["milroy", {"b": "Milroy.ex.gif", "f": "Milroy.gif"}],
        ["minor_river_unfordablerev", {"f": "minor_river_unfordableRev.gif"}],
        ["moor", {"b": "Moor.ex.gif", "f": "Moor.gif"}],
        ["morell", {"b": "Morell.ex.gif", "f": "Morell.gif"}],
        ["new banks", {"f": "New Banks.gif"}],
        ["new flanklin", {"f": "New Flanklin.gif"}],
        ["new heintzelman", {"f": "New Heintzelman.gif"}],
        ["new jackson", {"f": "New Jackson.gif"}],
        ["new jackson.sub", {"f": "New Jackson.sub.gif"}],
        ["new longstreet", {"f": "New Longstreet.gif"}],
        ["new longstreet.sub", {"f": "New Longstreet.sub.gif"}],
        ["new mcdowell", {"f": "New Mcdowell.gif"}],
        ["new porter", {"f": "New Porter.gif"}],
        ["new reno", {"f": "New Reno.gif"}],
        ["new sigel", {"f": "New Sigel.gif"}],
        ["new stuart", {"f": "New Stuart.gif"}],
        ["new stuart.sub", {"f": "New Stuart.sub.gif"}],
        ["new sumner", {"f": "New Sumner.gif"}],
        ["outofsupply", {"f": "OutOfSupply.gif"}],
        ["parke", {"b": "Parke.ex.gif", "f": "Parke.gif"}],
        ["piatt", {"b": "Piatt.ex.gif", "f": "Piatt.gif"}],
        ["pleasontn", {"b": "Pleasontn.ex.gif", "f": "Pleasontn.gif"}],
        ["pnellleg", {"b": "PnellLeg.ex.gif", "f": "PnellLeg.gif"}],
        ["pope", {"f": "Pope.gif"}],
        ["porter", {"f": "Porter.gif"}],
        ["rain", {"f": "Rain.gif"}],
        ["reno", {"f": "Reno.gif"}],
        ["reynolds", {"b": "Reynolds.ex.gif", "f": "Reynolds.gif"}],
        ["richrdson", {"b": "Richrdson.ex.gif", "f": "Richrdson.gif"}],
        ["ricketts", {"b": "Ricketts.ex.gif", "f": "Ricketts.gif"}],
        ["ripley", {"b": "Ripley.ex.gif", "f": "Ripley.gif"}],
        ["robertson", {"b": "Robertson.ex.gif", "f": "Robertson.gif"}],
        ["scammon", {"b": "Scammon.ex.gif", "f": "Scammon.gif"}],
        ["schenck", {"b": "Schenck.ex.gif", "f": "Schenck.gif"}],
        ["schurz", {"b": "Schurz.ex.gif", "f": "Schurz.gif"}],
        ["sedgwick", {"b": "Sedgwick.ex.gif", "f": "Sedgwick.gif"}],
        ["sigel", {"f": "Sigel.gif"}],
        ["slocum", {"b": "Slocum.ex.gif", "f": "Slocum.gif"}],
        ["smith", {"b": "Smith.ex.gif", "f": "Smith.gif"}],
        ["steinw", {"b": "Steinw.ex.gif", "f": "Steinw.gif"}],
        ["stevens", {"b": "Stevens.ex.gif", "f": "Stevens.gif"}],
        ["stuart", {"f": "Stuart.gif"}],
        ["stuart.sub", {"f": "Stuart.sub.gif"}],
        ["sturgis", {"b": "Sturgis.ex.gif", "f": "Sturgis.gif"}],
        ["sub1", {"b": "Sub1.ex.gif", "f": "Sub1.gif"}],
        ["sub2", {"b": "Sub2.ex.gif", "f": "Sub2.gif"}],
        ["sub3", {"b": "Sub3.ex.gif", "f": "Sub3.gif"}],
        ["sub4", {"b": "Sub4.ex.gif", "f": "Sub4.gif"}],
        ["sub5", {"b": "Sub5.ex.gif", "f": "Sub5.gif"}],
        ["sub6", {"b": "Sub6.ex.gif", "f": "Sub6.gif"}],
        ["subu1", {"b": "SubU1.ex.gif", "f": "SubU1.gif"}],
        ["subu2", {"b": "SubU2.ex.gif", "f": "SubU2.gif"}],
        ["subu3", {"b": "SubU3.ex.gif", "f": "SubU3.gif"}],
        ["subu4c", {"b": "SubU4c.ex.gif", "f": "SubU4c.gif"}],
        ["subu5c", {"b": "SubU5c.ex.gif", "f": "SubU5c.gif"}],
        ["subu6", {"b": "SubU6.ex.gif", "f": "SubU6.gif"}],
        ["sumner", {"f": "Sumner.gif"}],
        ["sykes", {"b": "Sykes.ex.gif", "f": "Sykes.gif"}],
        ["taliafero", {"b": "Taliafero.ex.gif", "f": "Taliafero.gif"}],
        ["taylor", {"b": "Taylor.ex.gif", "f": "Taylor.gif"}],
        ["turnrev", {"f": "turnRev.gif"}],
        ["union.bridge", {"f": "Union.bridge.gif"}],
        ["union.bridgemajor", {"f": "Union.bridgeMajor.gif"}],
        ["union.bridgeminor", {"f": "Union.bridgeMinor.gif"}],
        ["union.dem1", {"f": "Union.dem1.gif"}],
        ["union.dem2", {"f": "Union.dem2.gif"}],
        ["union.depot", {"f": "Union.depot.gif"}],
        ["union.disorg1", {"f": "Union.disorg1.gif"}],
        ["union.disorg10", {"f": "Union.disorg10.gif"}],
        ["union.disorg11", {"f": "Union.disorg11.gif"}],
        ["union.disorg12", {"f": "Union.disorg12.gif"}],
        ["union.disorg13", {"f": "Union.disorg13.gif"}],
        ["union.disorg14", {"f": "Union.disorg14.gif"}],
        ["union.disorg15", {"f": "Union.disorg15.gif"}],
        ["union.disorg16", {"f": "Union.disorg16.gif"}],
        ["union.disorg17", {"f": "Union.disorg17.gif"}],
        ["union.disorg18", {"f": "Union.disorg18.gif"}],
        ["union.disorg2", {"f": "Union.disorg2.gif"}],
        ["union.disorg3", {"f": "Union.disorg3.gif"}],
        ["union.disorg4", {"f": "Union.disorg4.gif"}],
        ["union.disorg5", {"f": "Union.disorg5.gif"}],
        ["union.disorg6", {"f": "Union.disorg6.gif"}],
        ["union.disorg7", {"f": "Union.disorg7.gif"}],
        ["union.disorg8", {"f": "Union.disorg8.gif"}],
        ["union.disorg9", {"f": "Union.disorg9.gif"}],
        ["union.org1", {"f": "Union.org1.gif"}],
        ["union.org10", {"f": "Union.org10.gif"}],
        ["union.org11", {"f": "Union.org11.gif"}],
        ["union.org12", {"f": "Union.org12.gif"}],
        ["union.org13", {"f": "Union.org13.gif"}],
        ["union.org14", {"f": "Union.org14.gif"}],
        ["union.org15", {"f": "Union.org15.gif"}],
        ["union.org16", {"f": "Union.org16.gif"}],
        ["union.org17", {"f": "Union.org17.gif"}],
        ["union.org18", {"f": "Union.org18.gif"}],
        ["union.org2", {"f": "Union.org2.gif"}],
        ["union.org3", {"f": "Union.org3.gif"}],
        ["union.org4", {"f": "Union.org4.gif"}],
        ["union.org5", {"f": "Union.org5.gif"}],
        ["union.org6", {"f": "Union.org6.gif"}],
        ["union.org7", {"f": "Union.org7.gif"}],
        ["union.org8", {"f": "Union.org8.gif"}],
        ["union.org9", {"f": "Union.org9.gif"}],
        ["usaforce1", {"f": "USAforce1.gif"}],
        ["usaforce10", {"f": "USAforce10.gif"}],
        ["usaforce11", {"f": "USAforce11.gif"}],
        ["usaforce12", {"f": "USAforce12.gif"}],
        ["usaforce2", {"f": "USAforce2.gif"}],
        ["usaforce3", {"f": "USAforce3.gif"}],
        ["usaforce4", {"f": "USAforce4.gif"}],
        ["usaforce5", {"f": "USAforce5.gif"}],
        ["usaforce6", {"f": "USAforce6.gif"}],
        ["usaforce7", {"f": "USAforce7.gif"}],
        ["usaforce8", {"f": "USAforce8.gif"}],
        ["usaforce9", {"f": "USAforce9.gif"}],
        ["waagner", {"b": "Waagner.ex.gif", "f": "Waagner.gif"}],
        ["walker", {"b": "Walker.ex.gif", "f": "Walker.gif"}],
        ["whipple", {"b": "Whipple.ex.gif", "f": "Whipple.gif"}],
        ["white", {"b": "White.ex.gif", "f": "White.gif"}],
        ["wilcox", {"b": "Wilcox.ex.gif", "f": "Wilcox.gif"}],
        ["williamsa", {"b": "WilliamsA.ex.gif", "f": "WilliamsA.gif"}],
        ["williamsb", {"b": "WilliamsB.ex.gif", "f": "WilliamsB.gif"}],
        ["winder", {"b": "Winder.ex.gif", "f": "Winder.gif"}],
    ]
];