var component_list = [
    '!!! Marker.png',
    '!!! Marker2.png',
    'Das marker.png',
    'East Factory1.png',
    'East Factory2.png',
    'East Factory3.png',
    'East Factory4.png',
    'East Factory5.png',
    'East Factory6.png',
    'Extrenal Factory 1.png',
    'Extrenal Factory 2.png',
    'Extrenal Factory 3.png',
    'Factory Layer 1.png',
    'Flight Marker.png',
    'Flight Track Marker.png',
    'Fur Marker.png',
    'Infrastructure_layer_1.png',
    'Infrastructure_red.png',
    'Infrastructure_yellow.png',
    'Keine Marker.png',
    'LS Marker Small.png',
    'LS Marker.png',
    'Macht Marker.png',
    'Niemand Marker.png',
    'Prestige Marker.png',
    'Red !!! Marker.png',
    'Red !!! Marker2.png',
    'Rheinsberg Factory rundown.png',
    'Rheinsberg Factory.png',
    'Rundown East Factory0.png',
    'Rundown East Factory1.png',
    'Rundown East Factory2.png',
    'Rundown East Factory3.png',
    'Rundown East Factory4.png',
    'Rundown East Factory5.png',
    'Sind Marker.png',
    'Socialist Cube Small.png',
    'Socialist Cube.png',
    'Socialist Marker.png',
    'unrest.png',
    'Volk Marker.png',
    'Wall Built Marker.png',
    'WC_marker.png',
    'West Factory 1.png',
    'West Factory 2.png',
    'West Factory 3.png',
    'West Factory 4.png',
    'West Factory 5.png',
    'West Factory 6.png',
    'Wir Marker.png'
];