var component_list = [
    '+ DRM Attacker.png',
    '+ DRM Defender.png',
    '- DRM Attacker.png',
    '- DRM Defender.png',
    'Allied Airdrop - back.png',
    'Allied Airdrop - front.png',
    'Appeasement or Pact Ends.png',
    'Area Seized.png',
    'Assault.png',
    'Axis Control.png',
    'Axis Strategic Move - back.png',
    'Axis Strategic Move - front.png',
    'Axis Strategic Move - What If - back.png',
    'Axis Strategic Move - What If - front.png',
    'Belgium Garrison 2 - What If - back.png',
    'Belgium Garrison 2 - What If - front.png',
    'Belgium Infantry 1 - Full.png',
    'Belgium Infantry 1 - Reduced.png',
    'Belgium Prod 1s - back.png',
    'Belgium Prod 1s - front.png',
    'Belgium Will 1s - back.png',
    'Belgium Will 1s - front.png',
    'Bombed - back.png',
    'Bombed - front.png',
    'Bulgaria Garrison 5 - back.png',
    'Bulgaria Garrison 5 - front.png',
    'Bulgaria Infantry 1 - Full.png',
    'Bulgaria Infantry 1 - Reduced.png',
    'Bulgaria Prod 1s - back.png',
    'Bulgaria Prod 1s - front.png',
    'Bulgaria Will 1s - back.png',
    'Bulgaria Will 1s - front.png',
    'Commonwealth Trade - front.png',
    'Denmark Garrison 1 - back.png',
    'Denmark Garrison 1 - front.png',
    'Denmark Infantry 2 - What If - Full.png',
    'Denmark Infantry 2 - What If - Reduced.png',
    'Denmark Prod 1s - back.png',
    'Denmark Prod 1s - front.png',
    'Denmark Will 1s - back.png',
    'Denmark Will 1s - front.png',
    'Diplomacy_Back.png',
    'Estonia Garrison 1 - back.png',
    'Estonia Garrison 1 - front.png',
    'Estonia Infantry 2 - What If - Full.png',
    'Estonia Infantry 2 - What If - Reduced.png',
    'Estonia Prod 1s - back.png',
    'Estonia Prod 1s - front.png',
    'Estonia Will 1s - back.png',
    'Estonia Will 1s - front.png',
    'Factory - What If - back.png',
    'Factory - What If - front.png',
    'Finland Garrison N. Fin - back.png',
    'Finland Garrison N. Fin - front.png',
    'Finland Garrison W. Fin - back.png',
    'Finland Garrison W. Fin - front.png',
    'Finland Infantry Isthmus - Full.png',
    'Finland Infantry Isthmus - Reduced.png',
    'Finland Infantry Talvela - Full.png',
    'Finland Infantry Talvela - Reduced.png',
    'Finland Prod 1s - back.png',
    'Finland Prod 1s - front.png',
    'Finland Will 1s - back.png',
    'Finland Will 1s - front.png',
    'FNA Garrison 2 - back.png',
    'FNA Garrison 2 - front.png',
    'FNA Garrison 3 - back.png',
    'FNA Garrison 3 - front.png',
    'FNA Infantry 1 - Full.png',
    'FNA Infantry 1 - Reduced.png',
    'FNA Infantry 4 - What If - Full.png',
    'FNA Infantry 4 - What If - Reduced.png',
    'FNA Prod 1s - back.png',
    'FNA Prod 1s - front.png',
    'FNA Will 1s - back.png',
    'FNA Will 1s - front.png',
    'France Air 1 - front.png',
    'France Air 2 - front.png',
    'France Convoy - What If - back.png',
    'France Convoy 1 - front.png',
    'France Convoy 2 - What If - front.png',
    'France Fleet 1 - front.png',
    'France Fleet 2 - What If - back.png',
    'France Surface - What If - back.png',
    'French Convoy - back.png',
    'French Factory Count - back.png',
    'French Factory Count - front.png',
    'French Fighter - back.png',
    'French Fort - back.png',
    'French Fort - What If - back.png',
    'French Fort Maginot - front.png',
    'French Fort Maginot - What If - front.png',
    'French Garrison N. Africa 2 - back.png',
    'French Garrison N. Africa 2 - front.png',
    'French Garrison N. Africa 3 - back.png',
    'French Garrison N. Africa 3 - front.png',
    'French Garrison Syria - front.png',
    'French Guard 1 - Full.png',
    'French Guard 1 - Reduced.png',
    'French Guard 2 - Full.png',
    'French Guard 2 - Reduced.png',
    'French Guard 3 - Full.png',
    'French Guard 3 - Reduced.png',
    'French Infantry 1 - Full.png',
    'French Infantry 1 - Reduced.png',
    'French Infantry 10 - Full.png',
    'French Infantry 10 - Reduced.png',
    'French Infantry 2 - Full.png',
    'French Infantry 2 - Reduced.png',
    'French Infantry 3 - Full.png',
    'French Infantry 3 - Reduced.png',
    'French Infantry 4 - Full.png',
    'French Infantry 4 - Reduced.png',
    'French Infantry 5 - Full.png',
    'French Infantry 5 - Reduced.png',
    'French Infantry 6 - Full.png',
    'French Infantry 6 - Reduced.png',
    'French Infantry 7 - Full.png',
    'French Infantry 7 - Reduced.png',
    'French Infantry 8 - Full.png',
    'French Infantry 8 - Reduced.png',
    'French Infantry 9 - Full.png',
    'French Infantry 9 - Reduced.png',
    'French Infantry Alps - Full.png',
    'French Infantry Alps - Reduced.png',
    'French Infantry N. Africa 1 - Full.png',
    'French Infantry N. Africa 1 - Reduced.png',
    'French Motorized 1 - What If - Full.png',
    'French Motorized 1 - What If - Reduced.png',
    'French Motorized 2 - What If - Full.png',
    'French Motorized 2 - What If - Reduced.png',
    'French Prod 10s - back.png',
    'French Prod 10s - front.png',
    'French Prod 1s - back.png',
    'French Prod 1s - front.png',
    'French Surface - back.png',
    'French Tank 1 - Full.png',
    'French Tank 1 - Reduced.png',
    'French Tank 2 - What If - Full.png',
    'French Tank 2 - What If - Reduced.png',
    'French Tanks - back.png',
    'French Tanks - front.png',
    'French Will 10s - back.png',
    'French Will 10s - front.png',
    'French Will 1s - back.png',
    'French Will 1s - front.png',
    'German Airdrop - back.png',
    'German Airdrop - front.png',
    'German Bomber - What If - back.png',
    'German Ceded - back.png',
    'German Ceded Area Alsace-Lorraine - front.png',
    'German Ceded Area Polish Corridor - front.png',
    'German Convoy - back.png',
    'German Convoy - What If - back.png',
    'German Convoy 1 - front.png',
    'German Convoy 2 - What If - front.png',
    'German Economic Reforms - front.png',
    'German Factory Count - back.png',
    'German Factory Count - front.png',
    'German Factory Lost - front.png',
    'German Fighter - back.png',
    'German Fleet 1 - What If - front.png',
    'German Garrison 1 - back.png',
    'German Garrison 1 - front.png',
    'German Garrison 2 - back.png',
    'German Garrison 2 - front.png',
    'German Garrison 3 - back.png',
    'German Garrison 3 - front.png',
    'German Garrison 4 - back.png',
    'German Garrison 4 - front.png',
    'German Garrison 5 - back.png',
    'German Garrison 5 - front.png',
    'German Garrison 6 - back.png',
    'German Garrison 6 - front.png',
    'German Garrison 7 - back.png',
    'German Garrison 7 - front.png',
    'German Garrison 8 - back.png',
    'German Garrison 8 - front.png',
    'German Garrison 9 - back.png',
    'German Garrison 9 - front.png',
    'German Garrison Liguria - back.png',
    'German Garrison Liguria - front.png',
    'German Garrison Vlasov - back.png',
    'German Garrison Vlasov - front.png',
    'German Ground Support - back.png',
    'German Ground Support - front.png',
    'German Ground Support - What If - back.png',
    'German Ground Support - What If - front.png',
    'German Heavy Artillery - back.png',
    'German Heavy Artillery - front.png',
    'German Infantry 1 - Full.png',
    'German Infantry 1 - Reduced.png',
    'German Infantry 10 - Full.png',
    'German Infantry 10 - Reduced.png',
    'German Infantry 11 - Full.png',
    'German Infantry 11 - Reduced.png',
    'German Infantry 12 - Full.png',
    'German Infantry 12 - Reduced.png',
    'German Infantry 14 - Full.png',
    'German Infantry 14 - Reduced.png',
    'German Infantry 15 - Full.png',
    'German Infantry 15 - Reduced.png',
    'German Infantry 16 - Full.png',
    'German Infantry 16 - Reduced.png',
    'German Infantry 17 - Full.png',
    'German Infantry 17 - Reduced.png',
    'German Infantry 18 - Full.png',
    'German Infantry 18 - Reduced.png',
    'German Infantry 19 - Full.png',
    'German Infantry 19 - Reduced.png',
    'German Infantry 2 - Full.png',
    'German Infantry 2 - Reduced.png',
    'German Infantry 20 - Full.png',
    'German Infantry 20 - Reduced.png',
    'German Infantry 4 - Full.png',
    'German Infantry 4 - Reduced.png',
    'German Infantry 6 - Full.png',
    'German Infantry 6 - Reduced.png',
    'German Infantry 7 - Full.png',
    'German Infantry 7 - Reduced.png',
    'German Infantry 8 - Full.png',
    'German Infantry 8 - Reduced.png',
    'German Infantry 9 - Full.png',
    'German Infantry 9 - Reduced.png',
    'German Infantry Norway - Full.png',
    'German Infantry Norway - Reduced.png',
    'German Jets - back.png',
    'German Jets - front.png',
    'German Luft 1 - front.png',
    'German Luft 2 - front.png',
    'German Luft 3 - front.png',
    'German Luft 4 - front.png',
    'German Luft 5 - front.png',
    'German Luft 6 - front.png',
    'German Luft Bomber - What If - front.png',
    'German Luft Re - front.png',
    'German Motorized Afrika - Full.png',
    'German Motorized Afrika - Reduced.png',
    'German Panzer 1 - Full.png',
    'German Panzer 1 - Reduced.png',
    'German Panzer 2 - Full.png',
    'German Panzer 2 - Reduced.png',
    'German Panzer 3 - Full.png',
    'German Panzer 3 - Reduced.png',
    'German Panzer 4 - Full.png',
    'German Panzer 4 - Reduced.png',
    'German Panzer 5 - Full.png',
    'German Panzer 5 - Reduced.png',
    'German Para 1 - Full.png',
    'German Para 1 - Reduced.png',
    'German Prod 10s - back.png',
    'German Prod 10s - front.png',
    'German Prod 1s - back.png',
    'German Prod 1s - front.png',
    'German Rockets - What If - back.png',
    'German Rockets - What If - front.png',
    'German SNAFU - What If - back.png',
    'German SNAFU - What If - front.png',
    'German SS 11 - Full.png',
    'German SS 11 - Reduced.png',
    'German SS 6 - Full.png',
    'German SS 6 - Reduced.png',
    'German Submarines - back.png',
    'German Submarines - front.png',
    'German Surface - What If - back.png',
    'German Surface Action - back.png',
    'German Surface Action - front.png',
    'German Surprise Attack - back.png',
    'German Surprise Attack - front.png',
    'German Tanks - back.png',
    'German Tanks - front.png',
    'German Will 10s - back.png',
    'German Will 10s - front.png',
    'German Will 1s - back.png',
    'German Will 1s - front.png',
    'Greece Garrison 1 - back.png',
    'Greece Garrison 1 - front.png',
    'Greece Infantry 2 - Full.png',
    'Greece Infantry 2 - Reduced.png',
    'Greece Prod 1s - back.png',
    'Greece Prod 1s - front.png',
    'Greece Will 1s - back.png',
    'Greece Will 1s - front.png',
    'Hidden.png',
    'HiddenCounterBack.png',
    'Hungary Garrison 1 - back.png',
    'Hungary Garrison 1 - front.png',
    'Hungary Garrison 3 - back.png',
    'Hungary Garrison 3 - front.png',
    'Hungary Infantry 2 - Full.png',
    'Hungary Infantry 2 - Reduced.png',
    'Hungary Infantry 4 - What If - Full.png',
    'Hungary Infantry 4 - What If - Reduced.png',
    'Hungary Prod 1s - back.png',
    'Hungary Prod 1s - front.png',
    'Hungary Will 1s - back.png',
    'Hungary Will 1s - front.png',
    'Iraq Garrison 1 - back.png',
    'Iraq Garrison 1 - front.png',
    'Iraq Infantry 2 - What If - Full.png',
    'Iraq Infantry 2 - What If - Reduced.png',
    'Iraq Prod 1s - back.png',
    'Iraq Prod 1s - front.png',
    'Iraq Will 1s - back.png',
    'Iraq Will 1s - front.png',
    'Ireland Garrison 2 - What If - back.png',
    'Ireland Garrison 2 - What If - front.png',
    'Ireland Infantry 1 - Full.png',
    'Ireland Infantry 1 - Reduced.png',
    'Ireland Prod 1s - back.png',
    'Ireland Prod 1s - front.png',
    'Ireland Will 1s - back.png',
    'Ireland Will 1s - front.png',
    'Italian Air 1 - front.png',
    'Italian Air 2 - What If - front.png',
    'Italian Carrier - What If - back.png',
    'Italian Convoy - back.png',
    'Italian Convoy - What If - back.png',
    'Italian Convoy 1 - front.png',
    'Italian Convoy 2 - front.png',
    'Italian Convoy 3 - What If - front.png',
    'Italian Factory Count - back.png',
    'Italian Factory Count - front.png',
    'Italian Fighter - back.png',
    'Italian Fleet 1 - front.png',
    'Italian Fleet 2 - front.png',
    'Italian Fleet CV - front.png',
    'Italian Fort Tobruk - back.png',
    'Italian Garrison 2 - back.png',
    'Italian Garrison 2 - front.png',
    'Italian Garrison 4 - back.png',
    'Italian Garrison 4 - front.png',
    'Italian Garrison 5 - back.png',
    'Italian Garrison 5 - front.png',
    'Italian Garrison 6 - back.png',
    'Italian Garrison 6 - front.png',
    'Italian Garrison 7 - back.png',
    'Italian Garrison 7 - front.png',
    'Italian Infantry 1 - Full.png',
    'Italian Infantry 1 - Reduced.png',
    'Italian Infantry 10 - Full.png',
    'Italian Infantry 10 - Reduced.png',
    'Italian Infantry 11 - Full.png',
    'Italian Infantry 11 - Reduced.png',
    'Italian Infantry 8 - Full.png',
    'Italian Infantry 8 - Reduced.png',
    'Italian Infantry 9 - Full.png',
    'Italian Infantry 9 - Reduced.png',
    'Italian Motorized Guard 1 - What If - Full.png',
    'Italian Motorized Guard 1 - What If - Reduced.png',
    'Italian Motorized Mot 1 - What If - Full.png',
    'Italian Motorized Mot 1 - What If - Reduced.png',
    'Italian Prod 10s - back.png',
    'Italian Prod 10s - front.png',
    'Italian Prod 1s - back.png',
    'Italian Prod 1s - front.png',
    'Italian Prod x2 - back.png',
    'Italian Prod x2 - front.png',
    'Italian Submarines - What If - back.png',
    'Italian Submarines - What If - front.png',
    'Italian Surface - back.png',
    'Italian Tanks - back.png',
    'Italian Tanks - front.png',
    'Italian Tanks - What If - back.png',
    'Italian Tanks - What If - front.png',
    'Italian Will 10s - back.png',
    'Italian Will 10s - front.png',
    'Italian Will 1s - back.png',
    'Italian Will 1s - front.png',
    'Latvia Garrison 1 - back.png',
    'Latvia Garrison 1 - front.png',
    'Latvia Infantry 2 - What If - Full.png',
    'Latvia Infantry 2 - What If - Reduced.png',
    'Latvia Prod 1s - back.png',
    'Latvia Prod 1s - front.png',
    'Latvia Will 1s - back.png',
    'Latvia Will 1s - front.png',
    'Lithuania Garrison 1 - back.png',
    'Lithuania Garrison 1 - front.png',
    'Lithuania Infantry 2 - What If - Full.png',
    'Lithuania Infantry 2 - What If - Reduced.png',
    'Lithuania Prod 1s - back.png',
    'Lithuania Prod 1s - front.png',
    'Lithuania Will 1s - back.png',
    'Lithuania Will 1s - front.png',
    'Low Supply.png',
    'Moscow Treaty - back.png',
    'Moscow Treaty - front.png',
    'Movement Points.png',
    'Mulberry - back.png',
    'Mulberry - front.png',
    'Netherlands Garrison Dutch - back.png',
    'Netherlands Garrison Dutch - front.png',
    'Netherlands Infantry 2 - What If - Full.png',
    'Netherlands Infantry 2 - What If - Reduced.png',
    'Netherlands Prod 1s - back.png',
    'Netherlands Prod 1s - front.png',
    'Netherlands Will 1s - back.png',
    'Netherlands Will 1s - front.png',
    'No Event.png',
    'No EZOC.png',
    'No Supply.png',
    'Norway Garrison 1 - back.png',
    'Norway Garrison 1 - front.png',
    'Norway Garrison 2 - back.png',
    'Norway Garrison 2 - front.png',
    'Norway Prod 1s - back.png',
    'Norway Prod 1s - front.png',
    'Norway Will 1s - back.png',
    'Norway Will 1s - front.png',
    'Nuclear Strike.png',
    'Poland Garrison Karpaty - back.png',
    'Poland Garrison Karpaty - front.png',
    'Poland Garrison Narew - back.png',
    'Poland Garrison Narew - front.png',
    'Poland Infantry Krakow - Full.png',
    'Poland Infantry Krakow - Reduced.png',
    'Poland Infantry Lodz - Full.png',
    'Poland Infantry Lodz - Reduced.png',
    'Poland Infantry Modlin - Full.png',
    'Poland Infantry Modlin - Reduced.png',
    'Poland Infantry Pomrz - Full.png',
    'Poland Infantry Pomrz - Reduced.png',
    'Poland Infantry Poznan - Full.png',
    'Poland Infantry Poznan - Reduced.png',
    'Poland Infantry Prusy - Full.png',
    'Poland Infantry Prusy - Reduced.png',
    'Poland Prod 1s - back.png',
    'Poland Prod 1s - front.png',
    'Poland Prod x2 - back.png',
    'Poland Prod x2 - front.png',
    'Poland Will 10s - back.png',
    'Poland Will 10s - front.png',
    'Poland Will 1s - back.png',
    'Poland Will 1s - front.png',
    'Policy Evaluation - back.png',
    'Policy Evaluation - front.png',
    'Political Failure.png',
    'Political Success.png',
    'Portugal Garrison 2 - What If - back.png',
    'Portugal Garrison 2 - What If - front.png',
    'Portugal Infantry 1 - Full.png',
    'Portugal Infantry 1 - Reduced.png',
    'Portugal Prod 1s - front.png',
    'Portugal Will 1s - back.png',
    'Portugal Will 1s - front.png',
    'Pro-Axis.png',
    'Pro-Soviet.png',
    'Pro-Western.png',
    'Romania Garrison 1 - back.png',
    'Romania Garrison 1 - front.png',
    'Romania Garrison 2 - What If - back.png',
    'Romania Garrison 2 - What If - front.png',
    'Romania Infantry 3 - Full.png',
    'Romania Infantry 3 - Reduced.png',
    'Romania Infantry 4 - Full.png',
    'Romania Infantry 4 - Reduced.png',
    'Romania Prod 1s - back.png',
    'Romania Prod 1s - front.png',
    'Romania Will 1s - back.png',
    'Romania Will 1s - front.png',
    'Scenario Ends.png',
    'Sorties 1.png',
    'Sorties 2.png',
    'Sorties 3.png',
    'Sorties 4.png',
    'Sorties 5.png',
    'Sorties 6.png',
    'Soviet Control.png',
    'Spain Air 1 - What If - back.png',
    'Spain Convoy Action - What If - back.png',
    'Spain Convoy Action - What If - front.png',
    'Spain Fighter - What If - back.png',
    'Spain Garrison 3 - back.png',
    'Spain Garrison 3 - front.png',
    'Spain Garrison 4 - back.png',
    'Spain Garrison 4 - front.png',
    'Spain Garrison 5 - back.png',
    'Spain Garrison 5 - front.png',
    'Spain Infantry 1 - Full.png',
    'Spain Infantry 1 - Reduced.png',
    'Spain Infantry 2 - Full.png',
    'Spain Infantry 2 - Reduced.png',
    'Spain Infantry 6 - What If - Full.png',
    'Spain Infantry 6 - What If - Reduced.png',
    'Spain Prod 1s - back.png',
    'Spain Prod 1s - front.png',
    'Spain Prod x2 - What If - back.png',
    'Spain Prod x2 - What If - front.png',
    'Spain Surface Action - What If - back.png',
    'Spain Surface Action - What If - front.png',
    'Spain Will 1s - back.png',
    'Spain Will 1s - front.png',
    'Strict Neutrality - What If.png',
    'Sweden Garrison 3 - back.png',
    'Sweden Garrison 3 - front.png',
    'Sweden Garrison 4 - back.png',
    'Sweden Garrison 4 - front.png',
    'Sweden Infantry 1 - Full.png',
    'Sweden Infantry 1 - Reduced.png',
    'Sweden Infantry 2 - Full.png',
    'Sweden Infantry 2 - Reduced.png',
    'Sweden Prod 1s - back.png',
    'Sweden Prod 1s - front.png',
    'Sweden Will 1s - back.png',
    'Sweden Will 1s - front.png',
    'Syria Garrison 1 - back.png',
    'Syria Garrison 1 - front.png',
    'Syria Infantry 2 - What If - Full.png',
    'Syria Infantry 2 - What If - Reduced.png',
    'Syria Prod 1s - back.png',
    'Syria Prod 1s - front.png',
    'Syria Will 1s - back.png',
    'Syria Will 1s - front.png',
    'Turkey Air 1 - What If - back.png',
    'Turkey Convoy Action - What If - back.png',
    'Turkey Convoy Action - What If - front.png',
    'Turkey Fighter - What If - back.png',
    'Turkey Garrison 4 - back.png',
    'Turkey Garrison 4 - front.png',
    'Turkey Garrison 5 - back.png',
    'Turkey Garrison 5 - front.png',
    'Turkey Garrison 6 - back.png',
    'Turkey Garrison 6 - front.png',
    'Turkey Infantry 1 - Full.png',
    'Turkey Infantry 1 - Reduced.png',
    'Turkey Infantry 2 - Full.png',
    'Turkey Infantry 2 - Reduced.png',
    'Turkey Infantry 3 - Full.png',
    'Turkey Infantry 3 - Reduced.png',
    'Turkey Prod 1s - back.png',
    'Turkey Prod 1s - front.png',
    'Turkey Prod x2 - What If - back.png',
    'Turkey Prod x2 - What If - front.png',
    'Turkey Surface Action - What If - back.png',
    'Turkey Surface Action - What If - front.png',
    'Turkey Will 1s - back.png',
    'Turkey Will 1s - front.png',
    'Turn.png',
    'UK Bomber - back.png',
    'UK Bomber Command - front.png',
    'UK Carrier - back.png',
    'UK Convoy - back.png',
    'UK Convoy 1 - front.png',
    'UK Convoy 2 - front.png',
    'UK Convoy 3 - front.png',
    'UK Convoy 4 - front.png',
    'UK Factory Count - back.png',
    'UK Factory Count - front.png',
    'UK Factory Lost - front.png',
    'UK Fighter - back.png',
    'UK Fighter - What If - back.png',
    'UK Fighter Command - front.png',
    'UK Force H - front.png',
    'UK Fort - back.png',
    'UK Fort Gibraltar - front.png',
    'UK Fort Malta - front.png',
    'UK Fort Tobruk - front.png',
    'UK Garrison 10 - back.png',
    'UK Garrison 10 - front.png',
    'UK Garrison 9 - back.png',
    'UK Garrison 9 - front.png',
    'UK Garrison Gibraltar - back.png',
    'UK Garrison Gibraltar - front.png',
    'UK Garrison Home - back.png',
    'UK Garrison Home - front.png',
    'UK Garrison Malta - back.png',
    'UK Garrison Malta - front.png',
    'UK Home Fleet - front.png',
    'UK Lend Lease - front.png',
    'UK Mediterranean Fleet - front.png',
    'UK Motorized 1 - What If - Full.png',
    'UK Motorized 1 - What If - Reduced.png',
    'UK Motorized BEF - Full.png',
    'UK Motorized BEF - Reduced.png',
    'UK Motorized WDF - Full.png',
    'UK Motorized WDF - Reduced.png',
    'UK Naval Evacuation - back.png',
    'UK Naval Evacuation - front.png',
    'UK Prod 10s - back.png',
    'UK Prod 10s - front.png',
    'UK Prod 1s - back.png',
    'UK Prod 1s - front.png',
    'UK RAF 1 - front.png',
    'UK RAF 2 - front.png',
    'UK RAF 3 - What If - front.png',
    'UK Surface - back.png',
    'UK Surprise Attack - back.png',
    'UK Surprise Attack - front.png',
    'UK Tank 1 Canada - Full.png',
    'UK Tank 1 Canada - Reduced.png',
    'UK Tank 2 - Full.png',
    'UK Tank 2 - Reduced.png',
    'UK Tank 8 - Full.png',
    'UK Tank 8 - Reduced.png',
    'UK Tanks - back.png',
    'UK Tanks - front.png',
    'UK W France Garrison - What If - back.png',
    'UK W France Garrison - What If - front.png',
    'UK Will 10s - back.png',
    'UK Will 10s - front.png',
    'UK Will 1s - back.png',
    'UK Will 1s - front.png',
    'UnitActivated.png',
    'USA AAF 12 - front.png',
    'USA AAF 15 - front.png',
    'USA AAF 8 - front.png',
    'USA AAF 9 - front.png',
    'USA Bomber - back.png',
    'USA Carrier - back.png',
    'USA Convoy - back.png',
    'USA Convoy 1 - front.png',
    'USA Convoy 2 - front.png',
    'USA Convoy 3 - front.png',
    'USA Convoy 4 - front.png',
    'USA Fighter - back.png',
    'USA Fleet 12 - front.png',
    'USA Fleet 4 - front.png',
    'USA Fleet 8 - front.png',
    'USA FTAF - front.png',
    'USA Motorized 2 - What If - Full.png',
    'USA Motorized 2 - What If - Reduced.png',
    'USA Motorized 4 - What If - Full.png',
    'USA Motorized 4 - What If - Reduced.png',
    'USA Motorized Task Force - Full.png',
    'USA Motorized Task Force - Reduced.png',
    'USA Submarines - What If - back.png',
    'USA Submarines - What If - front.png',
    'USA Surface - back.png',
    'USA Surprise Attack - back.png',
    'USA Surprise Attack - front.png',
    'USA Tank 1 - Full.png',
    'USA Tank 1 - Reduced.png',
    'USA Tank 1 French - Full.png',
    'USA Tank 1 French - Reduced.png',
    'USA Tank 15 - What If - Full.png',
    'USA Tank 15 - What If - Reduced.png',
    'USA Tank 3 - Full.png',
    'USA Tank 3 - Reduced.png',
    'USA Tank 5 - Full.png',
    'USA Tank 5 - Reduced.png',
    'USA Tank 7 - Full.png',
    'USA Tank 7 - Reduced.png',
    'USA Tank 9 - Full.png',
    'USA Tank 9 - Reduced.png',
    'USA Tanks - back.png',
    'USA Tanks - front.png',
    'USA Tanks - What If - back.png',
    'USA Tanks - What If - front.png',
    'USA Variable Arrival - back.png',
    'USA Variable Arrival - front.png',
    'USA Will 10s - back.png',
    'USA Will 10s - front.png',
    'USA Will 1s - back.png',
    'USA Will 1s - front.png',
    'USSR Airdrop - What If - back.png',
    'USSR Airdrop - What If - Front.png',
    'USSR Bomber - What If - back.png',
    'USSR Bomber Air - What If -  front.png',
    'USSR Ceded Area - back.png',
    'USSR Ceded Area Bessarabia - front.png',
    'USSR Ceded Area Eastern Poland - front.png',
    'USSR Ceded Area Estonia - front.png',
    'USSR Ceded Area Karelia - front.png',
    'USSR Ceded Area Latvia - front.png',
    'USSR Ceded Area Lithuania - front.png',
    'USSR Convoy - back.png',
    'USSR Convoy 1 - front.png',
    'USSR Convoy 2 - What If - front.png',
    'USSR Factory Count - back.png',
    'USSR Factory Count - front.png',
    'USSR Factory Lost - front.png',
    'USSR Fighter - back.png',
    'USSR Fighter 1 Air - front.png',
    'USSR Fighter 2 Air - front.png',
    'USSR Fighter 3 Air - front.png',
    'USSR Fighter 4 Air - front.png',
    'USSR Fighter 5 Air - front.png',
    'USSR Fleet 1 - What If - front.png',
    'USSR Fort - back.png',
    'USSR Fort Leningrad - front.png',
    'USSR Fort Moscow - front.png',
    'USSR Fort Sevastopol - front.png',
    'USSR Ground Support - back.png',
    'USSR Ground Support - front.png',
    'USSR Ground Support - What If - back.png',
    'USSR Ground Support - What If - front.png',
    'USSR Guard 1 - Full.png',
    'USSR Guard 1 - Reduced.png',
    'USSR Guard 10 - Full.png',
    'USSR Guard 10 - Reduced.png',
    'USSR Guard 11 - Full.png',
    'USSR Guard 11 - Reduced.png',
    'USSR Guard 2 - Full.png',
    'USSR Guard 2 - Reduced.png',
    'USSR Guard 3 - Full.png',
    'USSR Guard 3 - Reduced.png',
    'USSR Guard 4 - Full.png',
    'USSR Guard 4 - Reduced.png',
    'USSR Guard 5 - Full.png',
    'USSR Guard 5 - Reduced.png',
    'USSR Guard 6 - Full.png',
    'USSR Guard 6 - Reduced.png',
    'USSR Guard 7 - Full.png',
    'USSR Guard 7 - Reduced.png',
    'USSR Guard 8 - Full.png',
    'USSR Guard 8 - Reduced.png',
    'USSR Guard 9 - Full.png',
    'USSR Guard 9 - Reduced.png',
    'USSR Guard Tank 1 - Full.png',
    'USSR Guard Tank 1 - Reduced.png',
    'USSR Guard Tank 2 - Full.png',
    'USSR Guard Tank 2 - Reduced.png',
    'USSR Guard Tank 3 - Full.png',
    'USSR Guard Tank 3 - Reduced.png',
    'USSR Guard Tank 4 - Full.png',
    'USSR Guard Tank 4 - Reduced.png',
    'USSR Guard Tank 5 - Full.png',
    'USSR Guard Tank 5 - Reduced.png',
    'USSR Guard Tank 6 - Full.png',
    'USSR Guard Tank 6 - Reduced.png',
    'USSR Heavy Artillery - back.png',
    'USSR Heavy Artillery - front.png',
    'USSR Infantry 10 - Fill.png',
    'USSR Infantry 10 - Reduced.png',
    'USSR Infantry 11 - Full.png',
    'USSR Infantry 11 - Reduced.png',
    'USSR Infantry 12 - Fall.png',
    'USSR Infantry 12 - Reduced.png',
    'USSR Infantry 13 - Full.png',
    'USSR Infantry 13 - Reduced.png',
    'USSR Infantry 14 - Full.png',
    'USSR Infantry 14 - Reduced.png',
    'USSR Infantry 16 - Full.png',
    'USSR Infantry 16 - Reduced.png',
    'USSR Infantry 21 - Full.png',
    'USSR Infantry 21 - Reduced.png',
    'USSR Infantry 22 - Full.png',
    'USSR Infantry 22 - Reduced.png',
    'USSR Infantry 23 - Full.png',
    'USSR Infantry 23 - Reduced.png',
    'USSR Infantry 26 - Full.png',
    'USSR Infantry 26 - Reduced.png',
    'USSR Infantry 27 - Full.png',
    'USSR Infantry 27 - Reduced.png',
    'USSR Infantry 3 - Full.png',
    'USSR Infantry 3 - Reduced.png',
    'USSR Infantry 30 - Full.png',
    'USSR Infantry 30 - Reduced.png',
    'USSR Infantry 33 - Full.png',
    'USSR Infantry 33 - Reduced.png',
    'USSR Infantry 37 - Full.png',
    'USSR Infantry 37 - Reduced.png',
    'USSR Infantry 38 - Full.png',
    'USSR Infantry 38 - Reduced.png',
    'USSR Infantry 4 - Full.png',
    'USSR Infantry 4 - Reduced.png',
    'USSR Infantry 44 - Full.png',
    'USSR Infantry 44 - Reduced.png',
    'USSR Infantry 45 - Full.png',
    'USSR Infantry 45 - Reduced.png',
    'USSR Infantry 46 - Full.png',
    'USSR Infantry 46 - Reduced.png',
    'USSR Infantry 5 - Full.png',
    'USSR Infantry 5 - Reduced.png',
    'USSR Infantry 50 - Full.png',
    'USSR Infantry 50 - Reduced.png',
    'USSR Infantry 51 - Full.png',
    'USSR Infantry 51 - Reduced.png',
    'USSR Infantry 6 - Full.png',
    'USSR Infantry 6 - Reduced.png',
    'USSR Infantry 62 - Full.png',
    'USSR Infantry 62 - Reduced.png',
    'USSR Infantry 7 - Full.png',
    'USSR Infantry 7 - Reduced.png',
    'USSR Infantry 8 - Full.png',
    'USSR Infantry 8 - Reduced.png',
    'USSR Infantry 9 - Full.png',
    'USSR Infantry 9 - Reduced.png',
    'USSR Lend Lease - front.png',
    'USSR Partisans - back.png',
    'USSR Partisans - front.png',
    'USSR Prod 10s - back.png',
    'USSR Prod 10s - front.png',
    'USSR Prod 1s - back.png',
    'USSR Prod 1s - front.png',
    'USSR Russian Winter - back.png',
    'USSR Russian Winter - front.png',
    'USSR Shock 1 - Full.png',
    'USSR Shock 1 - Reduced.png',
    'USSR Shock 2 - Full.png',
    'USSR Shock 2 - Reduced.png',
    'USSR Shock 3 - Full.png',
    'USSR Shock 3 - Reduced.png',
    'USSR Shock 4 - Full.png',
    'USSR Shock 4 - Reduced.png',
    'USSR Shock 5 - Full.png',
    'USSR Shock 5 - Reduced.png',
    'USSR SNAFU - What If - back.png',
    'USSR SNAFU - What If - front.png',
    'USSR Strategic Move - back.png',
    'USSR Strategic Move - front.png',
    'USSR Strategic Move - What If - back.png',
    'USSR Strategic Move - What If - front.png',
    'USSR Submarines - What If - back.png',
    'USSR Submarines - What If - front.png',
    'USSR Surface - What If - back.png',
    'USSR Surface Action - back.png',
    'USSR Surface Action - front.png',
    'USSR Surprise Attack - back.png',
    'USSR Surprise Attack - front.png',
    'USSR Tank 1 - Full.png',
    'USSR Tank 1 - Reduced.png',
    'USSR Tank 2 - Full.png',
    'USSR Tank 2 - Reduced.png',
    'USSR Tank 3 - Full.png',
    'USSR Tank 3 - Reduced.png',
    'USSR Tank 4 - Full.png',
    'USSR Tank 4 - Reduced.png',
    'USSR Tank 5 - Full.png',
    'USSR Tank 5 - Reduced.png',
    'USSR Tank 6 - Full.png',
    'USSR Tank 6 - Reduced.png',
    'USSR Tanks - back.png',
    'USSR Tanks - front.png',
    'USSR Urals Factory - front.png',
    'USSR Will 10s - back.png',
    'USSR Will 10s - front.png',
    'USSR Will 1s - back.png',
    'USSR Will 1s - front.png',
    'Variable Entry.png',
    'Vichy Convoy Action - What If - back.png',
    'Vichy Convoy Action - What If - front.png',
    'Vichy Garrison 3 - back.png',
    'Vichy Garrison 3 - front.png',
    'Vichy Garrison 4 - back.png',
    'Vichy Garrison 4 - front.png',
    'Vichy Infantry 1 - Full.png',
    'Vichy Infantry 1 - Reduced.png',
    'Vichy Infantry 2 - Full.png',
    'Vichy Infantry 2 - Reduced.png',
    'Vichy Prod 1s - front.png',
    'Vichy Surface Action - front.png',
    'Vichy Surface Action - What If - back.png',
    'Weather.png',
    'Western Control.png',
    'Western Free Forces - back.png',
    'Western Free Forces - front.png',
    'Western Ground Support - back.png',
    'Western Ground Support - front.png',
    'Western Ground Support - What If - back.png',
    'Western Ground Support - What If - front.png',
    'Western Mulberry - back.png',
    'Western Mulberry - front.png',
    'Western Partisans - back.png',
    'Western Partisans - front.png',
    'Western SNAFU - What If - back.png',
    'Western SNAFU - What If - front.png',
    'Western Strategic Move - back.png',
    'Western Strategic Move - front.png',
    'Western Strategic Move - What If - back.png',
    'Western Strategic Move - What If - front.png',
    'Western Ultra - back.png',
    'Western Ultra - front.png',
    'Will Commit.png',
    'Will Not Commit.png',
    'Yugoslavia Garrison 3 - back.png',
    'Yugoslavia Garrison 3 - front.png',
    'Yugoslavia Garrison 4 - back.png',
    'Yugoslavia Garrison 4 - front.png',
    'Yugoslavia Garrison 5 - back.png',
    'Yugoslavia Garrison 5 - front.png',
    'Yugoslavia Garrison 6 - back.png',
    'Yugoslavia Garrison 6 - front.png',
    'Yugoslavia Infantry 1 - Full.png',
    'Yugoslavia Infantry 1 - Reduced.png',
    'Yugoslavia Infantry 2 - Full.png',
    'Yugoslavia Infantry 2 - Reduced.png',
    'Yugoslavia Prod 1s - back.png',
    'Yugoslavia Prod 1s - front.png',
    'Yugoslavia Will 1s - back.png',
    'Yugoslavia Will 1s - front.png',];