var component_list = [
    [
        "Belgic",
        ["be-10div", {"b": "BE-10Div-Bk.png", "f": "BE-10Div.png"}],
        ["be-11div", {"b": "BE-11Div-Bk.png", "f": "BE-11Div.png"}],
        ["be-12div", {"b": "BE-12Div-Bk.png", "f": "BE-12Div.png"}],
        ["be-13div", {"b": "BE-13Div-Bk.png", "f": "BE-13Div.png"}],
        ["be-14div", {"b": "BE-14Div-Bk.png", "f": "BE-14Div.png"}],
        ["be-15div", {"b": "BE-15Div-Bk.png", "f": "BE-15Div.png"}],
        ["be-16div", {"b": "BE-16Div-Bk.png", "f": "BE-16Div.png"}],
        ["be-17div", {"b": "BE-17Div-Bk.png", "f": "BE-17Div.png"}],
        ["be-18div", {"b": "BE-18Div-Bk.png", "f": "BE-18Div.png"}],
        ["be-1cav", {"b": "BE-1Cav-Bk.png", "f": "BE-1Cav.png"}],
        ["be-1div", {"b": "BE-1Div-Bk.png", "f": "BE-1Div.png"}],
        ["be-2cav", {"b": "BE-2Cav-Bk.png", "f": "BE-2Cav.png"}],
        ["be-2div", {"b": "BE-2Div-Bk.png", "f": "BE-2Div.png"}],
        ["be-3div", {"b": "BE-3Div-Bk.png", "f": "BE-3Div.png"}],
        ["be-4div", {"b": "BE-4Div-Bk.png", "f": "BE-4Div.png"}],
        ["be-5div", {"b": "BE-5Div-Bk.png", "f": "BE-5Div.png"}],
        ["be-6div", {"b": "BE-6Div-Bk.png", "f": "BE-6Div.png"}],
        ["be-8div", {"b": "BE-8Div-B.png", "f": "BE-8Div.png"}],
        ["be-9div", {"b": "BE-9Div-Bk.png", "f": "BE-9Div.png"}],
        ["be-chasar", {"b": "BE-ChasAr-B.png", "f": "BE-ChasAr-F.png"}],
        ["be-fort", {"b": "BE-Fort-B.png", "f": "BE-Fort-F.png"}],
    ],
    [
        "British",
        ["br-12div", {"b": "BR-12Div-Bk.png", "f": "BR-12Div.png"}],
        ["br-12l-recon", {"f": "BR-12L-recon.png"}],
        ["br-1div", {"b": "BR-1DIV-Bk.png", "f": "BR-1Div.png"}],
        ["br-1sttank", {"b": "BR-1stTank-Bk.png", "f": "BR-1stTank.png"}],
        ["br-20g-bde", {"b": "BR-20G-Bde-Bk.png", "f": "BR-20G-Bde.png"}],
        ["br-23div", {"b": "BR-23Div-Bk.png", "f": "BR-23Div.png"}],
        ["br-25bde", {"b": "BR-25Bde-Bk.png", "f": "BR-25Bde.png"}],
        ["br-2div", {"b": "BR-2DIV-Bk.png", "f": "BR-2Div.png"}],
        ["br-30bde", {"b": "BR-30Bde-Bk.png", "f": "BR-30Bde.png"}],
        ["br-3div", {"b": "BR-3Div-Bk.png", "f": "BR-3Div.png"}],
        ["br-42div", {"b": "BR-42Div-Bk.png", "f": "BR-42Div.png"}],
        ["br-44div", {"b": "BR-44Div-Bk.png", "f": "BR-44Div.png"}],
        ["br-46div", {"b": "BR-46Div-Bk.png", "f": "BR-46Div.png"}],
        ["br-48div", {"b": "BR-48Div-Bk.png", "f": "BR-48Div.png"}],
        ["br-4div", {"b": "BR-4Div-Bk.png", "f": "BR-4Div.png"}],
        ["br-50div", {"b": "BR-50Div-Bk.png", "f": "BR-50Div.png"}],
        ["br-5div", {"b": "BR-5Div-Bk.png", "f": "BR-5Div.png"}],
        ["br-gpmac", {"b": "BR-GpMac-Bk.png", "f": "BR-GpMac.png"}],
        ["br-gpwood", {"b": "BR-GpWood-Bk.png", "f": "BR-GpWood.png"}],
        ["br-hq-bef", {"b": "BR-HQ-BEF-Bk.png", "f": "BR-HQ-BEF.png"}],
        ["br-raf", {"b": "BR-RAF-Bk.png", "f": "BR-RAF.png"}],
        ["br-rem-0-0-3", {"f": "BR-REM-0-0-3.png"}],
        ["br-rem-inf", {"f": "BR-REM-INF.png"}],
    ],
    [
        "French",
        ["fr-101-84", {"b": "FR-101-84-Bk.png", "f": "FR-101-84.png"}],
        ["fr-101-87", {"b": "FR-101-87-Bk.png", "f": "FR-101-87.png"}],
        ["fr-102-148", {"b": "FR-102-148-Bk.png", "f": "FR-102-148.png"}],
        ["fr-102-42", {"b": "FR-102-42-Bk.png", "f": "FR-102-42.png"}],
        ["fr-10div", {"b": "FR-10Div-Bk.png", "f": "FR-10Div.png"}],
        ["fr-11div", {"b": "FR-11Div-Bk.png", "f": "FR-11Div.png"}],
        ["fr-12div", {"b": "FR-12Div-Bk.png", "f": "FR-12DIV.png"}],
        ["fr-13div", {"b": "FR-13Div-Bk.png", "f": "FR-13DIV.png"}],
        ["fr-14div", {"b": "FR-14Div-Bk.png", "f": "FR-14DIV.png"}],
        ["fr-15div", {"b": "FR-15Div-Bk.png", "f": "FR-15Div.png"}],
        ["fr-18div", {"b": "FR-18Div-Bk.png", "f": "FR-18Div.png"}],
        ["fr-19div", {"b": "FR-19Div-Bk.png", "f": "FR-19DIV.png"}],
        ["fr-1cav", {"b": "FR-1Cav-Bk.png", "f": "FR-1Cav.png"}],
        ["fr-1cav bgd", {"f": "FR-1Cav Bgd.png"}],
        ["fr-1dcr", {"b": "FR-1DCR-Bk.png", "f": "FR-1DCR.png"}],
        ["fr-1div", {"b": "FR-1Div-Bk.png", "f": "FR-1DIV.png"}],
        ["fr-1dlm", {"b": "FR-1DLM-Bk.png", "f": "FR-1DLM.png"}],
        ["fr-1mor", {"b": "FR-1Mor-Bk.png", "f": "FR-1Mor.png"}],
        ["fr-1na", {"b": "FR-1NA-Bk.png", "f": "FR-1NA.png"}],
        ["fr-21div", {"b": "FR-21Div-Bk.png", "f": "FR-21DIV.png"}],
        ["fr-22div", {"b": "FR-22DIV-BK.png", "f": "FR-22DIV.png"}],
        ["fr-23div", {"b": "FR-23Div-Bk.png", "f": "FR-23DIV.png"}],
        ["fr-24div", {"b": "FR-24DIV-Bk.png", "f": "FR-24DIV.png"}],
        ["fr-25div", {"b": "FR-25Div-Bk.png", "f": "FR-25DIV.png"}],
        ["fr-27div", {"b": "FR-27Div-Bk.png", "f": "FR-27DIV.png"}],
        ["fr-27recon", {"f": "FR-27Recon.png"}],
        ["fr-28div", {"b": "FR-28Div-Bk.png", "f": "FR-28DIV.png"}],
        ["fr-29div", {"b": "FR-29Div-Bk.png", "f": "FR-29DIV.png"}],
        ["fr-2cav", {"b": "FR-2Cav-Bk.png", "f": "FR-2Cav.png"}],
        ["fr-2dcr", {"b": "FR-2DCR-Bk.png", "f": "FR-2DCR.png"}],
        ["fr-2dlm", {"b": "FR-2DLM-Bk.png", "f": "FR-2DLM.png"}],
        ["fr-2na", {"b": "FR-2NA-Bk.png", "f": "FR-2NA.png"}],
        ["fr-32div", {"b": "FR-32Div-Bk.png", "f": "FR-32DIV.png"}],
        ["fr-34recon", {"f": "FR-34Recon.png"}],
        ["fr-36div", {"b": "FR-36Div-Bk.png", "f": "FR-36DIV.png"}],
        ["fr-3cav", {"b": "FR-3Cav-Bk.png", "f": "FR-3Cav.png"}],
        ["fr-3dcr", {"b": "FR-3DCR-Bk.png", "f": "FR-3DCR.png"}],
        ["fr-3div", {"b": "FR-3Div-Bk.png", "f": "FR-3DIV.png"}],
        ["fr-3dli", {"b": "FR-3DLI-Bk.png", "f": "FR-3DLI.png"}],
        ["fr-3dlm", {"b": "FR-3DLM-Bk.png", "f": "FR-3DLM.png"}],
        ["fr-3na", {"b": "FR-3NA-Bk.png", "f": "FR-3NA.png"}],
        ["fr-3spahis", {"f": "FR-3Spahis.png"}],
        ["fr-42div", {"b": "FR-42Div-Bk.png", "f": "FR-42DIV.png"}],
        ["fr-43div", {"b": "FR-43Div-Bk.png", "f": "FR-43DIV.png"}],
        ["fr-44div", {"b": "FR-44Div-Bk.png", "f": "FR-44DIV.png"}],
        ["fr-45div", {"b": "FR-45Div-Bk.png", "f": "FR-45DIV.png"}],
        ["fr-4cav", {"b": "FR-4Cav-Bk.png", "f": "FR-4Cav.png"}],
        ["fr-4dcr", {"b": "FR-4DCR-Bk.png", "f": "FR-4DCR.png"}],
        ["fr-4div", {"b": "FR-4Div-Bk.png", "f": "FR-4DIV.png"}],
        ["fr-4na", {"b": "FR-4NA-Bk.png", "f": "FR-4NA.png"}],
        ["fr-53div", {"b": "FR-53Div-Bk.png", "f": "FR-53Div.png"}],
        ["fr-55div", {"b": "FR-55Div-Bk.png", "f": "FR-55Div.png"}],
        ["fr-5cav", {"b": "FR-5Cav-Bk.png", "f": "FR-5Cav.png"}],
        ["fr-5div", {"b": "FR-5Div-Bk.png", "f": "FR-5DIV.png"}],
        ["fr-5na", {"b": "FR-5NA-Bk.png", "f": "FR-5NA.png"}],
        ["fr-60div", {"b": "FR-60Div-Bk.png", "f": "FR-60Div.png"}],
        ["fr-61div", {"b": "FR-61Div-Bk.png", "f": "FR-61Div.png"}],
        ["fr-68div", {"b": "FR-68Div-Bk.png", "f": "FR-68Div.png"}],
        ["fr-71div", {"b": "FR-71Div-Bk.png", "f": "FR-71Div.png"}],
        ["fr-74recon", {"f": "FR-74Recon.png"}],
        ["fr-75recon", {"f": "FR-75Recon.png"}],
        ["fr-7div", {"b": "FR-7Div-Bk.png", "f": "FR-7DIV.png"}],
        ["fr-7na", {"b": "FR-7NA-Bk.png", "f": "FR-7NA.png"}],
        ["fr-87afr", {"b": "FR-87Afr-Bk.png", "f": "FR-87Afr.png"}],
        ["fr-8div", {"b": "FR-8Div-Bk.png", "f": "FR-8DIV.png"}],
        ["fr-9div", {"b": "FR-9Div-Bk.png", "f": "FR-9DIV.png"}],
        ["fr-col-1div", {"b": "FR-Col-1Div-Bk.png", "f": "FR-Col-1Div.png"}],
        ["fr-col-3div", {"b": "FR-Col-3Div-Bk.png", "f": "FR-Col-3Div.png"}],
        ["fr-col-5div", {"b": "FR-Col-5Div-Bk.png", "f": "FR-Col-5Div.png"}],
        ["fr-col-7div", {"b": "FR-Col-7Div-Bk.png", "f": "FR-Col-7Div.png"}],
        ["fr-hq-1a", {"b": "FR-HQ-1A-Bk.png", "f": "FR-HQ-1A.png"}],
        ["fr-hq-2a", {"b": "FR-HQ-2A-Bk.png", "f": "FR-HQ-2A.png"}],
        ["fr-hq-6a", {"b": "FR-HQ-6A-Bk.png", "f": "FR-HQ-6A.png"}],
        ["fr-hq-9a", {"b": "FR-HQ-9A-Bk.png", "f": "FR-HQ-9A.png"}],
        ["fr-rem-cav", {"f": "FR-REM-CAV.png"}],
        ["fr-rem-dlm", {"f": "FR-REM-DLM.png"}],
        ["fr-rem-inf", {"f": "FR-REM-INF.png"}],
        ["fr-sfe", {"b": "FR-SFE-Bk.png", "f": "FR-SFE.png"}],
        ["fr-sff", {"b": "FR-SFF-Bk.png", "f": "FR-SFF.png"}],
        ["fr-sfm", {"b": "FR-SFM-Bk.png"}],
        ["fr-sfma", {"f": "FR-SFMa.png"}],
        ["fr-sfmb", {"f": "FR-SFMb.png"}],
        ["fr-tardu", {"f": "FR-Tardu.png"}],
        ["fr-tkbn-13", {"f": "FR-TkBn-13.png"}],
        ["fr-tkbn-17", {"f": "FR-TkBn-17.png"}],
        ["fr-tkbn-2", {"f": "FR-TkBn-2.png"}],
        ["fr-tkbn-22", {"f": "FR-TkBn-22.png"}],
        ["fr-tkbn-24", {"f": "FR-TkBn-24.png"}],
        ["fr-tkbn-3", {"f": "FR-TkBn-3.png"}],
        ["fr-tkbn-32", {"f": "FR-TkBn-32.png"}],
        ["fr-tkbn-34", {"f": "FR-TkBn-34.png"}],
        ["fr-tkbn-35", {"f": "FR-TkBn-35.png"}],
        ["fr-tkbn-38", {"f": "FR-TkBn-38.png"}],
        ["fr-tkbn-39", {"f": "FR-TkBn-39.png"}],
        ["fr-tkbn-4", {"f": "FR-TkBn-4.png"}],
        ["fr-tkbn-6", {"f": "FR-TkBn-6.png"}],
        ["fr-tkbn-7", {"f": "FR-TkBn-7.png"}],
        ["fr-tkbn-9", {"f": "FR-TkBn-9.png"}],
    ],
    [
        "Germans",
        ["ge-1", {"b": "GE-1-Bk.png", "f": "GE-1.png"}],
        ["ge-10", {"b": "GE-10-Bk.png", "f": "GE-10.png"}],
        ["ge-11", {"b": "GE-11-Bk.png", "f": "GE-11.png"}],
        ["ge-11sch", {"b": "GE-11Sch-B.png", "f": "GE-11Sch-F.png"}],
        ["ge-12", {"b": "GE-12-Bk.png", "f": "GE-12.png"}],
        ["ge-13m-66", {"b": "GE-13M-66-Bk.png", "f": "GE-13M-66.png"}],
        ["ge-13m-93", {"b": "GE-13M-93-Bk.png", "f": "GE-13M-93.png"}],
        ["ge-14", {"b": "GE-14-Bk.png", "f": "GE-14.png"}],
        ["ge-16", {"b": "GE-16-Bk.png", "f": "GE-16.png"}],
        ["ge-169", {"b": "GE-169-Bk.png", "f": "GE-169.png"}],
        ["ge-18", {"b": "GE-18-Bk.png", "f": "GE-18.png"}],
        ["ge-19", {"b": "GE-19-Bk.png", "f": "GE-19.png"}],
        ["ge-1geb", {"b": "GE-1Geb-B.png", "f": "GE-1Geb-F.png"}],
        ["ge-205", {"b": "GE-205-Bk.png", "f": "GE-205.png"}],
        ["ge-208", {"b": "GE-208-BK.png", "f": "GE-208.png"}],
        ["ge-20m-76", {"b": "GE-20M-76-Bk.png", "f": "GE-20M-76.png"}],
        ["ge-20m-90", {"b": "GE-20M-90-Bk.png", "f": "GE-20M-90.png"}],
        ["ge-21", {"b": "GE-21-Bk.png", "f": "GE-21.png"}],
        ["ge-211", {"b": "GE-211-Bk.png", "f": "GE-211.png"}],
        ["ge-216", {"b": "GE-216-BK.png", "f": "GE-216.png"}],
        ["ge-217", {"b": "GE-217-Bk.png", "f": "GE-217.png"}],
        ["ge-223", {"b": "GE-223-Bk.png", "f": "GE-223.png"}],
        ["ge-225", {"b": "GE-225-Bk.png", "f": "GE-225.png"}],
        ["ge-227", {"b": "GE-227-Bk.png", "f": "GE-227.png"}],
        ["ge-23", {"b": "GE-23-Bk.png", "f": "GE-23.png"}],
        ["ge-24", {"b": "GE-24-Bk.png", "f": "GE-24.png"}],
        ["ge-25", {"b": "GE-25-Bk.png", "f": "GE-25.png"}],
        ["ge-251", {"b": "GE-251-Bk.png", "f": "GE-251.png"}],
        ["ge-253", {"b": "GE-253-Bk.png", "f": "GE-253.png"}],
        ["ge-254", {"b": "GE-254-Bk.png", "f": "GE-254.png"}],
        ["ge-254-opt", {"f": "GE-254-OPT.png"}],
        ["ge-255", {"b": "GE-255-BK.png", "f": "GE-255.png"}],
        ["ge-256", {"b": "GE-256-BK.png", "f": "GE-256.png"}],
        ["ge-26", {"b": "GE-26-Bk.png", "f": "GE-26.png"}],
        ["ge-263", {"b": "GE-263-Bk.png", "f": "GE-263.png"}],
        ["ge-267", {"b": "GE-267-Bk.png", "f": "GE-267.png"}],
        ["ge-269", {"b": "GE-269-Bk.png", "f": "GE-269.png"}],
        ["ge-27", {"b": "GE-27-Bk.png", "f": "GE-27.png"}],
        ["ge-28", {"b": "GE-28-Bk.png", "f": "GE-28.png"}],
        ["ge-290", {"b": "GE-290-Bk.png", "f": "GE-290.png"}],
        ["ge-292", {"b": "GE-292-Bk.png", "f": "GE-292.png"}],
        ["ge-293", {"b": "GE-293-Bk.png", "f": "GE-293.png"}],
        ["ge-294", {"b": "GE-294-Bk.png", "f": "GE-294.png"}],
        ["ge-295", {"b": "GE-295-Bk.png", "f": "GE-295.png"}],
        ["ge-29m-15", {"b": "GE-29M-15-Bk.png", "f": "GE-29M-15.png"}],
        ["ge-29m-71", {"b": "GE-29M-71-Bk.png", "f": "GE-29M-71.png"}],
        ["ge-2m-25", {"b": "GE-2M-25-Bk.png", "f": "GE-2M-25.png"}],
        ["ge-2m-5", {"b": "GE-2M-5-Bk.png", "f": "GE-2M-5.png"}],
        ["ge-3", {"b": "GE-3-Bk.png", "f": "GE-3.png"}],
        ["ge-30", {"b": "GE-30-Bk.png", "f": "GE-30.png"}],
        ["ge-31", {"b": "GE-31-Bk.png", "f": "GE-31.png"}],
        ["ge-32", {"b": "GE-32-Bk.png", "f": "GE-32.png"}],
        ["ge-33", {"b": "GE-33-Bk.png", "f": "GE-33.png"}],
        ["ge-35", {"b": "GE-35-Bk.png", "f": "GE-35.png"}],
        ["ge-36", {"b": "GE-36-Bk.png", "f": "GE-36.png"}],
        ["ge-4", {"b": "GE-4-Bk.png", "f": "GE-4.png"}],
        ["ge-44", {"b": "GE-44-Bk.png", "f": "GE-44.png"}],
        ["ge-45", {"b": "GE-45-Bk.png", "f": "GE-45.png"}],
        ["ge-46", {"b": "GE-46-Bk.png", "f": "GE-46.png"}],
        ["ge-5", {"b": "GE-5-Bk.png", "f": "GE-5.png"}],
        ["ge-50", {"b": "GE-50-Bk.png", "f": "GE-50.png"}],
        ["ge-56", {"b": "GE-56-Bk.png", "f": "GE-56.png"}],
        ["ge-57", {"b": "GE-57-Bk.png", "f": "GE-57.png"}],
        ["ge-58", {"b": "GE-58-Bk.png", "f": "GE-58.png"}],
        ["ge-6", {"b": "GE-6-Bk.png", "f": "GE-6.png"}],
        ["ge-61", {"b": "GE-61-Bk.png", "f": "GE-61.png"}],
        ["ge-62", {"b": "GE-62-Bk.png", "f": "GE-62.png"}],
        ["ge-68", {"b": "GE-68-Bk.png", "f": "GE-68.png"}],
        ["ge-7", {"b": "GE-7-Bk.png", "f": "GE-7.png"}],
        ["ge-71", {"b": "GE-71-Bk.png", "f": "GE-71.png"}],
        ["ge-72", {"b": "GE-72-Bk.png", "f": "GE-72.png"}],
        ["ge-8", {"b": "GE-8-Bk.png", "f": "GE-8.png"}],
        ["ge-81", {"b": "GE-81-Bk.png", "f": "GE-81.png"}],
        ["ge-82", {"b": "GE-82-Bk.png", "f": "GE-82.png"}],
        ["ge-83", {"b": "GE-83-Bk.png", "f": "GE-83.png"}],
        ["ge-86", {"b": "GE-86-Bk.png", "f": "GE-86.png"}],
        ["ge-87", {"b": "GE-87-Bk.png", "f": "GE-87.png"}],
        ["ge-9", {"b": "GE-9-Bk.png", "f": "GE-9.png"}],
        ["ge-94", {"b": "GE-94-Bk.png", "f": "GE-94.png"}],
        ["ge-96", {"b": "GE-96-Bk.png", "f": "GE-96.png"}],
        ["ge-gd", {"b": "GE-GD-B.png", "f": "GE-GD-F.png"}],
        ["ge-pz1-1", {"b": "GE-Pz1-1-BK.png", "f": "GE-Pz1-1.png"}],
        ["ge-pz1-1k", {"b": "GE-Pz1-1K-BK.png", "f": "GE-Pz1-1K.png"}],
        ["ge-pz1-1t", {"b": "GE-Pz1-1T-BK.png", "f": "GE-Pz1-1T.png"}],
        ["ge-pz10-4t", {"b": "GE-Pz10-4T-Bk.png", "f": "GE-Pz10-4T.png"}],
        ["ge-pz10-69", {"b": "GE-Pz10-69-Bk.png", "f": "GE-Pz10-69.png"}],
        ["ge-pz10-86", {"b": "GE-Pz10-86-Bk.png", "f": "GE-Pz10-86.png"}],
        ["ge-pz2-2", {"b": "GE-Pz2-2-BK.png", "f": "GE-Pz2-2.png"}],
        ["ge-pz2-2k", {"b": "GE-Pz2-2K-BK.png", "f": "GE-Pz2-2K.png"}],
        ["ge-pz2-2t", {"b": "GE-Pz2-2T-BK.png", "f": "GE-Pz2-2T.png"}],
        ["ge-pz3-3", {"b": "GE-Pz3-3-Bk.png", "f": "GE-Pz3-3.png"}],
        ["ge-pz3-3k", {"b": "GE-Pz3-3K-Bk.png", "f": "GE-Pz3-3K.png"}],
        ["ge-pz3-3t", {"b": "GE-Pz3-3T-Bk.png", "f": "GE-Pz3-3T.png"}],
        ["ge-pz4-12", {"b": "GE-Pz4-12-Bk.png", "f": "GE-Pz4-12.png"}],
        ["ge-pz4-33", {"b": "GE-Pz4-33-Bk.png", "f": "GE-Pz4-33.png"}],
        ["ge-pz4-5t", {"b": "GE-Pz4-5T-Bk.png", "f": "GE-Pz4-5T.png"}],
        ["ge-pz5-13", {"b": "GE-Pz5-13-Bk.png", "f": "GE-Pz5-13.png"}],
        ["ge-pz5-14", {"b": "GE-Pz5-14-Bk.png", "f": "GE-Pz5-14.png"}],
        ["ge-pz5-8t", {"b": "GE-Pz5-8T-Bk.png", "f": "GE-Pz5-8T.png"}],
        ["ge-pz6-11t", {"b": "GE-Pz6-11T-Bk.png", "f": "GE-Pz6-11T.png"}],
        ["ge-pz6-4", {"b": "GE-Pz6-4-Bk.png", "f": "GE-Pz6-4.png"}],
        ["ge-pz6-6k", {"b": "GE-Pz6-6K-Bk.png", "f": "GE-Pz6-6K.png"}],
        ["ge-pz7-25t", {"b": "GE-Pz7-25T-Bk.png", "f": "GE-Pz7-25T.png"}],
        ["ge-pz7-6", {"b": "GE-Pz7-6-Bk.png", "f": "GE-Pz7-6.png"}],
        ["ge-pz7-7", {"b": "GE-Pz7-7-Bk.png", "f": "GE-Pz7-7.png"}],
        ["ge-pz8-10t", {"b": "GE-Pz8-10T-Bk.png", "f": "GE-Pz8-10T.png"}],
        ["ge-pz8-8", {"b": "GE-Pz8-8-Bk.png", "f": "GE-Pz8-8.png"}],
        ["ge-pz8-8k", {"b": "GE-Pz8-8K-Bk.png", "f": "GE-Pz8-8K.png"}],
        ["ge-pz9-10", {"b": "GE-Pz9-10-Bk.png", "f": "GE-Pz9-10.png"}],
        ["ge-pz9-11", {"b": "GE-Pz9-11-Bk.png", "f": "GE-Pz9-11.png"}],
        ["ge-pz9-33t", {"b": "GE-Pz9-33T-Bk.png", "f": "GE-Pz9-33T.png"}],
        ["ge-rem-generic", {"f": "GE-REM-GENERIC.png"}],
        ["ge-sslah", {"b": "GE-SSLAH-B.png", "f": "GE-SSLAH.png"}],
        ["ge-sspol", {"b": "GE-SSPol-B.png", "f": "GE-SSPOL.png"}],
        ["ge-ssrem", {"b": "GE-SSREM-B.png"}],
        ["ge-ssrem-a", {"f": "GE-SSREM-A.png"}],
        ["ge-sstot", {"b": "GE-SSTot-B.png", "f": "GE-SSTot.png"}],
        ["ge-ssverf", {"b": "GE-SSVerf-B.png", "f": "GE-SSVerf.png"}],
    ],
    [
        "Misc",
        ["m-autods", {"f": "m-AutoDS.png"}],
        ["m-control-allied", {"f": "m-CONTROL-Allied.png"}],
        ["m-control-ge", {"f": "m-Control-GE.png"}],
        ["m-disrupted", {"f": "m-Disrupted.png", "b": "m-FullRetreat.png"}],
        ["m-dyleline", {"f": "m-DyleLine.png", "b": "m-Fort-back.png"}],
        ["m-evac", {"f": "m-EVAC.png"}],
        ["m-gqg-1", {"f": "m-GQG-1.png"}],
        ["m-gqg-2", {"f": "m-GQG-2.png"}],
        ["m-gqg-3", {"f": "m-GQG-3.png"}],
        ["m-gqg-4", {"f": "m-GQG-4.png"}],
        ["m-gqg-5", {"f": "m-GQG-5.png"}],
        ["m-gqg-6", {"f": "m-GQG-6.png"}],
        ["m-halt-1", {"f": "m-Halt-1.png"}],
        ["m-halt-2", {"f": "m-Halt-2.png"}],
        ["m-halt-3", {"f": "m-Halt-3.png"}],
        ["m-halt-4", {"f": "m-Halt-4.png"}],
        ["m-halt-5", {"f": "m-Halt-5.png"}],
        ["m-halt-6", {"f": "m-Halt-6.png"}],
        ["m-maynotmove", {"f": "m-MayNotMove.png"}],
        ["m-outofsupply", {"f": "m-OutOfSupply-1.png", "b": "m-OutOfSupply-2.png"}],
        ["m-reserve", {"f": "M-RESERVE.png"}],
        ["m-stuka", {"b": "m-Stuka-back.png", "f": "m-Stuka.png"}],
        ["m-train", {"f": "m-Train.png"}],
        ["m-turn", {"f": "m-Turn-GE.png", "b": "m-Turn-Allied.png"}],
    ]
];